using System.Globalization;
using System.Text.RegularExpressions;
using Compono.XunitV3.Tests.Fixtures;
using Xunit.Sdk;

namespace Compono.XunitV3.Tests;

// Proves the pasteable-seed promise itself, not just a "Seed:" label's presence: a deliberately-
// failing composition propagates the pipeline's own CompositionException unwrapped (ComposeAttribute
// never wraps it), so the seed lives on exception.Diagnostic (the same "Console.WriteLine(exception
// .Diagnostic)" surface docs/architecture.md documents), not on exception.Message directly - unlike
// Compono.XunitV3's own pre-composition exceptions (negative seed, signature errors, inline
// validation), which append a "Seed: <value>" line straight into Message via AppendSeed.
public sealed partial class SeedReportingTests
{
    [Fact]
    public async Task GetData_FailingComposition_DiagnosticSeedFromAnAutoGeneratedRow_ReproducesTheSameFailure_WhenPastedBack()
    {
        var attribute = new ComposeAttribute();
        var method = typeof(SampleTestMethods).GetMethod(nameof(SampleTestMethods.WithUnregisteredInterfaceParameter))!;

        var firstAct = () => attribute.GetData(method, new DisposalTracker()).AsTask();
        var firstException = (await firstAct.Should().ThrowAsync<CompositionException>()).Which;

        var match = SeedLine().Match(firstException.Diagnostic!.ToString());
        match.Success.Should().BeTrue("Diagnostic.ToString() renders the 'Seed: <value>' line docs/architecture.md documents");
        var pastedSeed = int.Parse(match.Groups["seed"].Value, CultureInfo.InvariantCulture);

        var pastedAttribute = new ComposeAttribute { Seed = pastedSeed };
        var secondAct = () => pastedAttribute.GetData(method, new DisposalTracker()).AsTask();
        var secondException = (await secondAct.Should().ThrowAsync<CompositionException>()).Which;

        secondException.Diagnostic!.Seed.Should().Be((ulong)pastedSeed);
    }

    [Fact]
    public async Task GetData_FailingComposition_DiagnosticSeed_MatchesTheExplicitRowSeed()
    {
        const int seed = 7654321;
        var attribute = new ComposeAttribute { Seed = seed };
        var method = typeof(SampleTestMethods).GetMethod(nameof(SampleTestMethods.WithUnregisteredInterfaceParameter))!;

        var act = () => attribute.GetData(method, new DisposalTracker()).AsTask();
        var exception = (await act.Should().ThrowAsync<CompositionException>()).Which;

        exception.Diagnostic!.Seed.Should().Be((ulong)seed);
        exception.Diagnostic.ToString().Should().Contain(seed.ToString(CultureInfo.InvariantCulture));
    }

    [GeneratedRegex(@"Seed: (?<seed>\d+)")]
    private static partial Regex SeedLine();
}
