using System.Globalization;
using System.Text.RegularExpressions;
using Compono.XunitV3.Tests.Fixtures;
using Xunit.Sdk;

namespace Compono.XunitV3.Tests;

// Proves the pasteable-seed promise itself, not just a "Seed:" label's presence, for a genuine
// (pipeline-propagated) composition failure - as opposed to one of Compono.XunitV3's own
// pre-composition exceptions (negative seed, signature errors, inline validation), which already
// append "Seed: <value>" straight into Message via AppendSeed. A pipeline-thrown CompositionException's
// own Message never carried the seed on its own (only exception.Diagnostic did, via its own
// ToString()) - a real test runner's failure display shows Message, not Diagnostic.ToString(), so
// GetData now rewrites it via CompositionException.WithSeedInMessage (PR #26 review; ADR-0022
// Amendment 5) before it propagates. Diagnostic itself (and its own correct Seed/ToString() rendering)
// is untouched by this - these tests check both.
public sealed partial class SeedReportingTests
{
    [Fact]
    public async Task GetData_FailingComposition_MessageContainsTheAutoGeneratedRowSeed_AndReproducesTheSameFailure_WhenPastedBack()
    {
        var attribute = new ComposeAttribute();
        var method = typeof(SampleTestMethods).GetMethod(nameof(SampleTestMethods.WithUnregisteredInterfaceParameter))!;

        var firstAct = () => attribute.GetData(method, new DisposalTracker()).AsTask();
        var firstException = (await firstAct.Should().ThrowAsync<CompositionException>()).Which;

        var match = SeedLine().Match(firstException.Message);
        match.Success.Should().BeTrue("GetData rewrites a propagating composition failure's Message to include a 'Seed: <value>' line");
        var pastedSeed = int.Parse(match.Groups["seed"].Value, CultureInfo.InvariantCulture);

        var pastedAttribute = new ComposeAttribute { Seed = pastedSeed };
        var secondAct = () => pastedAttribute.GetData(method, new DisposalTracker()).AsTask();
        var secondException = (await secondAct.Should().ThrowAsync<CompositionException>()).Which;

        secondException.Message.Should().Contain($"Seed: {pastedSeed}");
    }

    [Fact]
    public async Task GetData_FailingComposition_MessageContainsTheExplicitRowSeed()
    {
        const int seed = 7654321;
        var attribute = new ComposeAttribute { Seed = seed };
        var method = typeof(SampleTestMethods).GetMethod(nameof(SampleTestMethods.WithUnregisteredInterfaceParameter))!;

        var act = () => attribute.GetData(method, new DisposalTracker()).AsTask();
        var exception = (await act.Should().ThrowAsync<CompositionException>()).Which;

        exception.Message.Should().Contain(seed.ToString(CultureInfo.InvariantCulture));
    }

    [Fact]
    public async Task GetData_FailingComposition_DiagnosticIsPreservedUnchanged_AlongsideTheRewrittenMessage()
    {
        const int seed = 987654;
        var attribute = new ComposeAttribute { Seed = seed };
        var method = typeof(SampleTestMethods).GetMethod(nameof(SampleTestMethods.WithUnregisteredInterfaceParameter))!;

        var act = () => attribute.GetData(method, new DisposalTracker()).AsTask();
        var exception = (await act.Should().ThrowAsync<CompositionException>()).Which;

        exception.Diagnostic!.Seed.Should().Be((ulong)seed);
        exception.Diagnostic.Message.Should().NotContain("Seed:", "the wrapped Message carries the seed - Diagnostic's own Message field is left as the pipeline's original plain text");
        exception.InnerException.Should().NotBeNull("the original pipeline exception is preserved, never discarded");
    }

    [GeneratedRegex(@"Seed: (?<seed>\d+)")]
    private static partial Regex SeedLine();
}
