//HintName: int_95e97e5e.RowInvokerRegistration.g.cs
// <auto-generated/>
#nullable enable

[global::System.CodeDom.Compiler.GeneratedCode("Compono.Generators", "REPLACED")]
file static class RowInvokerRegistration
{
    [global::System.Runtime.CompilerServices.ModuleInitializer]
    internal static void Register() =>
        global::Compono.RowInvokerRegistry.Register(
            typeof(int),
            static (row, in descriptor) => row.Resolve<int>(descriptor),
            static (row, in descriptor) => row.ResolveShared<int>(descriptor),
            static (row, in descriptor, value) => row.ShareExplicit(descriptor, (int)value!));
}
