//HintName: TestNamespace.MultipleMethodsTests.Second_method_is_composed_43cfcd9e.AotTheoryDataRowRegistration.g.cs
// <auto-generated/>
#nullable enable

[global::System.CodeDom.Compiler.GeneratedCode("Compono.Generators", "REPLACED")]
file static class AotTheoryDataRowRegistration
{
    [global::System.Runtime.CompilerServices.ModuleInitializer]
    internal static void Register() =>
        global::Xunit.v3.RegisteredEngineConfig.RegisterTheoryDataRowFactory(
            "global::TestNamespace.MultipleMethodsTests",
            "Second_method_is_composed",
            // true (delay enumeration to execution time), matching Compono.XunitV3.ComposeAttribute's
            // own SupportsDiscoveryEnumeration() => false semantics exactly - composition happens
            // once, at real test execution, never during discovery enumeration, for every
            // Compono-composed [Compose] attribute regardless of which xUnit mode discovers it.
            disableDiscoveryEnumeration: true,
            factory: static disposalTracker =>
            {
                var composer = global::Compono.Composer.Create();
                var row = composer.CreateRow(typeof(global::TestNamespace.MultipleMethodsTests));

                var value0 = row.Resolve<int>(new global::Compono.CompositionRequestDescriptor(global::Compono.CompositionRequestKind.TestParameter, 0, "value", typeof(global::TestNamespace.MultipleMethodsTests), global::Compono.Nullability.NotNullable));

                global::System.Collections.Generic.IReadOnlyCollection<global::Xunit.ITheoryDataRow> rows =
                    [new global::Xunit.TheoryDataRow(new object?[] { value0 })];

                return new global::System.Threading.Tasks.ValueTask<global::System.Collections.Generic.IReadOnlyCollection<global::Xunit.ITheoryDataRow>>(rows);
            });
}
