//HintName: System.Collections.Generic.List_global__TestNamespace.Address__793a7b57.CollectionPlan.g.cs
// <auto-generated/>
#nullable enable

[global::System.CodeDom.Compiler.GeneratedCode("Compono.Generators", "REPLACED")]
file sealed class CollectionCompositionPlan : global::Compono.ICompositionPlan<global::System.Collections.Generic.List<global::TestNamespace.Address>>
{
    public global::System.Collections.Generic.List<global::TestNamespace.Address> Compose(global::Compono.ICompositionContext context)
    {
        var size = context.ResolveCollectionSize();
        var result = new global::System.Collections.Generic.List<global::TestNamespace.Address>(size);
        for (var i = 0; i < size; i++)
            result.Add(context.Resolve<global::TestNamespace.Address>(new global::Compono.CompositionRequestDescriptor(global::Compono.CompositionRequestKind.CollectionElement, i, "", null, global::Compono.Nullability.NotNullable)));
        return result;
    }
}

file static class CollectionCompositionPlanRegistration
{
    [global::System.Runtime.CompilerServices.ModuleInitializer]
    internal static void Register() =>
        global::Compono.CollectionPlanCache<global::System.Collections.Generic.List<global::TestNamespace.Address>>.Instance = new CollectionCompositionPlan();
}
