//HintName: TestNamespace.Container_4bba93b8.CompositionPlan.g.cs
// <auto-generated/>
#nullable enable

namespace TestNamespace
{
    [global::System.CodeDom.Compiler.GeneratedCode("Compono.Generators", "REPLACED")]
    file sealed class ContainerCompositionPlan : global::Compono.ICompositionPlan<global::TestNamespace.Container>
    {
        public global::TestNamespace.Container Compose(global::Compono.ICompositionContext context) =>
            new global::TestNamespace.Container(
                context.Resolve<dynamic[]>(new global::Compono.CompositionRequestDescriptor(global::Compono.CompositionRequestKind.ConstructorParameter, 0, "items", global::Compono.Nullability.NotNullable))
            );
    }

    file static class ContainerCompositionPlanRegistration
    {
        [global::System.Runtime.CompilerServices.ModuleInitializer]
        internal static void Register() =>
            global::Compono.PlanCache<global::TestNamespace.Container>.Instance = new ContainerCompositionPlan();
    }
}
