//HintName: System.Collections.Generic.Dictionary_global__System.Guid__string__e164da6b.CollectionPlan.g.cs
// <auto-generated/>
#nullable enable

[global::System.CodeDom.Compiler.GeneratedCode("Compono.Generators", "REPLACED")]
file sealed class CollectionCompositionPlan : global::Compono.ICompositionPlan<global::System.Collections.Generic.Dictionary<global::System.Guid, string>>
{
    public global::System.Collections.Generic.Dictionary<global::System.Guid, string> Compose(global::Compono.ICompositionContext context)
    {
        var result = new global::System.Collections.Generic.Dictionary<global::System.Guid, string>(3);
        var usedKeys = new global::System.Collections.Generic.HashSet<global::System.Guid>(3);
        for (var i = 0; i < 3; i++)
        {
            if (!global::Compono.UniqueValueResolver.TryResolve<global::System.Guid>(context, global::Compono.CompositionRequestKind.DictionaryKey, i, global::Compono.Nullability.NotNullable, usedKeys, out var key))
                throw new global::Compono.CompositionException($"Could not generate 3 unique keys of type '{typeof(global::System.Guid)}' for 'global::System.Collections.Generic.Dictionary<global::System.Guid, string>' after {(global::Compono.UniqueValueResolver.MaxAttempts)} attempts per key - the key type's value space is likely too small for the requested collection size.");

            var value = context.Resolve<string>(new global::Compono.CompositionRequestDescriptor(global::Compono.CompositionRequestKind.DictionaryValue, i, "", global::Compono.Nullability.NotNullable));
            result.Add(key, value);
        }
        return result;
    }
}

file static class CollectionCompositionPlanRegistration
{
    [global::System.Runtime.CompilerServices.ModuleInitializer]
    internal static void Register() =>
        global::Compono.CollectionPlanCache<global::System.Collections.Generic.Dictionary<global::System.Guid, string>>.Instance = new CollectionCompositionPlan();
}
