//HintName: TestNamespace.Customer_6b657459.CompositionPlan.g.cs
// <auto-generated/>
#nullable enable

namespace TestNamespace
{
    [global::System.CodeDom.Compiler.GeneratedCode("Compono.Generators", "REPLACED")]
    file sealed class CustomerCompositionPlan : global::Compono.ICompositionPlan<global::TestNamespace.Customer>
    {
        public global::TestNamespace.Customer Compose(global::Compono.ICompositionContext context) =>
            new global::TestNamespace.Customer(
                context.Resolve<global::System.Collections.Generic.List<global::System.Collections.Generic.List<int>>>(new global::Compono.CompositionRequestDescriptor(global::Compono.CompositionRequestKind.ConstructorParameter, 0, "groups", global::Compono.Nullability.NotNullable))
            );
    }

    file static class CustomerCompositionPlanRegistration
    {
        [global::System.Runtime.CompilerServices.ModuleInitializer]
        internal static void Register() =>
            global::Compono.PlanCache<global::TestNamespace.Customer>.Instance = new CustomerCompositionPlan();
    }
}
