//HintName: System.Collections.Generic.HashSet_int__29bc9bb2.CollectionPlan.g.cs
// <auto-generated/>
#nullable enable

[global::System.CodeDom.Compiler.GeneratedCode("Compono.Generators", "REPLACED")]
file sealed class CollectionCompositionPlan : global::Compono.ICompositionPlan<global::System.Collections.Generic.HashSet<int>>
{
    public global::System.Collections.Generic.HashSet<int> Compose(global::Compono.ICompositionContext context)
    {
        var result = new global::System.Collections.Generic.HashSet<int>(3);
        for (var i = 0; i < 3; i++)
        {
            if (!global::Compono.UniqueValueResolver.TryResolve<int>(context, global::Compono.CompositionRequestKind.CollectionElement, i, global::Compono.Nullability.NotNullable, result, out _))
                throw new global::Compono.CompositionException($"Could not generate 3 unique values of type '{typeof(int)}' for 'global::System.Collections.Generic.HashSet<int>' after {(global::Compono.UniqueValueResolver.MaxAttempts)} attempts per element - the element type's value space is likely too small for the requested collection size.");
        }
        return result;
    }
}

file static class CollectionCompositionPlanRegistration
{
    [global::System.Runtime.CompilerServices.ModuleInitializer]
    internal static void Register() =>
        global::Compono.CollectionPlanCache<global::System.Collections.Generic.HashSet<int>>.Instance = new CollectionCompositionPlan();
}
