//HintName: TestNamespace.Address_5885b993.CompositionPlan.g.cs
// <auto-generated/>
#nullable enable

namespace TestNamespace
{
    [global::System.CodeDom.Compiler.GeneratedCode("Compono.Generators", "REPLACED")]
    file sealed class AddressCompositionPlan : global::Compono.ICompositionPlan<global::TestNamespace.Address>
    {
        public global::TestNamespace.Address Compose(global::Compono.ICompositionContext context) =>
            new global::TestNamespace.Address(
                context.Resolve<string>(new global::Compono.CompositionRequestDescriptor(global::Compono.CompositionRequestKind.ConstructorParameter, 0, "street", typeof(global::TestNamespace.Address), global::Compono.Nullability.NotNullable))
            );
    }

    file static class AddressCompositionPlanRegistration
    {
        [global::System.Runtime.CompilerServices.ModuleInitializer]
        internal static void Register() =>
            global::Compono.PlanCache<global::TestNamespace.Address>.Instance = new AddressCompositionPlan();
    }
}
