//HintName: TestNamespace.CreditNote_2e911510.CompositionPlan.g.cs
// <auto-generated/>
#nullable enable

namespace TestNamespace
{
    [global::System.CodeDom.Compiler.GeneratedCode("Compono.Generators", "REPLACED")]
    file sealed class CreditNoteCompositionPlan : global::Compono.ICompositionPlan<global::TestNamespace.CreditNote>
    {
        public global::TestNamespace.CreditNote Compose(global::Compono.ICompositionContext context) =>
            new global::TestNamespace.CreditNote(
                context.Resolve<string>(new global::Compono.CompositionRequestDescriptor(global::Compono.CompositionRequestKind.ConstructorParameter, 0, "reference", typeof(global::TestNamespace.CreditNote), global::Compono.Nullability.NotNullable))
            );
    }

    file static class CreditNoteCompositionPlanRegistration
    {
        [global::System.Runtime.CompilerServices.ModuleInitializer]
        internal static void Register() =>
            global::Compono.PlanCache<global::TestNamespace.CreditNote>.Instance = new CreditNoteCompositionPlan();
    }
}
