//HintName: TestNamespace.InsurancePolicy_a9987ff9.CompositionPlan.g.cs
// <auto-generated/>
#nullable enable

namespace TestNamespace
{
    [global::System.CodeDom.Compiler.GeneratedCode("Compono.Generators", "REPLACED")]
    file sealed class InsurancePolicyCompositionPlan : global::Compono.ICompositionPlan<global::TestNamespace.InsurancePolicy>
    {
        public global::TestNamespace.InsurancePolicy Compose(global::Compono.ICompositionContext context) =>
            new global::TestNamespace.InsurancePolicy(
                context.Resolve<string>(new global::Compono.CompositionRequestDescriptor(global::Compono.CompositionRequestKind.ConstructorParameter, 0, "policyNumber", typeof(global::TestNamespace.InsurancePolicy), global::Compono.Nullability.NotNullable))
            );
    }

    file static class InsurancePolicyCompositionPlanRegistration
    {
        [global::System.Runtime.CompilerServices.ModuleInitializer]
        internal static void Register() =>
            global::Compono.PlanCache<global::TestNamespace.InsurancePolicy>.Instance = new InsurancePolicyCompositionPlan();
    }
}
