//HintName: Sales.Customer.CompositionPlan.g.cs
// <auto-generated/>
#nullable enable

namespace Sales
{
    [global::System.CodeDom.Compiler.GeneratedCode("Compono.Generators", "REPLACED")]
    internal sealed class CustomerCompositionPlan : global::Compono.ICompositionPlan<Sales.Customer>
    {
        public Sales.Customer Compose(global::Compono.ICompositionContext context) =>
            new Sales.Customer(
                context.Resolve<string>()
            );
    }

    file static class CustomerCompositionPlanRegistration
    {
        [System.Runtime.CompilerServices.ModuleInitializer]
        internal static void Register() =>
            global::Compono.PlanCache<Sales.Customer>.Instance = new CustomerCompositionPlan();
    }
}
