//HintName: Sales.Customer_d17c7a30.CompositionPlan.g.cs
// <auto-generated/>
#nullable enable

namespace Sales
{
    [global::System.CodeDom.Compiler.GeneratedCode("Compono.Generators", "REPLACED")]
    file sealed class CustomerCompositionPlan : global::Compono.ICompositionPlan<global::Sales.Customer>
    {
        public global::Sales.Customer Compose(global::Compono.ICompositionContext context) =>
            new global::Sales.Customer(
                context.Resolve<string>(new global::Compono.CompositionRequestDescriptor(global::Compono.CompositionRequestKind.ConstructorParameter, 0, "name", global::Compono.Nullability.NotNullable))
            );
    }

    file static class CustomerCompositionPlanRegistration
    {
        [global::System.Runtime.CompilerServices.ModuleInitializer]
        internal static void Register() =>
            global::Compono.PlanCache<global::Sales.Customer>.Instance = new CustomerCompositionPlan();
    }
}
