//HintName: Support.Customer.CompositionPlan.g.cs
// <auto-generated/>
#nullable enable

namespace Support
{
    [global::System.CodeDom.Compiler.GeneratedCode("Compono.Generators", "REPLACED")]
    internal sealed class CustomerCompositionPlan : global::Compono.ICompositionPlan<Support.Customer>
    {
        public Support.Customer Compose(global::Compono.ICompositionContext context) =>
            new Support.Customer(
                context.Resolve<string>()
            );
    }

    file static class CustomerCompositionPlanRegistration
    {
        [System.Runtime.CompilerServices.ModuleInitializer]
        internal static void Register() =>
            global::Compono.PlanCache<Support.Customer>.Instance = new CustomerCompositionPlan();
    }
}
