//HintName: Support.Customer_058f8a61.CompositionPlan.g.cs
// <auto-generated/>
#nullable enable

namespace Support
{
    [global::System.CodeDom.Compiler.GeneratedCode("Compono.Generators", "REPLACED")]
    file sealed class CustomerCompositionPlan : global::Compono.ICompositionPlan<global::Support.Customer>
    {
        public global::Support.Customer Compose(global::Compono.ICompositionContext context) =>
            new global::Support.Customer(
                context.Resolve<string>(new global::Compono.CompositionRequestDescriptor(global::Compono.CompositionRequestKind.ConstructorParameter, 0, "name", typeof(global::Support.Customer), global::Compono.Nullability.NotNullable))
            );
    }

    file static class CustomerCompositionPlanRegistration
    {
        [global::System.Runtime.CompilerServices.ModuleInitializer]
        internal static void Register() =>
            global::Compono.PlanCache<global::Support.Customer>.Instance = new CustomerCompositionPlan();
    }
}
