//HintName: TestNamespace.PurchaseOrder_e2a52f3a.CompositionPlan.g.cs
// <auto-generated/>
#nullable enable

namespace TestNamespace
{
    [global::System.CodeDom.Compiler.GeneratedCode("Compono.Generators", "REPLACED")]
    file sealed class PurchaseOrderCompositionPlan : global::Compono.ICompositionPlan<global::TestNamespace.PurchaseOrder>
    {
        public global::TestNamespace.PurchaseOrder Compose(global::Compono.ICompositionContext context) =>
            new global::TestNamespace.PurchaseOrder(
                context.Resolve<string>(new global::Compono.CompositionRequestDescriptor(global::Compono.CompositionRequestKind.ConstructorParameter, 0, "reference", typeof(global::TestNamespace.PurchaseOrder), global::Compono.Nullability.NotNullable))
            );
    }

    file static class PurchaseOrderCompositionPlanRegistration
    {
        [global::System.Runtime.CompilerServices.ModuleInitializer]
        internal static void Register() =>
            global::Compono.PlanCache<global::TestNamespace.PurchaseOrder>.Instance = new PurchaseOrderCompositionPlan();
    }
}
