//HintName: TestNamespace.Foo_int__a6752344.CompositionPlan.g.cs
// <auto-generated/>
#nullable enable

namespace TestNamespace
{
    [global::System.CodeDom.Compiler.GeneratedCode("Compono.Generators", "REPLACED")]
    file sealed class FooCompositionPlan : global::Compono.ICompositionPlan<global::TestNamespace.Foo<int>>
    {
        public global::TestNamespace.Foo<int> Compose(global::Compono.ICompositionContext context) =>
            new global::TestNamespace.Foo<int>(
                context.Resolve<int>(global::Compono.Nullability.NotNullable)
            );
    }

    file static class FooCompositionPlanRegistration
    {
        [global::System.Runtime.CompilerServices.ModuleInitializer]
        internal static void Register() =>
            global::Compono.PlanCache<global::TestNamespace.Foo<int>>.Instance = new FooCompositionPlan();
    }
}
