//HintName: TestNamespace.Invoice_091ea950.CompositionPlan.g.cs
// <auto-generated/>
#nullable enable

namespace TestNamespace
{
    [global::System.CodeDom.Compiler.GeneratedCode("Compono.Generators", "REPLACED")]
    file sealed class InvoiceCompositionPlan : global::Compono.ICompositionPlan<global::TestNamespace.Invoice>
    {
        public global::TestNamespace.Invoice Compose(global::Compono.ICompositionContext context) =>
            new global::TestNamespace.Invoice(
                context.Resolve<string>(new global::Compono.CompositionRequestDescriptor(global::Compono.CompositionRequestKind.ConstructorParameter, 0, "reference", typeof(global::TestNamespace.Invoice), global::Compono.Nullability.NotNullable))
            );
    }

    file static class InvoiceCompositionPlanRegistration
    {
        [global::System.Runtime.CompilerServices.ModuleInitializer]
        internal static void Register() =>
            global::Compono.PlanCache<global::TestNamespace.Invoice>.Instance = new InvoiceCompositionPlan();
    }
}
