//HintName: TestNamespace.DeliveryReceipt_08e6cff3.CompositionPlan.g.cs
// <auto-generated/>
#nullable enable

namespace TestNamespace
{
    [global::System.CodeDom.Compiler.GeneratedCode("Compono.Generators", "REPLACED")]
    file sealed class DeliveryReceiptCompositionPlan : global::Compono.ICompositionPlan<global::TestNamespace.DeliveryReceipt>
    {
        public global::TestNamespace.DeliveryReceipt Compose(global::Compono.ICompositionContext context) =>
            new global::TestNamespace.DeliveryReceipt(
                context.Resolve<string>(new global::Compono.CompositionRequestDescriptor(global::Compono.CompositionRequestKind.ConstructorParameter, 0, "confirmationCode", typeof(global::TestNamespace.DeliveryReceipt), global::Compono.Nullability.NotNullable))
            );
    }

    file static class DeliveryReceiptCompositionPlanRegistration
    {
        [global::System.Runtime.CompilerServices.ModuleInitializer]
        internal static void Register() =>
            global::Compono.PlanCache<global::TestNamespace.DeliveryReceipt>.Instance = new DeliveryReceiptCompositionPlan();
    }
}
