//HintName: TestNamespace.Dog_eda06f49.CompositionPlan.g.cs
// <auto-generated/>
#nullable enable

namespace TestNamespace
{
    [global::System.CodeDom.Compiler.GeneratedCode("Compono.Generators", "REPLACED")]
    file sealed class DogCompositionPlan : global::Compono.ICompositionPlan<global::TestNamespace.Dog>
    {
        public global::TestNamespace.Dog Compose(global::Compono.ICompositionContext context) =>
            new global::TestNamespace.Dog(
            )
            {
                Species = context.Resolve<string>(new global::Compono.CompositionRequestDescriptor(global::Compono.CompositionRequestKind.RequiredMember, 0, "Species", typeof(global::TestNamespace.Animal), global::Compono.Nullability.NotNullable)),
                LegCount = context.Resolve<int>(new global::Compono.CompositionRequestDescriptor(global::Compono.CompositionRequestKind.RequiredMember, 1, "LegCount", typeof(global::TestNamespace.Animal), global::Compono.Nullability.NotNullable)),
                Name = context.Resolve<string>(new global::Compono.CompositionRequestDescriptor(global::Compono.CompositionRequestKind.RequiredMember, 2, "Name", typeof(global::TestNamespace.Dog), global::Compono.Nullability.NotNullable))
            };
    }

    file static class DogCompositionPlanRegistration
    {
        [global::System.Runtime.CompilerServices.ModuleInitializer]
        internal static void Register() =>
            global::Compono.PlanCache<global::TestNamespace.Dog>.Instance = new DogCompositionPlan();
    }
}
