//HintName: Customer_fb78d532.CompositionPlan.g.cs
// <auto-generated/>
#nullable enable

    [global::System.CodeDom.Compiler.GeneratedCode("Compono.Generators", "REPLACED")]
    file sealed class CustomerCompositionPlan : global::Compono.ICompositionPlan<global::Customer>
    {
        public global::Customer Compose(global::Compono.ICompositionContext context) =>
            new global::Customer(
                context.Resolve<string>(new global::Compono.CompositionRequestDescriptor(global::Compono.CompositionRequestKind.ConstructorParameter, 0, "firstName", global::Compono.Nullability.NotNullable))
            );
    }

    file static class CustomerCompositionPlanRegistration
    {
        [global::System.Runtime.CompilerServices.ModuleInitializer]
        internal static void Register() =>
            global::Compono.PlanCache<global::Customer>.Instance = new CustomerCompositionPlan();
    }
