//HintName: TestNamespace.Widget_ab440545.CompositionPlan.g.cs
// <auto-generated/>
#nullable enable

namespace TestNamespace
{
    [global::System.CodeDom.Compiler.GeneratedCode("Compono.Generators", "REPLACED")]
    file sealed class WidgetCompositionPlan : global::Compono.ICompositionPlan<global::TestNamespace.Widget>
    {
        public global::TestNamespace.Widget Compose(global::Compono.ICompositionContext context) =>
            new global::TestNamespace.Widget(
            )
            {
                @class = context.Resolve<string>(new global::Compono.CompositionRequestDescriptor(global::Compono.CompositionRequestKind.RequiredMember, 0, "class", global::Compono.Nullability.NotNullable))
            };
    }

    file static class WidgetCompositionPlanRegistration
    {
        [global::System.Runtime.CompilerServices.ModuleInitializer]
        internal static void Register() =>
            global::Compono.PlanCache<global::TestNamespace.Widget>.Instance = new WidgetCompositionPlan();
    }
}
