//HintName: TestNamespace.Box_int__c05d8e37.CompositionPlan.g.cs
// <auto-generated/>
#nullable enable

namespace TestNamespace
{
    [global::System.CodeDom.Compiler.GeneratedCode("Compono.Generators", "REPLACED")]
    file sealed class BoxCompositionPlan : global::Compono.ICompositionPlan<global::TestNamespace.Box<int>>
    {
        public global::TestNamespace.Box<int> Compose(global::Compono.ICompositionContext context) =>
            new global::TestNamespace.Box<int>(
                context.Resolve<int>()
            );
    }

    file static class BoxCompositionPlanRegistration
    {
        [System.Runtime.CompilerServices.ModuleInitializer]
        internal static void Register() =>
            global::Compono.PlanCache<global::TestNamespace.Box<int>>.Instance = new BoxCompositionPlan();
    }
}
