//HintName: TestNamespace.ShippingLabel_3e792a8b.RowInvokerRegistration.g.cs
// <auto-generated/>
#nullable enable

[global::System.CodeDom.Compiler.GeneratedCode("Compono.Generators", "REPLACED")]
file static class RowInvokerRegistration
{
    [global::System.Runtime.CompilerServices.ModuleInitializer]
    internal static void Register() =>
        global::Compono.RowInvokerRegistry.Register(
            typeof(global::TestNamespace.ShippingLabel),
            static (row, in descriptor) => row.Resolve<global::TestNamespace.ShippingLabel>(descriptor),
            static (row, in descriptor) => row.ResolveShared<global::TestNamespace.ShippingLabel>(descriptor),
            static (row, in descriptor, value) => row.ShareExplicit(descriptor, (global::TestNamespace.ShippingLabel)value!));
}
