//HintName: TestNamespace.Box_string__8834a427.CompositionPlan.g.cs
// <auto-generated/>
#nullable enable

namespace TestNamespace
{
    [global::System.CodeDom.Compiler.GeneratedCode("Compono.Generators", "REPLACED")]
    file sealed class BoxCompositionPlan : global::Compono.ICompositionPlan<global::TestNamespace.Box<string>>
    {
        public global::TestNamespace.Box<string> Compose(global::Compono.ICompositionContext context) =>
            new global::TestNamespace.Box<string>(
                context.Resolve<string>()
            );
    }

    file static class BoxCompositionPlanRegistration
    {
        [global::System.Runtime.CompilerServices.ModuleInitializer]
        internal static void Register() =>
            global::Compono.PlanCache<global::TestNamespace.Box<string>>.Instance = new BoxCompositionPlan();
    }
}
