//HintName: SpikeRepeated.Foo_1f4e446c.CompositionPlan.g.cs
// <auto-generated/>
#nullable enable

namespace SpikeRepeated
{
    [global::System.CodeDom.Compiler.GeneratedCode("Compono.Generators", "REPLACED")]
    file sealed class FooCompositionPlan : global::Compono.ICompositionPlan<global::SpikeRepeated.Foo>
    {
        public global::SpikeRepeated.Foo Compose(global::Compono.ICompositionContext context) =>
            new global::SpikeRepeated.Foo(
                context.Resolve<global::SpikeRepeated.IBar>(new global::Compono.CompositionRequestDescriptor(global::Compono.CompositionRequestKind.ConstructorParameter, 0, "bar", typeof(global::SpikeRepeated.Foo), global::Compono.Nullability.NotNullable)),
                context.Resolve<global::SpikeRepeated.IBaz>(new global::Compono.CompositionRequestDescriptor(global::Compono.CompositionRequestKind.ConstructorParameter, 1, "baz", typeof(global::SpikeRepeated.Foo), global::Compono.Nullability.NotNullable))
            );
    }

    file static class FooCompositionPlanRegistration
    {
        [global::System.Runtime.CompilerServices.ModuleInitializer]
        internal static void Register() =>
            global::Compono.PlanCache<global::SpikeRepeated.Foo>.Instance = new FooCompositionPlan();
    }
}
