//HintName: Spike.Outer_2823b7fd.CompositionPlan.g.cs
// <auto-generated/>
#nullable enable

namespace Spike
{
    [global::System.CodeDom.Compiler.GeneratedCode("Compono.Generators", "REPLACED")]
    file sealed class OuterCompositionPlan : global::Compono.ICompositionPlan<global::Spike.Outer>
    {
        public global::Spike.Outer Compose(global::Compono.ICompositionContext context) =>
            new global::Spike.Outer(
                context.Resolve<global::Spike.Foo>(new global::Compono.CompositionRequestDescriptor(global::Compono.CompositionRequestKind.ConstructorParameter, 0, "foo", typeof(global::Spike.Outer), global::Compono.Nullability.NotNullable))
            );
    }

    file static class OuterCompositionPlanRegistration
    {
        [global::System.Runtime.CompilerServices.ModuleInitializer]
        internal static void Register() =>
            global::Compono.PlanCache<global::Spike.Outer>.Instance = new OuterCompositionPlan();
    }
}
