//HintName: SpikeNullConditional.Foo_30b96565.CompositionPlan.g.cs
// <auto-generated/>
#nullable enable

namespace SpikeNullConditional
{
    [global::System.CodeDom.Compiler.GeneratedCode("Compono.Generators", "REPLACED")]
    file sealed class FooCompositionPlan : global::Compono.ICompositionPlan<global::SpikeNullConditional.Foo>
    {
        public global::SpikeNullConditional.Foo Compose(global::Compono.ICompositionContext context) =>
            new global::SpikeNullConditional.Foo(
                context.Resolve<global::SpikeNullConditional.IBar>(new global::Compono.CompositionRequestDescriptor(global::Compono.CompositionRequestKind.ConstructorParameter, 0, "bar", typeof(global::SpikeNullConditional.Foo), global::Compono.Nullability.NotNullable))
            );
    }

    file static class FooCompositionPlanRegistration
    {
        [global::System.Runtime.CompilerServices.ModuleInitializer]
        internal static void Register() =>
            global::Compono.PlanCache<global::SpikeNullConditional.Foo>.Instance = new FooCompositionPlan();
    }
}
