//HintName: TestNamespace.IThing_7b7b47c0.TestDouble.g.cs
// <auto-generated/>
#nullable enable

// PLAN-0063/ADR-0060: ClearCalls() reaches every ADR-0049 closed-instantiation-eligible member's
// per-closed-T bucket entries generically, with no static knowledge of which closed T's exist at
// runtime - this non-generic interface (implemented by every generated
// TestNamespace_IThing_7b7b47c0_*State<T> class below) is what makes that possible without reflection.
internal interface TestNamespace_IThing_7b7b47c0_IClearableCallState
{
    void ClearObservedCalls();
}

[global::System.CodeDom.Compiler.GeneratedCode("Compono.Generators", "REPLACED")]
internal sealed class TestNamespace_IThing_7b7b47c0_Double : global::TestNamespace.IThing
{
    internal global::Compono.ReturnConfig<global::Compono.Unit> __Configure;

    void global::TestNamespace.IThing.Configure<T>()
    {
        __Configure.RecordCall();
        if (__Configure.HasConfiguredSequence)
            __Configure.NextSequenceOutcome();
        else if (__Configure.HasConfiguredException)
            throw __Configure.ConfiguredException;
    }
}

internal static class TestNamespace_IThing_7b7b47c0_DoubleConfiguration
{
    public static global::Compono.ReturnConfigBuilder<global::Compono.Unit> Configure(this global::TestNamespace_IThing_7b7b47c0_Double self) =>
        new global::Compono.ReturnConfigBuilder<global::Compono.Unit>(ref self.__Configure);

}

internal readonly struct TestNamespace_IThing_7b7b47c0_DoubleVerifier
{
    internal global::TestNamespace_IThing_7b7b47c0_Double Instance { get; }

    internal TestNamespace_IThing_7b7b47c0_DoubleVerifier(global::TestNamespace_IThing_7b7b47c0_Double instance) => Instance = instance;
}

internal static class TestNamespace_IThing_7b7b47c0_VerifyExtension
{
    public static global::TestNamespace_IThing_7b7b47c0_DoubleVerifier Verify(this global::TestNamespace.IThing self) =>
        new(self as global::TestNamespace_IThing_7b7b47c0_Double
            ?? throw new global::System.InvalidOperationException(
                $"'{self.GetType()}' is not the 'global::TestNamespace.IThing' test double generated for this assembly. " +
                "If another assembly in this process also generated a double for 'global::TestNamespace.IThing', only one " +
                "registration wins process-wide (Compono.GeneratedTestDoubleRegistry, first-registration-wins) " +
                "- this is a known v1 limitation, not a bug in your test."));
}

internal static class TestNamespace_IThing_7b7b47c0_DoubleVerification
{
    public static global::Compono.CallVerifier Configure(this global::TestNamespace_IThing_7b7b47c0_DoubleVerifier self) =>
        new(self.Instance.__Configure.ConfiguredCallCount, "global::TestNamespace.IThing.Configure");

}

// PLAN-0063/ADR-0060: ReceivedCalls() - retrospective, snapshot-based call inspection, scoped to
// exactly the ADR-0048 eligible-member set (member.is_eligible_for_matching), unexpanded. A
// distinct third bridge from Configure()/Verify() - never attaches captured data to CallVerifier.
internal readonly struct TestNamespace_IThing_7b7b47c0_DoubleReceivedCalls
{
    internal global::TestNamespace_IThing_7b7b47c0_Double Instance { get; }

    internal TestNamespace_IThing_7b7b47c0_DoubleReceivedCalls(global::TestNamespace_IThing_7b7b47c0_Double instance) => Instance = instance;
}

internal static class TestNamespace_IThing_7b7b47c0_ReceivedCallsExtension
{
    public static global::TestNamespace_IThing_7b7b47c0_DoubleReceivedCalls ReceivedCalls(this global::TestNamespace.IThing self) =>
        new(self as global::TestNamespace_IThing_7b7b47c0_Double
            ?? throw new global::System.InvalidOperationException(
                $"'{self.GetType()}' is not the 'global::TestNamespace.IThing' test double generated for this assembly. " +
                "If another assembly in this process also generated a double for 'global::TestNamespace.IThing', only one " +
                "registration wins process-wide (Compono.GeneratedTestDoubleRegistry, first-registration-wins) " +
                "- this is a known v1 limitation, not a bug in your test."));
}

internal static class TestNamespace_IThing_7b7b47c0_DoubleReceivedCallsAccess
{
}

// PLAN-0063/ADR-0060: ClearCalls() - a direct, whole-double operation clearing every member's
// observation state (scalar call counts + ADR-0048 captured argument histories) while preserving
// all configured behavior (Returns/Throws/ReturnsCallback/ReturnsSequence - including in-progress
// SequenceOrdinal, which does not rewind - argument-matcher/multi-entry configuration, and generic
// closed-instantiation configuration). No per-member ClearCalls(), no global whole-double lock -
// each member's own existing synchronization primitive is used independently, per member.
internal static class TestNamespace_IThing_7b7b47c0_ClearCallsExtension
{
    public static void ClearCalls(this global::TestNamespace.IThing self)
    {
        var __double = self as global::TestNamespace_IThing_7b7b47c0_Double
            ?? throw new global::System.InvalidOperationException(
                $"'{self.GetType()}' is not the 'global::TestNamespace.IThing' test double generated for this assembly. " +
                "If another assembly in this process also generated a double for 'global::TestNamespace.IThing', only one " +
                "registration wins process-wide (Compono.GeneratedTestDoubleRegistry, first-registration-wins) " +
                "- this is a known v1 limitation, not a bug in your test.");

        __double.__Configure.ClearObservedCalls();
    }
}

internal static class TestNamespace_IThing_7b7b47c0_ConfigureExtension
{
    public static global::TestNamespace_IThing_7b7b47c0_Double Configure(this global::TestNamespace.IThing self) =>
        self as global::TestNamespace_IThing_7b7b47c0_Double
            ?? throw new global::System.InvalidOperationException(
                $"'{self.GetType()}' is not the 'global::TestNamespace.IThing' test double generated for this assembly. " +
                "If another assembly in this process also generated a double for 'global::TestNamespace.IThing', only one " +
                "registration wins process-wide (Compono.GeneratedTestDoubleRegistry, first-registration-wins) " +
                "- this is a known v1 limitation, not a bug in your test.");
}

file static class TestNamespace_IThing_7b7b47c0_DoubleRegistration
{
    [global::System.Runtime.CompilerServices.ModuleInitializer]
    internal static void Register() =>
        global::Compono.GeneratedTestDoubleRegistry.RegisterFactory<global::TestNamespace.IThing>(
            () => new global::TestNamespace_IThing_7b7b47c0_Double());
}
