//HintName: TestNamespace.IRepository_e3198068.TestDouble.g.cs
// <auto-generated/>
#nullable enable

[global::System.CodeDom.Compiler.GeneratedCode("Compono.Generators", "REPLACED")]
internal sealed class TestNamespace_IRepository_e3198068_Double : global::TestNamespace.IRepository
{
    internal global::Compono.ReturnConfig<bool> __Equals_37c3f22f;
    internal global::Compono.ReturnConfig<bool> __Equals_693d6b44;

    bool global::TestNamespace.IRepository.Equals(global::System.Span<int> value)
    {
        __Equals_37c3f22f.RecordCall();
        return __Equals_37c3f22f.HasConfiguredException ? throw __Equals_37c3f22f.ConfiguredException
            : __Equals_37c3f22f.HasConfiguredValue ? __Equals_37c3f22f.ConfiguredValue
            : default;
    }

    bool global::TestNamespace.IRepository.Equals(int a, int b)
    {
        __Equals_693d6b44.RecordCall();
        return __Equals_693d6b44.HasConfiguredException ? throw __Equals_693d6b44.ConfiguredException
            : __Equals_693d6b44.HasConfiguredValue ? __Equals_693d6b44.ConfiguredValue
            : default;
    }
}

internal static class TestNamespace_IRepository_e3198068_DoubleConfiguration
{
    public static global::Compono.ReturnConfigBuilder<bool> Equals(this global::TestNamespace_IRepository_e3198068_Double __self, global::System.Span<int> value) =>
        new global::Compono.ReturnConfigBuilder<bool>(ref __self.__Equals_37c3f22f);

    public static global::Compono.ReturnConfigBuilder<bool> Equals(this global::TestNamespace_IRepository_e3198068_Double __self, int a, int b) =>
        new global::Compono.ReturnConfigBuilder<bool>(ref __self.__Equals_693d6b44);

}

internal readonly struct TestNamespace_IRepository_e3198068_DoubleVerifier
{
    internal global::TestNamespace_IRepository_e3198068_Double Instance { get; }

    internal TestNamespace_IRepository_e3198068_DoubleVerifier(global::TestNamespace_IRepository_e3198068_Double instance) => Instance = instance;
}

internal static class TestNamespace_IRepository_e3198068_VerifyExtension
{
    public static global::TestNamespace_IRepository_e3198068_DoubleVerifier Verify(this global::TestNamespace.IRepository self) =>
        new(self as global::TestNamespace_IRepository_e3198068_Double
            ?? throw new global::System.InvalidOperationException(
                $"'{self.GetType()}' is not the 'global::TestNamespace.IRepository' test double generated for this assembly. " +
                "If another assembly in this process also generated a double for 'global::TestNamespace.IRepository', only one " +
                "registration wins process-wide (Compono.GeneratedTestDoubleRegistry, first-registration-wins) " +
                "- this is a known v1 limitation, not a bug in your test."));
}

internal static class TestNamespace_IRepository_e3198068_DoubleVerification
{
    public static global::Compono.CallVerifier Equals(this global::TestNamespace_IRepository_e3198068_DoubleVerifier __self, global::System.Span<int> value) =>
        new(__self.Instance.__Equals_37c3f22f.ConfiguredCallCount, "global::TestNamespace.IRepository.Equals");

    public static global::Compono.CallVerifier Equals(this global::TestNamespace_IRepository_e3198068_DoubleVerifier __self, int a, int b) =>
        new(__self.Instance.__Equals_693d6b44.ConfiguredCallCount, "global::TestNamespace.IRepository.Equals");

}

internal static class TestNamespace_IRepository_e3198068_ConfigureExtension
{
    public static global::TestNamespace_IRepository_e3198068_Double Configure(this global::TestNamespace.IRepository self) =>
        self as global::TestNamespace_IRepository_e3198068_Double
            ?? throw new global::System.InvalidOperationException(
                $"'{self.GetType()}' is not the 'global::TestNamespace.IRepository' test double generated for this assembly. " +
                "If another assembly in this process also generated a double for 'global::TestNamespace.IRepository', only one " +
                "registration wins process-wide (Compono.GeneratedTestDoubleRegistry, first-registration-wins) " +
                "- this is a known v1 limitation, not a bug in your test.");
}

file static class TestNamespace_IRepository_e3198068_DoubleRegistration
{
    [global::System.Runtime.CompilerServices.ModuleInitializer]
    internal static void Register() =>
        global::Compono.GeneratedTestDoubleRegistry.RegisterFactory<global::TestNamespace.IRepository>(
            () => new global::TestNamespace_IRepository_e3198068_Double());
}
