//HintName: TestNamespace.IContextManager_d05603ce.TestDouble.g.cs
// <auto-generated/>
#nullable enable

[global::System.CodeDom.Compiler.GeneratedCode("Compono.Generators", "REPLACED")]
internal sealed class TestNamespace_IContextManager_d05603ce_Double : global::TestNamespace.IContextManager
{
    internal sealed class __GetContextDataAsync_State<T> where T : class
    {
        // ADR-0050: multi-entry response configuration composed inside ADR-0049's
        // per-closed-T state - same Entry shape as the plain matching-eligible branch below, just
        // nested one level deeper (per closed T instead of per member).
        internal sealed class Entry
        {
            internal global::Compono.Match<string>? Matcher_key;
            internal global::Compono.ReturnConfig<global::System.Threading.Tasks.Task<T?>> Config;
        }

        internal readonly global::System.Collections.Generic.List<Entry> Entries = [];
        internal readonly global::System.Collections.Generic.List<string> Calls = [];
        internal readonly object Lock = new();
    }

    internal readonly global::System.Collections.Generic.Dictionary<global::System.Type, object> __GetContextDataAsync_buckets = new();

    internal __GetContextDataAsync_State<T> __GetContextDataAsync_Bucket<T>() where T : class
    {
        lock (__GetContextDataAsync_buckets)
        {
            if (!__GetContextDataAsync_buckets.TryGetValue(typeof(T), out var __boxed))
            {
                __boxed = new __GetContextDataAsync_State<T>();
                __GetContextDataAsync_buckets[typeof(T)] = __boxed;
            }

            return (__GetContextDataAsync_State<T>)__boxed;
        }
    }

#pragma warning disable CS8603, CS8616, CS8619
    global::System.Threading.Tasks.Task<T> global::TestNamespace.IContextManager.GetContextDataAsync<T>(string key)
    {
        var __bucket = __GetContextDataAsync_Bucket<T>();
        // ADR-0050: reverse-scan the ordered entry list - last matching registration wins.
        lock (__bucket.Lock) { __bucket.Calls.Add(key); }
        for (var __i = __bucket.Entries.Count - 1; __i >= 0; __i--)
        {
            var __entry = __bucket.Entries[__i];
            if ((__entry.Matcher_key is not { } __m_key || __m_key.Matches(key)))
            {
                if (__entry.Config.HasConfiguredException) throw __entry.Config.ConfiguredException;
                if (__entry.Config.HasConfiguredValue) return __entry.Config.ConfiguredValue;
                break;
            }
        }
        return global::System.Threading.Tasks.Task.FromResult<T?>(default);
    }
#pragma warning restore CS8603, CS8616, CS8619
}

internal static class TestNamespace_IContextManager_d05603ce_DoubleConfiguration
{
    public static global::Compono.ReturnConfigBuilder<global::System.Threading.Tasks.Task<T?>> GetContextDataAsync<T>(this global::TestNamespace_IContextManager_d05603ce_Double __self, global::Compono.Match<string> key) where T : class
    {
        // ADR-0050: appends a new entry rather than overwriting the (removed) single
        // slot - `ref entry.Config` stays valid regardless of later Entries.Add() reallocating the
        // list's backing array, since the ref targets the Entry object itself (heap-stable), not a
        // slot inside the list's array. See spike report for the reallocation-hazard proof.
        var __bucket = __self.__GetContextDataAsync_Bucket<T>();
        var __entry = new global::TestNamespace_IContextManager_d05603ce_Double.__GetContextDataAsync_State<T>.Entry();
        __entry.Matcher_key = key;
        __bucket.Entries.Add(__entry);
        return new global::Compono.ReturnConfigBuilder<global::System.Threading.Tasks.Task<T?>>(ref __entry.Config);
    }

}

internal readonly struct TestNamespace_IContextManager_d05603ce_DoubleVerifier
{
    internal global::TestNamespace_IContextManager_d05603ce_Double Instance { get; }

    internal TestNamespace_IContextManager_d05603ce_DoubleVerifier(global::TestNamespace_IContextManager_d05603ce_Double instance) => Instance = instance;
}

internal static class TestNamespace_IContextManager_d05603ce_VerifyExtension
{
    public static global::TestNamespace_IContextManager_d05603ce_DoubleVerifier Verify(this global::TestNamespace.IContextManager self) =>
        new(self as global::TestNamespace_IContextManager_d05603ce_Double
            ?? throw new global::System.InvalidOperationException(
                $"'{self.GetType()}' is not the 'global::TestNamespace.IContextManager' test double generated for this assembly. " +
                "If another assembly in this process also generated a double for 'global::TestNamespace.IContextManager', only one " +
                "registration wins process-wide (Compono.GeneratedTestDoubleRegistry, first-registration-wins) " +
                "- this is a known v1 limitation, not a bug in your test."));
}

internal static class TestNamespace_IContextManager_d05603ce_DoubleVerification
{
    public static global::Compono.CallVerifier GetContextDataAsync<T>(this global::TestNamespace_IContextManager_d05603ce_DoubleVerifier __self, global::Compono.Match<string> key) where T : class
    {
        var __bucket = __self.Instance.__GetContextDataAsync_Bucket<T>();
        int __count;
        lock (__bucket.Lock)
        {
            __count = 0;
            foreach (var call in __bucket.Calls)
            {
                if (key.Matches(call))
                    __count++;
            }
        }
        return new(__count, "global::TestNamespace.IContextManager.GetContextDataAsync");
    }

}

internal static class TestNamespace_IContextManager_d05603ce_ConfigureExtension
{
    public static global::TestNamespace_IContextManager_d05603ce_Double Configure(this global::TestNamespace.IContextManager self) =>
        self as global::TestNamespace_IContextManager_d05603ce_Double
            ?? throw new global::System.InvalidOperationException(
                $"'{self.GetType()}' is not the 'global::TestNamespace.IContextManager' test double generated for this assembly. " +
                "If another assembly in this process also generated a double for 'global::TestNamespace.IContextManager', only one " +
                "registration wins process-wide (Compono.GeneratedTestDoubleRegistry, first-registration-wins) " +
                "- this is a known v1 limitation, not a bug in your test.");
}

file static class TestNamespace_IContextManager_d05603ce_DoubleRegistration
{
    [global::System.Runtime.CompilerServices.ModuleInitializer]
    internal static void Register() =>
        global::Compono.GeneratedTestDoubleRegistry.RegisterFactory<global::TestNamespace.IContextManager>(
            () => new global::TestNamespace_IContextManager_d05603ce_Double());
}
