//HintName: TestNamespace.IRepository_e3198068.TestDouble.g.cs
// <auto-generated/>
#nullable enable

[global::System.CodeDom.Compiler.GeneratedCode("Compono.Generators", "REPLACED")]
internal sealed class TestNamespace_IRepository_e3198068_Double : global::TestNamespace.IRepository
{
    internal global::Compono.ReturnConfig<global::System.Threading.Tasks.Task<string?>> __FindNameAsync;
    internal global::Compono.ReturnConfig<global::Compono.Unit> __Save;
    internal global::Compono.ReturnConfig<int> __Count;
    internal global::Compono.Match<global::System.Guid>? __FindNameAsync_m_id;
    internal readonly global::System.Collections.Generic.List<global::System.Guid> __FindNameAsync_calls = [];
    internal readonly object __FindNameAsync_lock = new();
    internal global::Compono.Match<string>? __Save_m_name;
    internal readonly global::System.Collections.Generic.List<string> __Save_calls = [];
    internal readonly object __Save_lock = new();

    global::System.Threading.Tasks.Task<string?> global::TestNamespace.IRepository.FindNameAsync(global::System.Guid id)
    {
        __FindNameAsync.RecordCall();
        lock (__FindNameAsync_lock) { __FindNameAsync_calls.Add(id); }
        var __matches = (__FindNameAsync_m_id is not { } __m_id || __m_id.Matches(id));
        return __matches && __FindNameAsync.HasConfiguredException ? throw __FindNameAsync.ConfiguredException
            : __matches && __FindNameAsync.HasConfiguredValue ? __FindNameAsync.ConfiguredValue
            : global::System.Threading.Tasks.Task.FromResult<string?>(default);
    }

    void global::TestNamespace.IRepository.Save(string name)
    {
        __Save.RecordCall();
        lock (__Save_lock) { __Save_calls.Add(name); }
        var __matches = (__Save_m_name is not { } __m_name || __m_name.Matches(name));
        if (__matches && __Save.HasConfiguredException)
            throw __Save.ConfiguredException;
    }

    int global::TestNamespace.IRepository.Count
    {
        get
        {
            __Count.RecordCall();
            return __Count.HasConfiguredException ? throw __Count.ConfiguredException
                : __Count.HasConfiguredValue ? __Count.ConfiguredValue
                : default;
        }
        set
        {
            __Count.RecordCall();
            new global::Compono.ReturnConfigBuilder<int>(ref __Count).Returns(value);
        }
    }
}

internal static class TestNamespace_IRepository_e3198068_DoubleConfiguration
{
    public static global::Compono.ReturnConfigBuilder<global::System.Threading.Tasks.Task<string?>> FindNameAsync(this global::TestNamespace_IRepository_e3198068_Double self, global::Compono.Match<global::System.Guid> id)
    {
        self.__FindNameAsync_m_id = id;
        return new global::Compono.ReturnConfigBuilder<global::System.Threading.Tasks.Task<string?>>(ref self.__FindNameAsync);
    }

    // Compatibility overload (Codex review, PLAN-0048): v1/v2 gave every non-overloaded member a
    // zero-argument Configure(), regardless of real arity - a real existing call site
    // (Compono.TestDoubles.SampleTests' Save(int) usage) still uses it. Leaving every matcher field
    // null reproduces that exact argument-independent behavior (dispatch's `is not { } m ||
    // m.Matches(...)` treats null as always-matching), so this overload is purely additive, not a
    // second, different meaning.
    public static global::Compono.ReturnConfigBuilder<global::System.Threading.Tasks.Task<string?>> FindNameAsync(this global::TestNamespace_IRepository_e3198068_Double self) =>
        new global::Compono.ReturnConfigBuilder<global::System.Threading.Tasks.Task<string?>>(ref self.__FindNameAsync);

    public static global::Compono.ReturnConfigBuilder<global::Compono.Unit> Save(this global::TestNamespace_IRepository_e3198068_Double self, global::Compono.Match<string> name)
    {
        self.__Save_m_name = name;
        return new global::Compono.ReturnConfigBuilder<global::Compono.Unit>(ref self.__Save);
    }

    // Compatibility overload (Codex review, PLAN-0048): v1/v2 gave every non-overloaded member a
    // zero-argument Configure(), regardless of real arity - a real existing call site
    // (Compono.TestDoubles.SampleTests' Save(int) usage) still uses it. Leaving every matcher field
    // null reproduces that exact argument-independent behavior (dispatch's `is not { } m ||
    // m.Matches(...)` treats null as always-matching), so this overload is purely additive, not a
    // second, different meaning.
    public static global::Compono.ReturnConfigBuilder<global::Compono.Unit> Save(this global::TestNamespace_IRepository_e3198068_Double self) =>
        new global::Compono.ReturnConfigBuilder<global::Compono.Unit>(ref self.__Save);

    public static global::Compono.ReturnConfigBuilder<int> Count(this global::TestNamespace_IRepository_e3198068_Double self) =>
        new global::Compono.ReturnConfigBuilder<int>(ref self.__Count);

}

internal readonly struct TestNamespace_IRepository_e3198068_DoubleVerifier
{
    internal global::TestNamespace_IRepository_e3198068_Double Instance { get; }

    internal TestNamespace_IRepository_e3198068_DoubleVerifier(global::TestNamespace_IRepository_e3198068_Double instance) => Instance = instance;
}

internal static class TestNamespace_IRepository_e3198068_VerifyExtension
{
    public static global::TestNamespace_IRepository_e3198068_DoubleVerifier Verify(this global::TestNamespace.IRepository self) =>
        new(self as global::TestNamespace_IRepository_e3198068_Double
            ?? throw new global::System.InvalidOperationException(
                $"'{self.GetType()}' is not the 'global::TestNamespace.IRepository' test double generated for this assembly. " +
                "If another assembly in this process also generated a double for 'global::TestNamespace.IRepository', only one " +
                "registration wins process-wide (Compono.GeneratedTestDoubleRegistry, first-registration-wins) " +
                "- this is a known v1 limitation, not a bug in your test."));
}

internal static class TestNamespace_IRepository_e3198068_DoubleVerification
{
    public static global::Compono.CallVerifier FindNameAsync(this global::TestNamespace_IRepository_e3198068_DoubleVerifier self, global::Compono.Match<global::System.Guid> id)
    {
        int __count;
        lock (self.Instance.__FindNameAsync_lock)
        {
            __count = 0;
            foreach (var call in self.Instance.__FindNameAsync_calls)
            {
                if (id.Matches(call))
                    __count++;
            }
        }
        return new(__count, "global::TestNamespace.IRepository.FindNameAsync");
    }

    // Compatibility overload - same reasoning as DoubleConfiguration's zero-argument sibling above:
    // reuses the still-maintained, unfiltered ConfiguredCallCount rather than walking the call log,
    // reproducing v1/v2's exact argument-independent Verify() for this member.
    public static global::Compono.CallVerifier FindNameAsync(this global::TestNamespace_IRepository_e3198068_DoubleVerifier self) =>
        new(self.Instance.__FindNameAsync.ConfiguredCallCount, "global::TestNamespace.IRepository.FindNameAsync");

    public static global::Compono.CallVerifier Save(this global::TestNamespace_IRepository_e3198068_DoubleVerifier self, global::Compono.Match<string> name)
    {
        int __count;
        lock (self.Instance.__Save_lock)
        {
            __count = 0;
            foreach (var call in self.Instance.__Save_calls)
            {
                if (name.Matches(call))
                    __count++;
            }
        }
        return new(__count, "global::TestNamespace.IRepository.Save");
    }

    // Compatibility overload - same reasoning as DoubleConfiguration's zero-argument sibling above:
    // reuses the still-maintained, unfiltered ConfiguredCallCount rather than walking the call log,
    // reproducing v1/v2's exact argument-independent Verify() for this member.
    public static global::Compono.CallVerifier Save(this global::TestNamespace_IRepository_e3198068_DoubleVerifier self) =>
        new(self.Instance.__Save.ConfiguredCallCount, "global::TestNamespace.IRepository.Save");

    public static global::Compono.CallVerifier Count(this global::TestNamespace_IRepository_e3198068_DoubleVerifier self) =>
        new(self.Instance.__Count.ConfiguredCallCount, "global::TestNamespace.IRepository.Count");

}

internal static class TestNamespace_IRepository_e3198068_ConfigureExtension
{
    public static global::TestNamespace_IRepository_e3198068_Double Configure(this global::TestNamespace.IRepository self) =>
        self as global::TestNamespace_IRepository_e3198068_Double
            ?? throw new global::System.InvalidOperationException(
                $"'{self.GetType()}' is not the 'global::TestNamespace.IRepository' test double generated for this assembly. " +
                "If another assembly in this process also generated a double for 'global::TestNamespace.IRepository', only one " +
                "registration wins process-wide (Compono.GeneratedTestDoubleRegistry, first-registration-wins) " +
                "- this is a known v1 limitation, not a bug in your test.");
}

file static class TestNamespace_IRepository_e3198068_DoubleRegistration
{
    [global::System.Runtime.CompilerServices.ModuleInitializer]
    internal static void Register() =>
        global::Compono.GeneratedTestDoubleRegistry.RegisterFactory<global::TestNamespace.IRepository>(
            () => new global::TestNamespace_IRepository_e3198068_Double());
}
