//HintName: TestNamespace.IRepository_e3198068.TestDouble.g.cs
// <auto-generated/>
#nullable enable

// PLAN-0063/ADR-0060: ClearCalls() reaches every ADR-0049 closed-instantiation-eligible member's
// per-closed-T bucket entries generically, with no static knowledge of which closed T's exist at
// runtime - this non-generic interface (implemented by every generated
// TestNamespace_IRepository_e3198068_*State<T> class below) is what makes that possible without reflection.
internal interface TestNamespace_IRepository_e3198068_IClearableCallState
{
    void ClearObservedCalls();
}

[global::System.CodeDom.Compiler.GeneratedCode("Compono.Generators", "REPLACED")]
internal sealed class TestNamespace_IRepository_e3198068_Double : global::TestNamespace.IRepository
{
    internal delegate int __Foo_Callback(int __Foo_ReceivedCall);

    internal readonly ref struct __Foo_Builder
    {
        private readonly ref global::Compono.ReturnConfig<int> _config;
        private readonly ref __Foo_Callback? _callback;

        internal __Foo_Builder(ref global::Compono.ReturnConfig<int> config, ref __Foo_Callback? callback)
        {
            _config = ref config;
            _callback = ref callback;
        }

        public void Returns(int value)
        {
            _callback = null;
            new global::Compono.ReturnConfigBuilder<int>(ref _config).Returns(value);
        }

        public void Throws(global::System.Exception exception)
        {
            _callback = null;
            new global::Compono.ReturnConfigBuilder<int>(ref _config).Throws(exception);
        }

        public void ReturnsSequence(params global::Compono.SequenceOutcome<int>[] outcomes)
        {
            _callback = null;
            new global::Compono.ReturnConfigBuilder<int>(ref _config).ReturnsSequence(outcomes);
        }

        public void ReturnsCallback(__Foo_Callback callback)
        {
            global::System.ArgumentNullException.ThrowIfNull(callback);
            _config.ClearConfiguredResponse();
            _callback = callback;
        }
    }
    // ADR-0050: multi-entry response configuration - replaces the single
    // __Foo/__Foo_m_{param} shape with an ordered, append-only
    // entry list. Configure() appends; dispatch scans in reverse (last-matching-registration-wins).
    internal sealed class __Foo_Entry
    {
        internal global::Compono.Match<int>? Matcher___Foo_ReceivedCall;
        internal global::Compono.ReturnConfig<int> Config;
        internal __Foo_Callback? Callback;
    }

    internal readonly global::System.Collections.Generic.List<__Foo_Entry> __Foo_entries = [];
    internal readonly global::System.Collections.Generic.List<int> __Foo_calls = [];
    internal readonly object __Foo_lock = new();

    // PLAN-0063/ADR-0060: named snapshot record backing ReceivedCalls() for this eligible member -
    // one field per real parameter, real parameter names (not the positional "Item1"/"Item2" the
    // internal __Foo_calls tuple above uses for its own, unrelated, internal-only
    // matching purpose). Not emitted for an overload-matching-eligible member - ReceivedCalls() is
    // scoped to exactly ADR-0048's non-overloaded eligible-member set for 1.1.
    // A parameter literally named the same as this record's own type (e.g. a real member
    // `Foo(int __Foo_ReceivedCall)`) would otherwise produce a positional property with the same
    // name as its enclosing type - CS0542 - since a record's declared parameter name IS its public
    // property name; suffixed with "_Value" in that one case (Codex review, PR #134). Two real
    // parameters can never already share a name (the compiler already guarantees that for the real
    // member this record mirrors), so at most one parameter in this list ever needs the suffix.
    internal readonly record struct __Foo_ReceivedCall(int __Foo_ReceivedCall_Value);

    int global::TestNamespace.IRepository.Foo(int __Foo_ReceivedCall)
    {
        __Foo_Callback? __callback = null;
        // ADR-0050: reverse-scan the ordered entry list - last matching registration wins. Both
        // the call-log append and the full scan stay under the SAME lock acquisition as
        // Configure()'s Add() (Codex review, PR #108 round 5) - the prior split-lock shape (a
        // short lock around _calls.Add() only, then an unlocked scan) let a concurrent Configure()
        // call mutate List<T>'s backing array while dispatch was still iterating it. `return`/
        // `throw` inside a C# `lock` block still releases the lock (try/finally under the hood).
        lock (__Foo_lock)
        {
            __Foo_calls.Add(__Foo_ReceivedCall);
            for (var __i = __Foo_entries.Count - 1; __i >= 0; __i--)
            {
                var __entry = __Foo_entries[__i];
                if ((__entry.Matcher___Foo_ReceivedCall is not { } __m___Foo_ReceivedCall || __m___Foo_ReceivedCall.Matches(__Foo_ReceivedCall)))
                {
                    if (__entry.Callback is { } configuredCallback)
                    {
                        __callback = configuredCallback;
                        break;
                    }
                    // ADR-0050: no `break` here (Codex review, PR #108 round 6) - if this entry
                    // matched but has neither a configured exception nor a configured value (e.g.
                    // its builder is still being set up when this call arrives), it must NOT shadow
                    // an older, fully-configured matching entry; the scan continues to the next
                    // (older) entry instead of falling through to the default/required-config rule.
                    // ADR-0054: a configured sequence is checked first - Returns/Throws/ReturnsSequence
                    // are mutually exclusive on one Config, so order between this and the two checks
                    // below doesn't change behavior, but leads with the newest-added capability.
                    if (__entry.Config.HasConfiguredSequence) return __entry.Config.NextSequenceOutcome();
                    if (__entry.Config.HasConfiguredException) throw __entry.Config.ConfiguredException;
                    if (__entry.Config.HasConfiguredValue) return __entry.Config.ConfiguredValue;
                }
            }
        }
        if (__callback is { } callback)
            return callback(__Foo_ReceivedCall);
        return default;
    }
}

internal static class TestNamespace_IRepository_e3198068_DoubleConfiguration
{
    public static global::TestNamespace_IRepository_e3198068_Double.__Foo_Builder Foo(this global::TestNamespace_IRepository_e3198068_Double __self, global::Compono.Match<int> __Foo_ReceivedCall)
    {
        // ADR-0050: appends a new entry - see the closed-instantiation Configure()
        // above for the reallocation-hazard proof, identical reasoning applies here. The Add()
        // itself is under the same member lock dispatch scans under (Codex review, PR #108
        // round 5).
        var __entry = new global::TestNamespace_IRepository_e3198068_Double.__Foo_Entry();
        __entry.Matcher___Foo_ReceivedCall = __Foo_ReceivedCall;
        lock (__self.__Foo_lock) { __self.__Foo_entries.Add(__entry); }
        return new global::TestNamespace_IRepository_e3198068_Double.__Foo_Builder(ref __entry.Config, ref __entry.Callback);
    }

    // Compatibility overload (Codex review, PLAN-0048): v1/v2 gave every non-overloaded member a
    // zero-argument Configure(), regardless of real arity. ADR-0050: under multi-entry,
    // this no longer needs to null out prior matchers to reproduce "last wins" - it just appends its
    // own new, all-null-matcher (always-matching) entry; being the most-recently-appended entry, the
    // reverse scan finds it before any earlier, more specific entry, exactly reproducing v1/v2's
    // argument-independent override behavior without mutating any earlier entry's state at all.
    public static global::TestNamespace_IRepository_e3198068_Double.__Foo_Builder Foo(this global::TestNamespace_IRepository_e3198068_Double self)
    {
        var __entry = new global::TestNamespace_IRepository_e3198068_Double.__Foo_Entry();
        lock (self.__Foo_lock) { self.__Foo_entries.Add(__entry); }
        return new global::TestNamespace_IRepository_e3198068_Double.__Foo_Builder(ref __entry.Config, ref __entry.Callback);
    }

}

internal readonly struct TestNamespace_IRepository_e3198068_DoubleVerifier
{
    internal global::TestNamespace_IRepository_e3198068_Double Instance { get; }

    internal TestNamespace_IRepository_e3198068_DoubleVerifier(global::TestNamespace_IRepository_e3198068_Double instance) => Instance = instance;
}

internal static class TestNamespace_IRepository_e3198068_VerifyExtension
{
    public static global::TestNamespace_IRepository_e3198068_DoubleVerifier Verify(this global::TestNamespace.IRepository self) =>
        new(self as global::TestNamespace_IRepository_e3198068_Double
            ?? throw new global::System.InvalidOperationException(
                $"'{self.GetType()}' is not the 'global::TestNamespace.IRepository' test double generated for this assembly. " +
                "If another assembly in this process also generated a double for 'global::TestNamespace.IRepository', only one " +
                "registration wins process-wide (Compono.GeneratedTestDoubleRegistry, first-registration-wins) " +
                "- this is a known v1 limitation, not a bug in your test."));
}

internal static class TestNamespace_IRepository_e3198068_DoubleVerification
{
    public static global::Compono.CallVerifier Foo(this global::TestNamespace_IRepository_e3198068_DoubleVerifier __self, global::Compono.Match<int> __Foo_ReceivedCall)
    {
        int __count;
        lock (__self.Instance.__Foo_lock)
        {
            __count = 0;
            foreach (var call in __self.Instance.__Foo_calls)
            {
                if (__Foo_ReceivedCall.Matches(call))
                    __count++;
            }
        }
        return new(__count, "global::TestNamespace.IRepository.Foo");
    }

    // Compatibility overload - ADR-0050: the removed single-slot field no longer
    // tracks a call count at all (RecordCall() is gone from dispatch for this shape) - the call
    // log's own Count, under its existing lock, is exactly the same number and is already
    // maintained regardless of how many response entries exist.
    public static global::Compono.CallVerifier Foo(this global::TestNamespace_IRepository_e3198068_DoubleVerifier self)
    {
        int __count;
        lock (self.Instance.__Foo_lock) { __count = self.Instance.__Foo_calls.Count; }
        return new(__count, "global::TestNamespace.IRepository.Foo");
    }

}

// PLAN-0063/ADR-0060: ReceivedCalls() - retrospective, snapshot-based call inspection, scoped to
// exactly the ADR-0048 eligible-member set (member.is_eligible_for_matching), unexpanded. A
// distinct third bridge from Configure()/Verify() - never attaches captured data to CallVerifier.
internal readonly struct TestNamespace_IRepository_e3198068_DoubleReceivedCalls
{
    internal global::TestNamespace_IRepository_e3198068_Double Instance { get; }

    internal TestNamespace_IRepository_e3198068_DoubleReceivedCalls(global::TestNamespace_IRepository_e3198068_Double instance) => Instance = instance;
}

internal static class TestNamespace_IRepository_e3198068_ReceivedCallsExtension
{
    public static global::TestNamespace_IRepository_e3198068_DoubleReceivedCalls ReceivedCalls(this global::TestNamespace.IRepository self) =>
        new(self as global::TestNamespace_IRepository_e3198068_Double
            ?? throw new global::System.InvalidOperationException(
                $"'{self.GetType()}' is not the 'global::TestNamespace.IRepository' test double generated for this assembly. " +
                "If another assembly in this process also generated a double for 'global::TestNamespace.IRepository', only one " +
                "registration wins process-wide (Compono.GeneratedTestDoubleRegistry, first-registration-wins) " +
                "- this is a known v1 limitation, not a bug in your test."));
}

internal static class TestNamespace_IRepository_e3198068_DoubleReceivedCallsAccess
{
    // Snapshot under the same ADR-0048 per-member lock Verify()'s own scan already uses - no live
    // mutable collection is ever returned, per ADR-0060's snapshot-semantics decision.
    public static global::System.Collections.Generic.IReadOnlyList<global::TestNamespace_IRepository_e3198068_Double.__Foo_ReceivedCall> Foo(this global::TestNamespace_IRepository_e3198068_DoubleReceivedCalls self)
    {
        lock (self.Instance.__Foo_lock)
        {
            var __snapshot = new global::TestNamespace_IRepository_e3198068_Double.__Foo_ReceivedCall[self.Instance.__Foo_calls.Count];
            for (var __i = 0; __i < __snapshot.Length; __i++)
            {
                var call = self.Instance.__Foo_calls[__i];
                __snapshot[__i] = new(call);
            }

            return __snapshot;
        }
    }

}

// PLAN-0063/ADR-0060: ClearCalls() - a direct, whole-double operation clearing every member's
// observation state (scalar call counts + ADR-0048 captured argument histories) while preserving
// all configured behavior (Returns/Throws/ReturnsCallback/ReturnsSequence - including in-progress
// SequenceOrdinal, which does not rewind - argument-matcher/multi-entry configuration, and generic
// closed-instantiation configuration). No per-member ClearCalls(), no global whole-double lock -
// each member's own existing synchronization primitive is used independently, per member.
internal static class TestNamespace_IRepository_e3198068_ClearCallsExtension
{
    public static void ClearCalls(this global::TestNamespace.IRepository self)
    {
        var __double = self as global::TestNamespace_IRepository_e3198068_Double
            ?? throw new global::System.InvalidOperationException(
                $"'{self.GetType()}' is not the 'global::TestNamespace.IRepository' test double generated for this assembly. " +
                "If another assembly in this process also generated a double for 'global::TestNamespace.IRepository', only one " +
                "registration wins process-wide (Compono.GeneratedTestDoubleRegistry, first-registration-wins) " +
                "- this is a known v1 limitation, not a bug in your test.");

        lock (__double.__Foo_lock) { __double.__Foo_calls.Clear(); }
    }
}

internal static class TestNamespace_IRepository_e3198068_ConfigureExtension
{
    public static global::TestNamespace_IRepository_e3198068_Double Configure(this global::TestNamespace.IRepository self) =>
        self as global::TestNamespace_IRepository_e3198068_Double
            ?? throw new global::System.InvalidOperationException(
                $"'{self.GetType()}' is not the 'global::TestNamespace.IRepository' test double generated for this assembly. " +
                "If another assembly in this process also generated a double for 'global::TestNamespace.IRepository', only one " +
                "registration wins process-wide (Compono.GeneratedTestDoubleRegistry, first-registration-wins) " +
                "- this is a known v1 limitation, not a bug in your test.");
}

file static class TestNamespace_IRepository_e3198068_DoubleRegistration
{
    [global::System.Runtime.CompilerServices.ModuleInitializer]
    internal static void Register() =>
        global::Compono.GeneratedTestDoubleRegistry.RegisterFactory<global::TestNamespace.IRepository>(
            () => new global::TestNamespace_IRepository_e3198068_Double());
}
