//HintName: TestNamespace.IContextManager_d05603ce.TestDouble.g.cs
// <auto-generated/>
#nullable enable

[global::System.CodeDom.Compiler.GeneratedCode("Compono.Generators", "REPLACED")]
internal sealed class TestNamespace_IContextManager_d05603ce_Double : global::TestNamespace.IContextManager
{
    internal sealed class __GetDataAsync_97bed815_State<T> where T : class
    {
        internal global::Compono.ReturnConfig<global::System.Threading.Tasks.Task<T?>> Config;
    }

    internal readonly global::System.Collections.Generic.Dictionary<global::System.Type, object> __GetDataAsync_97bed815_buckets = new();

    internal __GetDataAsync_97bed815_State<T> __GetDataAsync_97bed815_Bucket<T>() where T : class
    {
        lock (__GetDataAsync_97bed815_buckets)
        {
            if (!__GetDataAsync_97bed815_buckets.TryGetValue(typeof(T), out var __boxed))
            {
                __boxed = new __GetDataAsync_97bed815_State<T>();
                __GetDataAsync_97bed815_buckets[typeof(T)] = __boxed;
            }

            return (__GetDataAsync_97bed815_State<T>)__boxed;
        }
    }
    internal sealed class __GetDataAsync_1aae9cd0_State<T> where T : class
    {
        internal global::Compono.ReturnConfig<global::System.Threading.Tasks.Task<T?>> Config;
    }

    internal readonly global::System.Collections.Generic.Dictionary<global::System.Type, object> __GetDataAsync_1aae9cd0_buckets = new();

    internal __GetDataAsync_1aae9cd0_State<T> __GetDataAsync_1aae9cd0_Bucket<T>() where T : class
    {
        lock (__GetDataAsync_1aae9cd0_buckets)
        {
            if (!__GetDataAsync_1aae9cd0_buckets.TryGetValue(typeof(T), out var __boxed))
            {
                __boxed = new __GetDataAsync_1aae9cd0_State<T>();
                __GetDataAsync_1aae9cd0_buckets[typeof(T)] = __boxed;
            }

            return (__GetDataAsync_1aae9cd0_State<T>)__boxed;
        }
    }

#pragma warning disable CS8603, CS8616, CS8619
    global::System.Threading.Tasks.Task<T> global::TestNamespace.IContextManager.GetDataAsync<T>(string id)
    {
        var __bucket = __GetDataAsync_97bed815_Bucket<T>();
        __bucket.Config.RecordCall();
        return __bucket.Config.HasConfiguredException ? throw __bucket.Config.ConfiguredException
            : __bucket.Config.HasConfiguredValue ? __bucket.Config.ConfiguredValue
            : global::System.Threading.Tasks.Task.FromResult<T?>(default);
    }
#pragma warning restore CS8603, CS8616, CS8619

#pragma warning disable CS8603, CS8616, CS8619
    global::System.Threading.Tasks.Task<T> global::TestNamespace.IContextManager.GetDataAsync<T>(string id, int version)
    {
        var __bucket = __GetDataAsync_1aae9cd0_Bucket<T>();
        __bucket.Config.RecordCall();
        return __bucket.Config.HasConfiguredException ? throw __bucket.Config.ConfiguredException
            : __bucket.Config.HasConfiguredValue ? __bucket.Config.ConfiguredValue
            : global::System.Threading.Tasks.Task.FromResult<T?>(default);
    }
#pragma warning restore CS8603, CS8616, CS8619
}

internal static class TestNamespace_IContextManager_d05603ce_DoubleConfiguration
{
    public static global::Compono.ReturnConfigBuilder<global::System.Threading.Tasks.Task<T?>> GetDataAsync<T>(this global::TestNamespace_IContextManager_d05603ce_Double __self, string id) where T : class
    {
        var __bucket = __self.__GetDataAsync_97bed815_Bucket<T>();
        return new global::Compono.ReturnConfigBuilder<global::System.Threading.Tasks.Task<T?>>(ref __bucket.Config);
    }

    public static global::Compono.ReturnConfigBuilder<global::System.Threading.Tasks.Task<T?>> GetDataAsync<T>(this global::TestNamespace_IContextManager_d05603ce_Double __self, string id, int version) where T : class
    {
        var __bucket = __self.__GetDataAsync_1aae9cd0_Bucket<T>();
        return new global::Compono.ReturnConfigBuilder<global::System.Threading.Tasks.Task<T?>>(ref __bucket.Config);
    }

}

internal readonly struct TestNamespace_IContextManager_d05603ce_DoubleVerifier
{
    internal global::TestNamespace_IContextManager_d05603ce_Double Instance { get; }

    internal TestNamespace_IContextManager_d05603ce_DoubleVerifier(global::TestNamespace_IContextManager_d05603ce_Double instance) => Instance = instance;
}

internal static class TestNamespace_IContextManager_d05603ce_VerifyExtension
{
    public static global::TestNamespace_IContextManager_d05603ce_DoubleVerifier Verify(this global::TestNamespace.IContextManager self) =>
        new(self as global::TestNamespace_IContextManager_d05603ce_Double
            ?? throw new global::System.InvalidOperationException(
                $"'{self.GetType()}' is not the 'global::TestNamespace.IContextManager' test double generated for this assembly. " +
                "If another assembly in this process also generated a double for 'global::TestNamespace.IContextManager', only one " +
                "registration wins process-wide (Compono.GeneratedTestDoubleRegistry, first-registration-wins) " +
                "- this is a known v1 limitation, not a bug in your test."));
}

internal static class TestNamespace_IContextManager_d05603ce_DoubleVerification
{
    public static global::Compono.CallVerifier GetDataAsync<T>(this global::TestNamespace_IContextManager_d05603ce_DoubleVerifier __self, string id) where T : class =>
        new(__self.Instance.__GetDataAsync_97bed815_Bucket<T>().Config.ConfiguredCallCount, "global::TestNamespace.IContextManager.GetDataAsync");

    public static global::Compono.CallVerifier GetDataAsync<T>(this global::TestNamespace_IContextManager_d05603ce_DoubleVerifier __self, string id, int version) where T : class =>
        new(__self.Instance.__GetDataAsync_1aae9cd0_Bucket<T>().Config.ConfiguredCallCount, "global::TestNamespace.IContextManager.GetDataAsync");

}

internal static class TestNamespace_IContextManager_d05603ce_ConfigureExtension
{
    public static global::TestNamespace_IContextManager_d05603ce_Double Configure(this global::TestNamespace.IContextManager self) =>
        self as global::TestNamespace_IContextManager_d05603ce_Double
            ?? throw new global::System.InvalidOperationException(
                $"'{self.GetType()}' is not the 'global::TestNamespace.IContextManager' test double generated for this assembly. " +
                "If another assembly in this process also generated a double for 'global::TestNamespace.IContextManager', only one " +
                "registration wins process-wide (Compono.GeneratedTestDoubleRegistry, first-registration-wins) " +
                "- this is a known v1 limitation, not a bug in your test.");
}

file static class TestNamespace_IContextManager_d05603ce_DoubleRegistration
{
    [global::System.Runtime.CompilerServices.ModuleInitializer]
    internal static void Register() =>
        global::Compono.GeneratedTestDoubleRegistry.RegisterFactory<global::TestNamespace.IContextManager>(
            () => new global::TestNamespace_IContextManager_d05603ce_Double());
}
