//HintName: TestNamespace.ICollision_e0157ffc.TestDouble.g.cs
// <auto-generated/>
#nullable enable

[global::System.CodeDom.Compiler.GeneratedCode("Compono.Generators", "REPLACED")]
internal sealed class TestNamespace_ICollision_e0157ffc_Double : global::TestNamespace.ICollision
{
    internal global::Compono.ReturnConfig<bool> __Foo;
    internal global::Compono.ReturnConfig<global::Compono.Unit> __Foo_dimHelper;

    bool global::TestNamespace.ICollision.Foo()
    {
        __Foo.RecordCall();
        return __Foo.HasConfiguredSequence ? __Foo.NextSequenceOutcome()
            : __Foo.HasConfiguredException ? throw __Foo.ConfiguredException
            : __Foo.HasConfiguredValue ? __Foo.ConfiguredValue
            : default;
    }

    void global::TestNamespace.ICollision.Foo_dimHelper()
    {
        __Foo_dimHelper.RecordCall();
        if (__Foo_dimHelper.HasConfiguredSequence)
            __Foo_dimHelper.NextSequenceOutcome();
        else if (__Foo_dimHelper.HasConfiguredException)
            throw __Foo_dimHelper.ConfiguredException;
    }
}

internal static class TestNamespace_ICollision_e0157ffc_DoubleConfiguration
{
    public static global::Compono.ReturnConfigBuilder<bool> Foo(this global::TestNamespace_ICollision_e0157ffc_Double self) =>
        new global::Compono.ReturnConfigBuilder<bool>(ref self.__Foo);

    public static global::Compono.ReturnConfigBuilder<global::Compono.Unit> Foo_dimHelper(this global::TestNamespace_ICollision_e0157ffc_Double self) =>
        new global::Compono.ReturnConfigBuilder<global::Compono.Unit>(ref self.__Foo_dimHelper);

}

internal readonly struct TestNamespace_ICollision_e0157ffc_DoubleVerifier
{
    internal global::TestNamespace_ICollision_e0157ffc_Double Instance { get; }

    internal TestNamespace_ICollision_e0157ffc_DoubleVerifier(global::TestNamespace_ICollision_e0157ffc_Double instance) => Instance = instance;
}

internal static class TestNamespace_ICollision_e0157ffc_VerifyExtension
{
    public static global::TestNamespace_ICollision_e0157ffc_DoubleVerifier Verify(this global::TestNamespace.ICollision self) =>
        new(self as global::TestNamespace_ICollision_e0157ffc_Double
            ?? throw new global::System.InvalidOperationException(
                $"'{self.GetType()}' is not the 'global::TestNamespace.ICollision' test double generated for this assembly. " +
                "If another assembly in this process also generated a double for 'global::TestNamespace.ICollision', only one " +
                "registration wins process-wide (Compono.GeneratedTestDoubleRegistry, first-registration-wins) " +
                "- this is a known v1 limitation, not a bug in your test."));
}

internal static class TestNamespace_ICollision_e0157ffc_DoubleVerification
{
    public static global::Compono.CallVerifier Foo(this global::TestNamespace_ICollision_e0157ffc_DoubleVerifier self) =>
        new(self.Instance.__Foo.ConfiguredCallCount, "global::TestNamespace.ICollision.Foo");

    public static global::Compono.CallVerifier Foo_dimHelper(this global::TestNamespace_ICollision_e0157ffc_DoubleVerifier self) =>
        new(self.Instance.__Foo_dimHelper.ConfiguredCallCount, "global::TestNamespace.ICollision.Foo_dimHelper");

}

internal static class TestNamespace_ICollision_e0157ffc_ConfigureExtension
{
    public static global::TestNamespace_ICollision_e0157ffc_Double Configure(this global::TestNamespace.ICollision self) =>
        self as global::TestNamespace_ICollision_e0157ffc_Double
            ?? throw new global::System.InvalidOperationException(
                $"'{self.GetType()}' is not the 'global::TestNamespace.ICollision' test double generated for this assembly. " +
                "If another assembly in this process also generated a double for 'global::TestNamespace.ICollision', only one " +
                "registration wins process-wide (Compono.GeneratedTestDoubleRegistry, first-registration-wins) " +
                "- this is a known v1 limitation, not a bug in your test.");
}

file static class TestNamespace_ICollision_e0157ffc_DoubleRegistration
{
    [global::System.Runtime.CompilerServices.ModuleInitializer]
    internal static void Register() =>
        global::Compono.GeneratedTestDoubleRegistry.RegisterFactory<global::TestNamespace.ICollision>(
            () => new global::TestNamespace_ICollision_e0157ffc_Double());
}
