//HintName: TestNamespace.IRepository_e3198068.TestDouble.g.cs
// <auto-generated/>
#nullable enable

[global::System.CodeDom.Compiler.GeneratedCode("Compono.Generators", "REPLACED")]
internal sealed class TestNamespace_IRepository_e3198068_Double : global::TestNamespace.IRepository
{
    internal global::Compono.ReturnConfig<global::Compono.Unit> __Seek;
    internal global::Compono.Match<int>? __Seek_m_offset;
    internal readonly global::System.Collections.Generic.List<int> __Seek_calls = [];
    internal readonly object __Seek_lock = new();

    void global::TestNamespace.IRepository.Seek(ref readonly int offset)
    {
    }

    void global::TestNamespace.IRepository.Seek(int offset)
    {
        __Seek.RecordCall();
        lock (__Seek_lock) { __Seek_calls.Add(offset); }
        var __matches = (__Seek_m_offset is not { } __m_offset || __m_offset.Matches(offset));
        if (__matches && __Seek.HasConfiguredException)
            throw __Seek.ConfiguredException;
    }
}

internal static class TestNamespace_IRepository_e3198068_DoubleConfiguration
{
    public static global::Compono.ReturnConfigBuilder<global::Compono.Unit> Seek(this global::TestNamespace_IRepository_e3198068_Double __self, global::Compono.Match<int> offset)
    {
        __self.__Seek_m_offset = offset;
        return new global::Compono.ReturnConfigBuilder<global::Compono.Unit>(ref __self.__Seek);
    }

    // Compatibility overload (Codex review, PLAN-0048): v1/v2 gave every non-overloaded member a
    // zero-argument Configure(), regardless of real arity - a real existing call site
    // (Compono.TestDoubles.SampleTests' Save(int) usage) still uses it. Explicitly clearing every
    // matcher field (not merely leaving them alone) is what makes this overload reproduce v1/v2's
    // exact argument-independent behavior even on a double a prior Configure() call already gave
    // matchers to - dispatch's `is not { } m || m.Matches(...)` treats null as always-matching, so a
    // second call through this overload has to actually null them out, not just skip setting new
    // ones, to make "the second Configure() call overwrites" true regardless of which overload either
    // call went through (Codex review, PR #106).
    public static global::Compono.ReturnConfigBuilder<global::Compono.Unit> Seek(this global::TestNamespace_IRepository_e3198068_Double self)
    {
        self.__Seek_m_offset = null;
        return new global::Compono.ReturnConfigBuilder<global::Compono.Unit>(ref self.__Seek);
    }

}

internal readonly struct TestNamespace_IRepository_e3198068_DoubleVerifier
{
    internal global::TestNamespace_IRepository_e3198068_Double Instance { get; }

    internal TestNamespace_IRepository_e3198068_DoubleVerifier(global::TestNamespace_IRepository_e3198068_Double instance) => Instance = instance;
}

internal static class TestNamespace_IRepository_e3198068_VerifyExtension
{
    public static global::TestNamespace_IRepository_e3198068_DoubleVerifier Verify(this global::TestNamespace.IRepository self) =>
        new(self as global::TestNamespace_IRepository_e3198068_Double
            ?? throw new global::System.InvalidOperationException(
                $"'{self.GetType()}' is not the 'global::TestNamespace.IRepository' test double generated for this assembly. " +
                "If another assembly in this process also generated a double for 'global::TestNamespace.IRepository', only one " +
                "registration wins process-wide (Compono.GeneratedTestDoubleRegistry, first-registration-wins) " +
                "- this is a known v1 limitation, not a bug in your test."));
}

internal static class TestNamespace_IRepository_e3198068_DoubleVerification
{
    public static global::Compono.CallVerifier Seek(this global::TestNamespace_IRepository_e3198068_DoubleVerifier __self, global::Compono.Match<int> offset)
    {
        int __count;
        lock (__self.Instance.__Seek_lock)
        {
            __count = 0;
            foreach (var call in __self.Instance.__Seek_calls)
            {
                if (offset.Matches(call))
                    __count++;
            }
        }
        return new(__count, "global::TestNamespace.IRepository.Seek");
    }

    // Compatibility overload - same reasoning as DoubleConfiguration's zero-argument sibling above:
    // reuses the still-maintained, unfiltered ConfiguredCallCount rather than walking the call log,
    // reproducing v1/v2's exact argument-independent Verify() for this member.
    public static global::Compono.CallVerifier Seek(this global::TestNamespace_IRepository_e3198068_DoubleVerifier self) =>
        new(self.Instance.__Seek.ConfiguredCallCount, "global::TestNamespace.IRepository.Seek");

}

internal static class TestNamespace_IRepository_e3198068_ConfigureExtension
{
    public static global::TestNamespace_IRepository_e3198068_Double Configure(this global::TestNamespace.IRepository self) =>
        self as global::TestNamespace_IRepository_e3198068_Double
            ?? throw new global::System.InvalidOperationException(
                $"'{self.GetType()}' is not the 'global::TestNamespace.IRepository' test double generated for this assembly. " +
                "If another assembly in this process also generated a double for 'global::TestNamespace.IRepository', only one " +
                "registration wins process-wide (Compono.GeneratedTestDoubleRegistry, first-registration-wins) " +
                "- this is a known v1 limitation, not a bug in your test.");
}

file static class TestNamespace_IRepository_e3198068_DoubleRegistration
{
    [global::System.Runtime.CompilerServices.ModuleInitializer]
    internal static void Register() =>
        global::Compono.GeneratedTestDoubleRegistry.RegisterFactory<global::TestNamespace.IRepository>(
            () => new global::TestNamespace_IRepository_e3198068_Double());
}
