//HintName: TestNamespace.IRepository_e3198068.TestDouble.g.cs
// <auto-generated/>
#nullable enable

[global::System.CodeDom.Compiler.GeneratedCode("Compono.Generators", "REPLACED")]
internal sealed class TestNamespace_IRepository_e3198068_Double : global::TestNamespace.IRepository
{
    internal global::Compono.ReturnConfig<global::Compono.Unit> __Configure;
    internal global::Compono.ReturnConfig<string?> __GetName;

    void global::TestNamespace.IRepository.Configure(int mode)
    {
        __Configure.RecordCall();
        if (__Configure.HasConfiguredException)
            throw __Configure.ConfiguredException;
    }

    string? global::TestNamespace.IRepository.GetName()
    {
        __GetName.RecordCall();
        return __GetName.HasConfiguredException ? throw __GetName.ConfiguredException
            : __GetName.HasConfiguredValue ? __GetName.ConfiguredValue
            : default;
    }
}

internal static class TestNamespace_IRepository_e3198068_DoubleConfiguration
{
    public static global::Compono.ReturnConfigBuilder<global::Compono.Unit> Configure(this global::TestNamespace_IRepository_e3198068_Double self) =>
        new global::Compono.ReturnConfigBuilder<global::Compono.Unit>(ref self.__Configure);

    public static global::Compono.ReturnConfigBuilder<string?> GetName(this global::TestNamespace_IRepository_e3198068_Double self) =>
        new global::Compono.ReturnConfigBuilder<string?>(ref self.__GetName);

}

internal readonly struct TestNamespace_IRepository_e3198068_DoubleVerifier
{
    internal global::TestNamespace_IRepository_e3198068_Double Instance { get; }

    internal TestNamespace_IRepository_e3198068_DoubleVerifier(global::TestNamespace_IRepository_e3198068_Double instance) => Instance = instance;
}

internal static class TestNamespace_IRepository_e3198068_VerifyExtension
{
    public static global::TestNamespace_IRepository_e3198068_DoubleVerifier Verify(this global::TestNamespace.IRepository self) =>
        new(self as global::TestNamespace_IRepository_e3198068_Double
            ?? throw new global::System.InvalidOperationException(
                $"'{self.GetType()}' is not the 'global::TestNamespace.IRepository' test double generated for this assembly. " +
                "If another assembly in this process also generated a double for 'global::TestNamespace.IRepository', only one " +
                "registration wins process-wide (Compono.GeneratedTestDoubleRegistry, first-registration-wins) " +
                "- this is a known v1 limitation, not a bug in your test."));
}

internal static class TestNamespace_IRepository_e3198068_DoubleVerification
{
    public static global::Compono.CallVerifier Configure(this global::TestNamespace_IRepository_e3198068_DoubleVerifier self) =>
        new(self.Instance.__Configure.ConfiguredCallCount, "global::TestNamespace.IRepository.Configure");

    public static global::Compono.CallVerifier GetName(this global::TestNamespace_IRepository_e3198068_DoubleVerifier self) =>
        new(self.Instance.__GetName.ConfiguredCallCount, "global::TestNamespace.IRepository.GetName");

}

internal static class TestNamespace_IRepository_e3198068_ConfigureExtension
{
    public static global::TestNamespace_IRepository_e3198068_Double Configure(this global::TestNamespace.IRepository self) =>
        self as global::TestNamespace_IRepository_e3198068_Double
            ?? throw new global::System.InvalidOperationException(
                $"'{self.GetType()}' is not the 'global::TestNamespace.IRepository' test double generated for this assembly. " +
                "If another assembly in this process also generated a double for 'global::TestNamespace.IRepository', only one " +
                "registration wins process-wide (Compono.GeneratedTestDoubleRegistry, first-registration-wins) " +
                "- this is a known v1 limitation, not a bug in your test.");
}

file static class TestNamespace_IRepository_e3198068_DoubleRegistration
{
    [global::System.Runtime.CompilerServices.ModuleInitializer]
    internal static void Register() =>
        global::Compono.GeneratedTestDoubleRegistry.RegisterFactory<global::TestNamespace.IRepository>(
            () => new global::TestNamespace_IRepository_e3198068_Double());
}
