//HintName: TestNamespace.IRepository_e3198068.TestDouble.g.cs
// <auto-generated/>
#nullable enable

[global::System.CodeDom.Compiler.GeneratedCode("Compono.Generators", "REPLACED")]
internal sealed class TestNamespace_IRepository_e3198068_Double : global::TestNamespace.IRepository
{
    // ADR-0050: multi-entry response configuration - replaces the single
    // __FindNameAsync/__FindNameAsync_m_{param} shape with an ordered, append-only
    // entry list. Configure() appends; dispatch scans in reverse (last-matching-registration-wins).
    internal sealed class __FindNameAsync_Entry
    {
        internal global::Compono.Match<global::System.Guid>? Matcher_id;
        internal global::Compono.ReturnConfig<global::System.Threading.Tasks.Task<string?>> Config;
    }

    internal readonly global::System.Collections.Generic.List<__FindNameAsync_Entry> __FindNameAsync_entries = [];
    internal readonly global::System.Collections.Generic.List<global::System.Guid> __FindNameAsync_calls = [];
    internal readonly object __FindNameAsync_lock = new();
    // ADR-0050: multi-entry response configuration - replaces the single
    // __Save/__Save_m_{param} shape with an ordered, append-only
    // entry list. Configure() appends; dispatch scans in reverse (last-matching-registration-wins).
    internal sealed class __Save_Entry
    {
        internal global::Compono.Match<string?>? Matcher_name;
        internal global::Compono.ReturnConfig<global::Compono.Unit> Config;
    }

    internal readonly global::System.Collections.Generic.List<__Save_Entry> __Save_entries = [];
    internal readonly global::System.Collections.Generic.List<string?> __Save_calls = [];
    internal readonly object __Save_lock = new();

    global::System.Threading.Tasks.Task<string?> global::TestNamespace.IRepository.FindNameAsync(global::System.Guid id)
    {
        // ADR-0050: reverse-scan the ordered entry list - last matching registration wins.
        lock (__FindNameAsync_lock) { __FindNameAsync_calls.Add(id); }
        for (var __i = __FindNameAsync_entries.Count - 1; __i >= 0; __i--)
        {
            var __entry = __FindNameAsync_entries[__i];
            if ((__entry.Matcher_id is not { } __m_id || __m_id.Matches(id)))
            {
                if (__entry.Config.HasConfiguredException) throw __entry.Config.ConfiguredException;
                if (__entry.Config.HasConfiguredValue) return __entry.Config.ConfiguredValue;
                break;
            }
        }
        return global::System.Threading.Tasks.Task.FromResult<string?>(default);
    }

    void global::TestNamespace.IRepository.Save(string? name)
    {
        // ADR-0050: reverse-scan the ordered entry list - last matching registration wins.
        lock (__Save_lock) { __Save_calls.Add(name); }
        for (var __i = __Save_entries.Count - 1; __i >= 0; __i--)
        {
            var __entry = __Save_entries[__i];
            if ((__entry.Matcher_name is not { } __m_name || __m_name.Matches(name)))
            {
                if (__entry.Config.HasConfiguredException) throw __entry.Config.ConfiguredException;
                break;
            }
        }
    }
}

internal static class TestNamespace_IRepository_e3198068_DoubleConfiguration
{
    public static global::Compono.ReturnConfigBuilder<global::System.Threading.Tasks.Task<string?>> FindNameAsync(this global::TestNamespace_IRepository_e3198068_Double __self, global::Compono.Match<global::System.Guid> id)
    {
        // ADR-0050: appends a new entry - see the closed-instantiation Configure()
        // above for the reallocation-hazard proof, identical reasoning applies here.
        var __entry = new global::TestNamespace_IRepository_e3198068_Double.__FindNameAsync_Entry();
        __entry.Matcher_id = id;
        __self.__FindNameAsync_entries.Add(__entry);
        return new global::Compono.ReturnConfigBuilder<global::System.Threading.Tasks.Task<string?>>(ref __entry.Config);
    }

    // Compatibility overload (Codex review, PLAN-0048): v1/v2 gave every non-overloaded member a
    // zero-argument Configure(), regardless of real arity. ADR-0050: under multi-entry,
    // this no longer needs to null out prior matchers to reproduce "last wins" - it just appends its
    // own new, all-null-matcher (always-matching) entry; being the most-recently-appended entry, the
    // reverse scan finds it before any earlier, more specific entry, exactly reproducing v1/v2's
    // argument-independent override behavior without mutating any earlier entry's state at all.
    public static global::Compono.ReturnConfigBuilder<global::System.Threading.Tasks.Task<string?>> FindNameAsync(this global::TestNamespace_IRepository_e3198068_Double self)
    {
        var __entry = new global::TestNamespace_IRepository_e3198068_Double.__FindNameAsync_Entry();
        self.__FindNameAsync_entries.Add(__entry);
        return new global::Compono.ReturnConfigBuilder<global::System.Threading.Tasks.Task<string?>>(ref __entry.Config);
    }

    public static global::Compono.ReturnConfigBuilder<global::Compono.Unit> Save(this global::TestNamespace_IRepository_e3198068_Double __self, global::Compono.Match<string?> name)
    {
        // ADR-0050: appends a new entry - see the closed-instantiation Configure()
        // above for the reallocation-hazard proof, identical reasoning applies here.
        var __entry = new global::TestNamespace_IRepository_e3198068_Double.__Save_Entry();
        __entry.Matcher_name = name;
        __self.__Save_entries.Add(__entry);
        return new global::Compono.ReturnConfigBuilder<global::Compono.Unit>(ref __entry.Config);
    }

    // Compatibility overload (Codex review, PLAN-0048): v1/v2 gave every non-overloaded member a
    // zero-argument Configure(), regardless of real arity. ADR-0050: under multi-entry,
    // this no longer needs to null out prior matchers to reproduce "last wins" - it just appends its
    // own new, all-null-matcher (always-matching) entry; being the most-recently-appended entry, the
    // reverse scan finds it before any earlier, more specific entry, exactly reproducing v1/v2's
    // argument-independent override behavior without mutating any earlier entry's state at all.
    public static global::Compono.ReturnConfigBuilder<global::Compono.Unit> Save(this global::TestNamespace_IRepository_e3198068_Double self)
    {
        var __entry = new global::TestNamespace_IRepository_e3198068_Double.__Save_Entry();
        self.__Save_entries.Add(__entry);
        return new global::Compono.ReturnConfigBuilder<global::Compono.Unit>(ref __entry.Config);
    }

}

internal readonly struct TestNamespace_IRepository_e3198068_DoubleVerifier
{
    internal global::TestNamespace_IRepository_e3198068_Double Instance { get; }

    internal TestNamespace_IRepository_e3198068_DoubleVerifier(global::TestNamespace_IRepository_e3198068_Double instance) => Instance = instance;
}

internal static class TestNamespace_IRepository_e3198068_VerifyExtension
{
    public static global::TestNamespace_IRepository_e3198068_DoubleVerifier Verify(this global::TestNamespace.IRepository self) =>
        new(self as global::TestNamespace_IRepository_e3198068_Double
            ?? throw new global::System.InvalidOperationException(
                $"'{self.GetType()}' is not the 'global::TestNamespace.IRepository' test double generated for this assembly. " +
                "If another assembly in this process also generated a double for 'global::TestNamespace.IRepository', only one " +
                "registration wins process-wide (Compono.GeneratedTestDoubleRegistry, first-registration-wins) " +
                "- this is a known v1 limitation, not a bug in your test."));
}

internal static class TestNamespace_IRepository_e3198068_DoubleVerification
{
    public static global::Compono.CallVerifier FindNameAsync(this global::TestNamespace_IRepository_e3198068_DoubleVerifier __self, global::Compono.Match<global::System.Guid> id)
    {
        int __count;
        lock (__self.Instance.__FindNameAsync_lock)
        {
            __count = 0;
            foreach (var call in __self.Instance.__FindNameAsync_calls)
            {
                if (id.Matches(call))
                    __count++;
            }
        }
        return new(__count, "global::TestNamespace.IRepository.FindNameAsync");
    }

    // Compatibility overload - ADR-0050: the removed single-slot field no longer
    // tracks a call count at all (RecordCall() is gone from dispatch for this shape) - the call
    // log's own Count, under its existing lock, is exactly the same number and is already
    // maintained regardless of how many response entries exist.
    public static global::Compono.CallVerifier FindNameAsync(this global::TestNamespace_IRepository_e3198068_DoubleVerifier self)
    {
        int __count;
        lock (self.Instance.__FindNameAsync_lock) { __count = self.Instance.__FindNameAsync_calls.Count; }
        return new(__count, "global::TestNamespace.IRepository.FindNameAsync");
    }

    public static global::Compono.CallVerifier Save(this global::TestNamespace_IRepository_e3198068_DoubleVerifier __self, global::Compono.Match<string?> name)
    {
        int __count;
        lock (__self.Instance.__Save_lock)
        {
            __count = 0;
            foreach (var call in __self.Instance.__Save_calls)
            {
                if (name.Matches(call))
                    __count++;
            }
        }
        return new(__count, "global::TestNamespace.IRepository.Save");
    }

    // Compatibility overload - ADR-0050: the removed single-slot field no longer
    // tracks a call count at all (RecordCall() is gone from dispatch for this shape) - the call
    // log's own Count, under its existing lock, is exactly the same number and is already
    // maintained regardless of how many response entries exist.
    public static global::Compono.CallVerifier Save(this global::TestNamespace_IRepository_e3198068_DoubleVerifier self)
    {
        int __count;
        lock (self.Instance.__Save_lock) { __count = self.Instance.__Save_calls.Count; }
        return new(__count, "global::TestNamespace.IRepository.Save");
    }

}

internal static class TestNamespace_IRepository_e3198068_ConfigureExtension
{
    public static global::TestNamespace_IRepository_e3198068_Double Configure(this global::TestNamespace.IRepository self) =>
        self as global::TestNamespace_IRepository_e3198068_Double
            ?? throw new global::System.InvalidOperationException(
                $"'{self.GetType()}' is not the 'global::TestNamespace.IRepository' test double generated for this assembly. " +
                "If another assembly in this process also generated a double for 'global::TestNamespace.IRepository', only one " +
                "registration wins process-wide (Compono.GeneratedTestDoubleRegistry, first-registration-wins) " +
                "- this is a known v1 limitation, not a bug in your test.");
}

file static class TestNamespace_IRepository_e3198068_DoubleRegistration
{
    [global::System.Runtime.CompilerServices.ModuleInitializer]
    internal static void Register() =>
        global::Compono.GeneratedTestDoubleRegistry.RegisterFactory<global::TestNamespace.IRepository>(
            () => new global::TestNamespace_IRepository_e3198068_Double());
}
