//HintName: TestNamespace.IContextManager_d05603ce.TestDouble.g.cs
// <auto-generated/>
#nullable enable

// PLAN-0063/ADR-0060: ClearCalls() reaches every ADR-0049 closed-instantiation-eligible member's
// per-closed-T bucket entries generically, with no static knowledge of which closed T's exist at
// runtime - this non-generic interface (implemented by every generated
// TestNamespace_IContextManager_d05603ce_*State<T> class below) is what makes that possible without reflection.
internal interface TestNamespace_IContextManager_d05603ce_IClearableCallState
{
    void ClearObservedCalls();
}

[global::System.CodeDom.Compiler.GeneratedCode("Compono.Generators", "REPLACED")]
internal sealed class TestNamespace_IContextManager_d05603ce_Double : global::TestNamespace.IContextManager
{
    internal delegate global::System.Threading.Tasks.Task<T?> __GetDataAsync_97bed815_Callback<T>(string id) where T : class;

    internal readonly ref struct __GetDataAsync_97bed815_Builder<T> where T : class
    {
        private readonly ref global::Compono.ReturnConfig<global::System.Threading.Tasks.Task<T?>> _config;
        private readonly ref __GetDataAsync_97bed815_Callback<T>? _callback;

        internal __GetDataAsync_97bed815_Builder(ref global::Compono.ReturnConfig<global::System.Threading.Tasks.Task<T?>> config, ref __GetDataAsync_97bed815_Callback<T>? callback)
        {
            _config = ref config;
            _callback = ref callback;
        }

        public void Returns(global::System.Threading.Tasks.Task<T?> value)
        {
            _callback = null;
            new global::Compono.ReturnConfigBuilder<global::System.Threading.Tasks.Task<T?>>(ref _config).Returns(value);
        }

        public void Throws(global::System.Exception exception)
        {
            _callback = null;
            new global::Compono.ReturnConfigBuilder<global::System.Threading.Tasks.Task<T?>>(ref _config).Throws(exception);
        }

        public void ReturnsSequence(params global::Compono.SequenceOutcome<global::System.Threading.Tasks.Task<T?>>[] outcomes)
        {
            _callback = null;
            new global::Compono.ReturnConfigBuilder<global::System.Threading.Tasks.Task<T?>>(ref _config).ReturnsSequence(outcomes);
        }

        public void ReturnsCallback(__GetDataAsync_97bed815_Callback<T> callback)
        {
            global::System.ArgumentNullException.ThrowIfNull(callback);
            _config.ClearConfiguredResponse();
            _callback = callback;
        }
    }
    internal delegate global::System.Threading.Tasks.Task<T?> __GetDataAsync_1aae9cd0_Callback<T>(string id, int version) where T : class;

    internal readonly ref struct __GetDataAsync_1aae9cd0_Builder<T> where T : class
    {
        private readonly ref global::Compono.ReturnConfig<global::System.Threading.Tasks.Task<T?>> _config;
        private readonly ref __GetDataAsync_1aae9cd0_Callback<T>? _callback;

        internal __GetDataAsync_1aae9cd0_Builder(ref global::Compono.ReturnConfig<global::System.Threading.Tasks.Task<T?>> config, ref __GetDataAsync_1aae9cd0_Callback<T>? callback)
        {
            _config = ref config;
            _callback = ref callback;
        }

        public void Returns(global::System.Threading.Tasks.Task<T?> value)
        {
            _callback = null;
            new global::Compono.ReturnConfigBuilder<global::System.Threading.Tasks.Task<T?>>(ref _config).Returns(value);
        }

        public void Throws(global::System.Exception exception)
        {
            _callback = null;
            new global::Compono.ReturnConfigBuilder<global::System.Threading.Tasks.Task<T?>>(ref _config).Throws(exception);
        }

        public void ReturnsSequence(params global::Compono.SequenceOutcome<global::System.Threading.Tasks.Task<T?>>[] outcomes)
        {
            _callback = null;
            new global::Compono.ReturnConfigBuilder<global::System.Threading.Tasks.Task<T?>>(ref _config).ReturnsSequence(outcomes);
        }

        public void ReturnsCallback(__GetDataAsync_1aae9cd0_Callback<T> callback)
        {
            global::System.ArgumentNullException.ThrowIfNull(callback);
            _config.ClearConfiguredResponse();
            _callback = callback;
        }
    }
    internal sealed class __GetDataAsync_97bed815_State<T> : TestNamespace_IContextManager_d05603ce_IClearableCallState where T : class
    {
        internal global::Compono.ReturnConfig<global::System.Threading.Tasks.Task<T?>> Config;
        internal __GetDataAsync_97bed815_Callback<T>? Callback;

        // PLAN-0063/ADR-0060: see the matched-parameters branch above for the full rationale - this
        // shape has no argument history to clear, only the scalar call count.
        public void ClearObservedCalls() => this.Config.ClearObservedCalls();
    }

    internal readonly global::System.Collections.Generic.Dictionary<global::System.Type, object> __GetDataAsync_97bed815_buckets = new();

    internal __GetDataAsync_97bed815_State<T> __GetDataAsync_97bed815_Bucket<T>() where T : class
    {
        lock (__GetDataAsync_97bed815_buckets)
        {
            if (!__GetDataAsync_97bed815_buckets.TryGetValue(typeof(T), out var __boxed))
            {
                __boxed = new __GetDataAsync_97bed815_State<T>();
                __GetDataAsync_97bed815_buckets[typeof(T)] = __boxed;
            }

            return (__GetDataAsync_97bed815_State<T>)__boxed;
        }
    }
    internal sealed class __GetDataAsync_1aae9cd0_State<T> : TestNamespace_IContextManager_d05603ce_IClearableCallState where T : class
    {
        internal global::Compono.ReturnConfig<global::System.Threading.Tasks.Task<T?>> Config;
        internal __GetDataAsync_1aae9cd0_Callback<T>? Callback;

        // PLAN-0063/ADR-0060: see the matched-parameters branch above for the full rationale - this
        // shape has no argument history to clear, only the scalar call count.
        public void ClearObservedCalls() => this.Config.ClearObservedCalls();
    }

    internal readonly global::System.Collections.Generic.Dictionary<global::System.Type, object> __GetDataAsync_1aae9cd0_buckets = new();

    internal __GetDataAsync_1aae9cd0_State<T> __GetDataAsync_1aae9cd0_Bucket<T>() where T : class
    {
        lock (__GetDataAsync_1aae9cd0_buckets)
        {
            if (!__GetDataAsync_1aae9cd0_buckets.TryGetValue(typeof(T), out var __boxed))
            {
                __boxed = new __GetDataAsync_1aae9cd0_State<T>();
                __GetDataAsync_1aae9cd0_buckets[typeof(T)] = __boxed;
            }

            return (__GetDataAsync_1aae9cd0_State<T>)__boxed;
        }
    }

#pragma warning disable CS8603, CS8616, CS8619
    global::System.Threading.Tasks.Task<T> global::TestNamespace.IContextManager.GetDataAsync<T>(string id)
    {
        var __bucket = __GetDataAsync_97bed815_Bucket<T>();
        __bucket.Config.RecordCall();
        return __bucket.Callback is { } callback ? callback(id)
            : __bucket.Config.HasConfiguredSequence ? __bucket.Config.NextSequenceOutcome()
            : __bucket.Config.HasConfiguredException ? throw __bucket.Config.ConfiguredException
            : __bucket.Config.HasConfiguredValue ? __bucket.Config.ConfiguredValue
            : global::System.Threading.Tasks.Task.FromResult<T?>(default);
    }
#pragma warning restore CS8603, CS8616, CS8619

#pragma warning disable CS8603, CS8616, CS8619
    global::System.Threading.Tasks.Task<T> global::TestNamespace.IContextManager.GetDataAsync<T>(string id, int version)
    {
        var __bucket = __GetDataAsync_1aae9cd0_Bucket<T>();
        __bucket.Config.RecordCall();
        return __bucket.Callback is { } callback ? callback(id, version)
            : __bucket.Config.HasConfiguredSequence ? __bucket.Config.NextSequenceOutcome()
            : __bucket.Config.HasConfiguredException ? throw __bucket.Config.ConfiguredException
            : __bucket.Config.HasConfiguredValue ? __bucket.Config.ConfiguredValue
            : global::System.Threading.Tasks.Task.FromResult<T?>(default);
    }
#pragma warning restore CS8603, CS8616, CS8619
}

internal static class TestNamespace_IContextManager_d05603ce_DoubleConfiguration
{
    public static global::TestNamespace_IContextManager_d05603ce_Double.__GetDataAsync_97bed815_Builder<T> GetDataAsync<T>(this global::TestNamespace_IContextManager_d05603ce_Double __self, string id) where T : class
    {
        var __bucket = __self.__GetDataAsync_97bed815_Bucket<T>();
        return new global::TestNamespace_IContextManager_d05603ce_Double.__GetDataAsync_97bed815_Builder<T>(ref __bucket.Config, ref __bucket.Callback);
    }

    public static global::TestNamespace_IContextManager_d05603ce_Double.__GetDataAsync_1aae9cd0_Builder<T> GetDataAsync<T>(this global::TestNamespace_IContextManager_d05603ce_Double __self, string id, int version) where T : class
    {
        var __bucket = __self.__GetDataAsync_1aae9cd0_Bucket<T>();
        return new global::TestNamespace_IContextManager_d05603ce_Double.__GetDataAsync_1aae9cd0_Builder<T>(ref __bucket.Config, ref __bucket.Callback);
    }

}

internal readonly struct TestNamespace_IContextManager_d05603ce_DoubleVerifier
{
    internal global::TestNamespace_IContextManager_d05603ce_Double Instance { get; }

    internal TestNamespace_IContextManager_d05603ce_DoubleVerifier(global::TestNamespace_IContextManager_d05603ce_Double instance) => Instance = instance;
}

internal static class TestNamespace_IContextManager_d05603ce_VerifyExtension
{
    public static global::TestNamespace_IContextManager_d05603ce_DoubleVerifier Verify(this global::TestNamespace.IContextManager self) =>
        new(self as global::TestNamespace_IContextManager_d05603ce_Double
            ?? throw new global::System.InvalidOperationException(
                $"'{self.GetType()}' is not the 'global::TestNamespace.IContextManager' test double generated for this assembly. " +
                "If another assembly in this process also generated a double for 'global::TestNamespace.IContextManager', only one " +
                "registration wins process-wide (Compono.GeneratedTestDoubleRegistry, first-registration-wins) " +
                "- this is a known v1 limitation, not a bug in your test."));
}

internal static class TestNamespace_IContextManager_d05603ce_DoubleVerification
{
    public static global::Compono.CallVerifier GetDataAsync<T>(this global::TestNamespace_IContextManager_d05603ce_DoubleVerifier __self, string id) where T : class =>
        new(__self.Instance.__GetDataAsync_97bed815_Bucket<T>().Config.ConfiguredCallCount, "global::TestNamespace.IContextManager.GetDataAsync");

    public static global::Compono.CallVerifier GetDataAsync<T>(this global::TestNamespace_IContextManager_d05603ce_DoubleVerifier __self, string id, int version) where T : class =>
        new(__self.Instance.__GetDataAsync_1aae9cd0_Bucket<T>().Config.ConfiguredCallCount, "global::TestNamespace.IContextManager.GetDataAsync");

}

// PLAN-0063/ADR-0060: ReceivedCalls() - retrospective, snapshot-based call inspection, scoped to
// exactly the ADR-0048 eligible-member set (member.is_eligible_for_matching), unexpanded. A
// distinct third bridge from Configure()/Verify() - never attaches captured data to CallVerifier.
internal readonly struct TestNamespace_IContextManager_d05603ce_DoubleReceivedCalls
{
    internal global::TestNamespace_IContextManager_d05603ce_Double Instance { get; }

    internal TestNamespace_IContextManager_d05603ce_DoubleReceivedCalls(global::TestNamespace_IContextManager_d05603ce_Double instance) => Instance = instance;
}

internal static class TestNamespace_IContextManager_d05603ce_ReceivedCallsExtension
{
    public static global::TestNamespace_IContextManager_d05603ce_DoubleReceivedCalls ReceivedCalls(this global::TestNamespace.IContextManager self) =>
        new(self as global::TestNamespace_IContextManager_d05603ce_Double
            ?? throw new global::System.InvalidOperationException(
                $"'{self.GetType()}' is not the 'global::TestNamespace.IContextManager' test double generated for this assembly. " +
                "If another assembly in this process also generated a double for 'global::TestNamespace.IContextManager', only one " +
                "registration wins process-wide (Compono.GeneratedTestDoubleRegistry, first-registration-wins) " +
                "- this is a known v1 limitation, not a bug in your test."));
}

internal static class TestNamespace_IContextManager_d05603ce_DoubleReceivedCallsAccess
{
}

// PLAN-0063/ADR-0060: ClearCalls() - a direct, whole-double operation clearing every member's
// observation state (scalar call counts + ADR-0048 captured argument histories) while preserving
// all configured behavior (Returns/Throws/ReturnsCallback/ReturnsSequence - including in-progress
// SequenceOrdinal, which does not rewind - argument-matcher/multi-entry configuration, and generic
// closed-instantiation configuration). No per-member ClearCalls(), no global whole-double lock -
// each member's own existing synchronization primitive is used independently, per member.
internal static class TestNamespace_IContextManager_d05603ce_ClearCallsExtension
{
    public static void ClearCalls(this global::TestNamespace.IContextManager self)
    {
        var __double = self as global::TestNamespace_IContextManager_d05603ce_Double
            ?? throw new global::System.InvalidOperationException(
                $"'{self.GetType()}' is not the 'global::TestNamespace.IContextManager' test double generated for this assembly. " +
                "If another assembly in this process also generated a double for 'global::TestNamespace.IContextManager', only one " +
                "registration wins process-wide (Compono.GeneratedTestDoubleRegistry, first-registration-wins) " +
                "- this is a known v1 limitation, not a bug in your test.");

        lock (__double.__GetDataAsync_97bed815_buckets)
        {
            foreach (var __bucketEntry in __double.__GetDataAsync_97bed815_buckets.Values)
                ((TestNamespace_IContextManager_d05603ce_IClearableCallState)__bucketEntry).ClearObservedCalls();
        }
        lock (__double.__GetDataAsync_1aae9cd0_buckets)
        {
            foreach (var __bucketEntry in __double.__GetDataAsync_1aae9cd0_buckets.Values)
                ((TestNamespace_IContextManager_d05603ce_IClearableCallState)__bucketEntry).ClearObservedCalls();
        }
    }
}

internal static class TestNamespace_IContextManager_d05603ce_ConfigureExtension
{
    public static global::TestNamespace_IContextManager_d05603ce_Double Configure(this global::TestNamespace.IContextManager self) =>
        self as global::TestNamespace_IContextManager_d05603ce_Double
            ?? throw new global::System.InvalidOperationException(
                $"'{self.GetType()}' is not the 'global::TestNamespace.IContextManager' test double generated for this assembly. " +
                "If another assembly in this process also generated a double for 'global::TestNamespace.IContextManager', only one " +
                "registration wins process-wide (Compono.GeneratedTestDoubleRegistry, first-registration-wins) " +
                "- this is a known v1 limitation, not a bug in your test.");
}

file static class TestNamespace_IContextManager_d05603ce_DoubleRegistration
{
    [global::System.Runtime.CompilerServices.ModuleInitializer]
    internal static void Register() =>
        global::Compono.GeneratedTestDoubleRegistry.RegisterFactory<global::TestNamespace.IContextManager>(
            () => new global::TestNamespace_IContextManager_d05603ce_Double());
}
