//HintName: TestNamespace.IRepository_e3198068.TestDouble.g.cs
// <auto-generated/>
#nullable enable

[global::System.CodeDom.Compiler.GeneratedCode("Compono.Generators", "REPLACED")]
internal sealed class TestNamespace_IRepository_e3198068_Double : global::TestNamespace.IRepository
{
    internal global::Compono.ReturnConfig<string?> __GetName;
    // ADR-0050: multi-entry response configuration - replaces the single
    // __Configure/__Configure_m_{param} shape with an ordered, append-only
    // entry list. Configure() appends; dispatch scans in reverse (last-matching-registration-wins).
    internal sealed class __Configure_Entry
    {
        internal global::Compono.Match<int>? Matcher_mode;
        internal global::Compono.ReturnConfig<global::Compono.Unit> Config;
    }

    internal readonly global::System.Collections.Generic.List<__Configure_Entry> __Configure_entries = [];
    internal readonly global::System.Collections.Generic.List<int> __Configure_calls = [];
    internal readonly object __Configure_lock = new();

    void global::TestNamespace.IRepository.Configure(int mode)
    {
        // ADR-0050: reverse-scan the ordered entry list - last matching registration wins. Both
        // the call-log append and the full scan stay under the SAME lock acquisition as
        // Configure()'s Add() (Codex review, PR #108 round 5) - the prior split-lock shape (a
        // short lock around _calls.Add() only, then an unlocked scan) let a concurrent Configure()
        // call mutate List<T>'s backing array while dispatch was still iterating it.
        lock (__Configure_lock)
        {
            __Configure_calls.Add(mode);
            for (var __i = __Configure_entries.Count - 1; __i >= 0; __i--)
            {
                var __entry = __Configure_entries[__i];
                if ((__entry.Matcher_mode is not { } __m_mode || __m_mode.Matches(mode)))
                {
                    // ADR-0050: no `break` here (Codex review, PR #108 round 6) - see the
                    // value-returning branch below for the full reasoning; a matched entry with
                    // neither a configured exception nor a configured value must not shadow an
                    // older, configured matching entry. Void members still have a genuine
                    // "configured" state distinct from "incomplete" - `HasConfiguredValue` is set
                    // by `.Returns(default)` (a `global::Compono.Unit`) even though there's nothing
                    // to return - so it must
                    // stop the scan (`return;`) exactly like the value-returning branch below, not
                    // be treated as equivalent to an unconfigured/incomplete entry (Codex review,
                    // PR #108 round 7).
                    if (__entry.Config.HasConfiguredException) throw __entry.Config.ConfiguredException;
                    if (__entry.Config.HasConfiguredValue) return;
                }
            }
        }
    }

    string? global::TestNamespace.IRepository.GetName()
    {
        __GetName.RecordCall();
        return __GetName.HasConfiguredException ? throw __GetName.ConfiguredException
            : __GetName.HasConfiguredValue ? __GetName.ConfiguredValue
            : default;
    }
}

internal static class TestNamespace_IRepository_e3198068_DoubleConfiguration
{
    public static global::Compono.ReturnConfigBuilder<global::Compono.Unit> Configure(this global::TestNamespace_IRepository_e3198068_Double __self, global::Compono.Match<int> mode)
    {
        // ADR-0050: appends a new entry - see the closed-instantiation Configure()
        // above for the reallocation-hazard proof, identical reasoning applies here. The Add()
        // itself is under the same member lock dispatch scans under (Codex review, PR #108
        // round 5).
        var __entry = new global::TestNamespace_IRepository_e3198068_Double.__Configure_Entry();
        __entry.Matcher_mode = mode;
        lock (__self.__Configure_lock) { __self.__Configure_entries.Add(__entry); }
        return new global::Compono.ReturnConfigBuilder<global::Compono.Unit>(ref __entry.Config);
    }

    // Compatibility overload (Codex review, PLAN-0048): v1/v2 gave every non-overloaded member a
    // zero-argument Configure(), regardless of real arity. ADR-0050: under multi-entry,
    // this no longer needs to null out prior matchers to reproduce "last wins" - it just appends its
    // own new, all-null-matcher (always-matching) entry; being the most-recently-appended entry, the
    // reverse scan finds it before any earlier, more specific entry, exactly reproducing v1/v2's
    // argument-independent override behavior without mutating any earlier entry's state at all.
    public static global::Compono.ReturnConfigBuilder<global::Compono.Unit> Configure(this global::TestNamespace_IRepository_e3198068_Double self)
    {
        var __entry = new global::TestNamespace_IRepository_e3198068_Double.__Configure_Entry();
        lock (self.__Configure_lock) { self.__Configure_entries.Add(__entry); }
        return new global::Compono.ReturnConfigBuilder<global::Compono.Unit>(ref __entry.Config);
    }

    public static global::Compono.ReturnConfigBuilder<string?> GetName(this global::TestNamespace_IRepository_e3198068_Double self) =>
        new global::Compono.ReturnConfigBuilder<string?>(ref self.__GetName);

}

internal readonly struct TestNamespace_IRepository_e3198068_DoubleVerifier
{
    internal global::TestNamespace_IRepository_e3198068_Double Instance { get; }

    internal TestNamespace_IRepository_e3198068_DoubleVerifier(global::TestNamespace_IRepository_e3198068_Double instance) => Instance = instance;
}

internal static class TestNamespace_IRepository_e3198068_VerifyExtension
{
    public static global::TestNamespace_IRepository_e3198068_DoubleVerifier Verify(this global::TestNamespace.IRepository self) =>
        new(self as global::TestNamespace_IRepository_e3198068_Double
            ?? throw new global::System.InvalidOperationException(
                $"'{self.GetType()}' is not the 'global::TestNamespace.IRepository' test double generated for this assembly. " +
                "If another assembly in this process also generated a double for 'global::TestNamespace.IRepository', only one " +
                "registration wins process-wide (Compono.GeneratedTestDoubleRegistry, first-registration-wins) " +
                "- this is a known v1 limitation, not a bug in your test."));
}

internal static class TestNamespace_IRepository_e3198068_DoubleVerification
{
    public static global::Compono.CallVerifier Configure(this global::TestNamespace_IRepository_e3198068_DoubleVerifier __self, global::Compono.Match<int> mode)
    {
        int __count;
        lock (__self.Instance.__Configure_lock)
        {
            __count = 0;
            foreach (var call in __self.Instance.__Configure_calls)
            {
                if (mode.Matches(call))
                    __count++;
            }
        }
        return new(__count, "global::TestNamespace.IRepository.Configure");
    }

    // Compatibility overload - ADR-0050: the removed single-slot field no longer
    // tracks a call count at all (RecordCall() is gone from dispatch for this shape) - the call
    // log's own Count, under its existing lock, is exactly the same number and is already
    // maintained regardless of how many response entries exist.
    public static global::Compono.CallVerifier Configure(this global::TestNamespace_IRepository_e3198068_DoubleVerifier self)
    {
        int __count;
        lock (self.Instance.__Configure_lock) { __count = self.Instance.__Configure_calls.Count; }
        return new(__count, "global::TestNamespace.IRepository.Configure");
    }

    public static global::Compono.CallVerifier GetName(this global::TestNamespace_IRepository_e3198068_DoubleVerifier self) =>
        new(self.Instance.__GetName.ConfiguredCallCount, "global::TestNamespace.IRepository.GetName");

}

internal static class TestNamespace_IRepository_e3198068_ConfigureExtension
{
    public static global::TestNamespace_IRepository_e3198068_Double Configure(this global::TestNamespace.IRepository self) =>
        self as global::TestNamespace_IRepository_e3198068_Double
            ?? throw new global::System.InvalidOperationException(
                $"'{self.GetType()}' is not the 'global::TestNamespace.IRepository' test double generated for this assembly. " +
                "If another assembly in this process also generated a double for 'global::TestNamespace.IRepository', only one " +
                "registration wins process-wide (Compono.GeneratedTestDoubleRegistry, first-registration-wins) " +
                "- this is a known v1 limitation, not a bug in your test.");
}

file static class TestNamespace_IRepository_e3198068_DoubleRegistration
{
    [global::System.Runtime.CompilerServices.ModuleInitializer]
    internal static void Register() =>
        global::Compono.GeneratedTestDoubleRegistry.RegisterFactory<global::TestNamespace.IRepository>(
            () => new global::TestNamespace_IRepository_e3198068_Double());
}
