//HintName: TestNamespace.IRepository_e3198068.TestDouble.g.cs
// <auto-generated/>
#nullable enable

[global::System.CodeDom.Compiler.GeneratedCode("Compono.Generators", "REPLACED")]
internal sealed class TestNamespace_IRepository_e3198068_Double : global::TestNamespace.IRepository
{
    internal delegate int __Value_b9dfaa09_Callback(int offset);

    internal readonly ref struct __Value_b9dfaa09_Builder
    {
        private readonly ref global::Compono.ReturnConfig<int> _config;
        private readonly ref __Value_b9dfaa09_Callback? _callback;

        internal __Value_b9dfaa09_Builder(ref global::Compono.ReturnConfig<int> config, ref __Value_b9dfaa09_Callback? callback)
        {
            _config = ref config;
            _callback = ref callback;
        }

        public void Returns(int value)
        {
            _callback = null;
            new global::Compono.ReturnConfigBuilder<int>(ref _config).Returns(value);
        }

        public void Throws(global::System.Exception exception)
        {
            _callback = null;
            new global::Compono.ReturnConfigBuilder<int>(ref _config).Throws(exception);
        }

        public void ReturnsSequence(params global::Compono.SequenceOutcome<int>[] outcomes)
        {
            _callback = null;
            new global::Compono.ReturnConfigBuilder<int>(ref _config).ReturnsSequence(outcomes);
        }

        public void ReturnsCallback(__Value_b9dfaa09_Callback callback)
        {
            global::System.ArgumentNullException.ThrowIfNull(callback);
            _config.ClearConfiguredResponse();
            _callback = callback;
        }
    }
    // ADR-0050: multi-entry response configuration - replaces the single
    // __Value_b9dfaa09/__Value_b9dfaa09_m_{param} shape with an ordered, append-only
    // entry list. Configure() appends; dispatch scans in reverse (last-matching-registration-wins).
    internal sealed class __Value_b9dfaa09_Entry
    {
        internal global::Compono.Match<int>? Matcher_offset;
        internal global::Compono.ReturnConfig<int> Config;
        internal __Value_b9dfaa09_Callback? Callback;
    }

    internal readonly global::System.Collections.Generic.List<__Value_b9dfaa09_Entry> __Value_b9dfaa09_entries = [];
    internal readonly global::System.Collections.Generic.List<int> __Value_b9dfaa09_calls = [];
    internal readonly object __Value_b9dfaa09_lock = new();

    int global::TestNamespace.IBaseA.Value
    {
        get => default;
    }

    int global::TestNamespace.IBaseB.Value()
    {
        return default;
    }

    int global::TestNamespace.IBaseB.Value(int offset)
    {
        __Value_b9dfaa09_Callback? __callback = null;
        // ADR-0050: reverse-scan the ordered entry list - last matching registration wins. Both
        // the call-log append and the full scan stay under the SAME lock acquisition as
        // Configure()'s Add() (Codex review, PR #108 round 5) - the prior split-lock shape (a
        // short lock around _calls.Add() only, then an unlocked scan) let a concurrent Configure()
        // call mutate List<T>'s backing array while dispatch was still iterating it. `return`/
        // `throw` inside a C# `lock` block still releases the lock (try/finally under the hood).
        lock (__Value_b9dfaa09_lock)
        {
            __Value_b9dfaa09_calls.Add(offset);
            for (var __i = __Value_b9dfaa09_entries.Count - 1; __i >= 0; __i--)
            {
                var __entry = __Value_b9dfaa09_entries[__i];
                if ((__entry.Matcher_offset is not { } __m_offset || __m_offset.Matches(offset)))
                {
                    if (__entry.Callback is { } configuredCallback)
                    {
                        __callback = configuredCallback;
                        break;
                    }
                    // ADR-0050: no `break` here (Codex review, PR #108 round 6) - if this entry
                    // matched but has neither a configured exception nor a configured value (e.g.
                    // its builder is still being set up when this call arrives), it must NOT shadow
                    // an older, fully-configured matching entry; the scan continues to the next
                    // (older) entry instead of falling through to the default/required-config rule.
                    // ADR-0054: a configured sequence is checked first - Returns/Throws/ReturnsSequence
                    // are mutually exclusive on one Config, so order between this and the two checks
                    // below doesn't change behavior, but leads with the newest-added capability.
                    if (__entry.Config.HasConfiguredSequence) return __entry.Config.NextSequenceOutcome();
                    if (__entry.Config.HasConfiguredException) throw __entry.Config.ConfiguredException;
                    if (__entry.Config.HasConfiguredValue) return __entry.Config.ConfiguredValue;
                }
            }
        }
        if (__callback is { } callback)
            return callback(offset);
        return default;
    }
}

internal static class TestNamespace_IRepository_e3198068_DoubleConfiguration
{
    // ADR-0044 Amendment 21 / PLAN-0054 Phase 2: discriminator-only Configure() - real parameter
    // types, unchanged signature/call sites - but now appends an always-matching entry to the
    // shared per-overload entries list instead of returning a builder over a removed single field.
    public static global::TestNamespace_IRepository_e3198068_Double.__Value_b9dfaa09_Builder Value(this global::TestNamespace_IRepository_e3198068_Double __self, int offset)
    {
        var __entry = new global::TestNamespace_IRepository_e3198068_Double.__Value_b9dfaa09_Entry();
        lock (__self.__Value_b9dfaa09_lock) { __self.__Value_b9dfaa09_entries.Add(__entry); }
        return new global::TestNamespace_IRepository_e3198068_Double.__Value_b9dfaa09_Builder(ref __entry.Config, ref __entry.Callback);
    }

    // New matching-specific member name (ADR-0044 Amendment 21) - real Match<T> parameters,
    // appends a real-matcher entry to the SAME entries list the discriminator-only method above
    // appends to, so a call the SUT actually makes through the real overload is visible to both
    // surfaces consistently. Generic exactly when the discriminator-only method above is (Amendment
    // 1's "extension becomes generic" rule, unaffected by matching-eligibility) - a same-parameter-
    // types generic/non-generic overload pair would otherwise collide (CS0111) with a fixed arity.
    public static global::TestNamespace_IRepository_e3198068_Double.__Value_b9dfaa09_Builder ValueMatching(this global::TestNamespace_IRepository_e3198068_Double __self, global::Compono.Match<int> offset)
    {
        var __entry = new global::TestNamespace_IRepository_e3198068_Double.__Value_b9dfaa09_Entry();
        __entry.Matcher_offset = offset;
        lock (__self.__Value_b9dfaa09_lock) { __self.__Value_b9dfaa09_entries.Add(__entry); }
        return new global::TestNamespace_IRepository_e3198068_Double.__Value_b9dfaa09_Builder(ref __entry.Config, ref __entry.Callback);
    }

}

internal readonly struct TestNamespace_IRepository_e3198068_DoubleVerifier
{
    internal global::TestNamespace_IRepository_e3198068_Double Instance { get; }

    internal TestNamespace_IRepository_e3198068_DoubleVerifier(global::TestNamespace_IRepository_e3198068_Double instance) => Instance = instance;
}

internal static class TestNamespace_IRepository_e3198068_VerifyExtension
{
    public static global::TestNamespace_IRepository_e3198068_DoubleVerifier Verify(this global::TestNamespace.IRepository self) =>
        new(self as global::TestNamespace_IRepository_e3198068_Double
            ?? throw new global::System.InvalidOperationException(
                $"'{self.GetType()}' is not the 'global::TestNamespace.IRepository' test double generated for this assembly. " +
                "If another assembly in this process also generated a double for 'global::TestNamespace.IRepository', only one " +
                "registration wins process-wide (Compono.GeneratedTestDoubleRegistry, first-registration-wins) " +
                "- this is a known v1 limitation, not a bug in your test."));
}

internal static class TestNamespace_IRepository_e3198068_DoubleVerification
{
    // ADR-0044 Amendment 21 / PLAN-0054 Phase 2: discriminator-only Verify() - real parameter
    // types, unchanged signature - reads the shared per-overload call log's unfiltered Count
    // instead of a removed field's ConfiguredCallCount.
    public static global::Compono.CallVerifier Value(this global::TestNamespace_IRepository_e3198068_DoubleVerifier __self, int offset)
    {
        int __count;
        lock (__self.Instance.__Value_b9dfaa09_lock) { __count = __self.Instance.__Value_b9dfaa09_calls.Count; }
        return new(__count, "global::TestNamespace.IBaseB.Value");
    }

    // New matching-specific member name (ADR-0044 Amendment 21) - reads the SAME call log, filtered
    // by the supplied matchers, counting only real calls whose real arguments satisfy every one.
    // Generic exactly when the discriminator-only method above is - same reasoning as Configure().
    public static global::Compono.CallVerifier ValueMatching(this global::TestNamespace_IRepository_e3198068_DoubleVerifier __self, global::Compono.Match<int> offset)
    {
        int __count;
        lock (__self.Instance.__Value_b9dfaa09_lock)
        {
            __count = 0;
            foreach (var call in __self.Instance.__Value_b9dfaa09_calls)
            {
                if (offset.Matches(call))
                    __count++;
            }
        }
        return new(__count, "global::TestNamespace.IBaseB.Value");
    }

}

internal static class TestNamespace_IRepository_e3198068_ConfigureExtension
{
    public static global::TestNamespace_IRepository_e3198068_Double Configure(this global::TestNamespace.IRepository self) =>
        self as global::TestNamespace_IRepository_e3198068_Double
            ?? throw new global::System.InvalidOperationException(
                $"'{self.GetType()}' is not the 'global::TestNamespace.IRepository' test double generated for this assembly. " +
                "If another assembly in this process also generated a double for 'global::TestNamespace.IRepository', only one " +
                "registration wins process-wide (Compono.GeneratedTestDoubleRegistry, first-registration-wins) " +
                "- this is a known v1 limitation, not a bug in your test.");
}

file static class TestNamespace_IRepository_e3198068_DoubleRegistration
{
    [global::System.Runtime.CompilerServices.ModuleInitializer]
    internal static void Register() =>
        global::Compono.GeneratedTestDoubleRegistry.RegisterFactory<global::TestNamespace.IRepository>(
            () => new global::TestNamespace_IRepository_e3198068_Double());
}
