//HintName: TestNamespace.IThing_7b7b47c0.TestDouble.g.cs
// <auto-generated/>
#nullable enable

[global::System.CodeDom.Compiler.GeneratedCode("Compono.Generators", "REPLACED")]
internal sealed class TestNamespace_IThing_7b7b47c0_Double : global::TestNamespace.IThing
{
    internal global::Compono.ReturnConfig<global::Compono.Unit> __Configure;

    void global::TestNamespace.IThing.Configure<T>()
    {
        if (__Configure.HasConfiguredException)
            throw __Configure.ConfiguredException;
    }
}

internal static class TestNamespace_IThing_7b7b47c0_DoubleConfiguration
{
    public static global::Compono.ReturnConfigBuilder<global::Compono.Unit> Configure(this global::TestNamespace_IThing_7b7b47c0_Double self) =>
        new global::Compono.ReturnConfigBuilder<global::Compono.Unit>(ref self.__Configure);

}

internal static class TestNamespace_IThing_7b7b47c0_ConfigureExtension
{
    public static global::TestNamespace_IThing_7b7b47c0_Double Configure(this global::TestNamespace.IThing self) =>
        self as global::TestNamespace_IThing_7b7b47c0_Double
            ?? throw new global::System.InvalidOperationException(
                $"'{self.GetType()}' is not the 'global::TestNamespace.IThing' test double generated for this assembly. " +
                "If another assembly in this process also generated a double for 'global::TestNamespace.IThing', only one " +
                "registration wins process-wide (Compono.GeneratedTestDoubleRegistry, first-registration-wins) " +
                "- this is a known v1 limitation, not a bug in your test.");
}

file static class TestNamespace_IThing_7b7b47c0_DoubleRegistration
{
    [global::System.Runtime.CompilerServices.ModuleInitializer]
    internal static void Register() =>
        global::Compono.GeneratedTestDoubleRegistry.RegisterFactory<global::TestNamespace.IThing>(
            () => new global::TestNamespace_IThing_7b7b47c0_Double());
}
