//HintName: TestNamespace.ILeaf12_2124707f.TestDouble.g.cs
// <auto-generated/>
#nullable enable

[global::System.CodeDom.Compiler.GeneratedCode("Compono.Generators", "REPLACED")]
internal sealed class TestNamespace_ILeaf12_2124707f_Double : global::TestNamespace.ILeaf12
{
    internal delegate bool __Flag_Callback();

    internal readonly ref struct __Flag_Builder
    {
        private readonly ref global::Compono.ReturnConfig<bool> _config;
        private readonly ref __Flag_Callback? _callback;

        internal __Flag_Builder(ref global::Compono.ReturnConfig<bool> config, ref __Flag_Callback? callback)
        {
            _config = ref config;
            _callback = ref callback;
        }

        public void Returns(bool value)
        {
            _callback = null;
            new global::Compono.ReturnConfigBuilder<bool>(ref _config).Returns(value);
        }

        public void Throws(global::System.Exception exception)
        {
            _callback = null;
            new global::Compono.ReturnConfigBuilder<bool>(ref _config).Throws(exception);
        }

        public void ReturnsSequence(params global::Compono.SequenceOutcome<bool>[] outcomes)
        {
            _callback = null;
            new global::Compono.ReturnConfigBuilder<bool>(ref _config).ReturnsSequence(outcomes);
        }

        public void ReturnsCallback(__Flag_Callback callback)
        {
            global::System.ArgumentNullException.ThrowIfNull(callback);
            _config.ClearConfiguredResponse();
            _callback = callback;
        }
    }
    // ADR-0044 Amendment 20: the owner-forwarding dispatch helper is a pure, stateless forward to
    // `this` (never independently mutated), so one instance is reused for every unconfigured call
    // to this member instead of allocating a fresh one per call (code-review finding). A benign
    // race under concurrent first-use (two threads each constructing one before either publishes)
    // is harmless - both forward identically, and only one is kept.
    private __Flag_DimFallback? __Flag_dimHelper;
    internal global::Compono.ReturnConfig<bool> __Flag;
    internal __Flag_Callback? __Flag_callback;
    // ADR-0044 Amendment 20: owner-forwarding dispatch helper - holds the real generated double,
    // implements global::TestNamespace.IBase12 but deliberately does NOT
    // override Flag, so calling Flag through this helper's
    // own global::TestNamespace.IBase12 view lets C#'s own default-interface-
    // member dispatch resolve to the interface's real body. Every OTHER member this helper must
    // implement to satisfy that interface's full contract is a pure forward back to the owner's own
    // explicit implementation - never independently recorded, so exactly one place (the owner's own
    // Flag implementation, below) ever records a call to this member.
    internal sealed class __Flag_DimFallback : global::TestNamespace.IBase12
    {
        private readonly TestNamespace_ILeaf12_2124707f_Double _owner;

        internal __Flag_DimFallback(TestNamespace_ILeaf12_2124707f_Double owner) => _owner = owner;
    }

    bool global::TestNamespace.IBase12.Flag()
    {
        __Flag.RecordCall();
        return __Flag_callback is { } callback ? callback()
            : __Flag.HasConfiguredSequence ? __Flag.NextSequenceOutcome()
            : __Flag.HasConfiguredException ? throw __Flag.ConfiguredException
            : __Flag.HasConfiguredValue ? __Flag.ConfiguredValue
            : ((global::TestNamespace.IBase12)(this.__Flag_dimHelper ??= new __Flag_DimFallback(this))).Flag();
    }
}

internal static class TestNamespace_ILeaf12_2124707f_DoubleConfiguration
{
    public static global::TestNamespace_ILeaf12_2124707f_Double.__Flag_Builder Flag(this global::TestNamespace_ILeaf12_2124707f_Double self) =>
        new global::TestNamespace_ILeaf12_2124707f_Double.__Flag_Builder(ref self.__Flag, ref self.__Flag_callback);

}

internal readonly struct TestNamespace_ILeaf12_2124707f_DoubleVerifier
{
    internal global::TestNamespace_ILeaf12_2124707f_Double Instance { get; }

    internal TestNamespace_ILeaf12_2124707f_DoubleVerifier(global::TestNamespace_ILeaf12_2124707f_Double instance) => Instance = instance;
}

internal static class TestNamespace_ILeaf12_2124707f_VerifyExtension
{
    public static global::TestNamespace_ILeaf12_2124707f_DoubleVerifier Verify(this global::TestNamespace.ILeaf12 self) =>
        new(self as global::TestNamespace_ILeaf12_2124707f_Double
            ?? throw new global::System.InvalidOperationException(
                $"'{self.GetType()}' is not the 'global::TestNamespace.ILeaf12' test double generated for this assembly. " +
                "If another assembly in this process also generated a double for 'global::TestNamespace.ILeaf12', only one " +
                "registration wins process-wide (Compono.GeneratedTestDoubleRegistry, first-registration-wins) " +
                "- this is a known v1 limitation, not a bug in your test."));
}

internal static class TestNamespace_ILeaf12_2124707f_DoubleVerification
{
    public static global::Compono.CallVerifier Flag(this global::TestNamespace_ILeaf12_2124707f_DoubleVerifier self) =>
        new(self.Instance.__Flag.ConfiguredCallCount, "global::TestNamespace.IBase12.Flag");

}

internal static class TestNamespace_ILeaf12_2124707f_ConfigureExtension
{
    public static global::TestNamespace_ILeaf12_2124707f_Double Configure(this global::TestNamespace.ILeaf12 self) =>
        self as global::TestNamespace_ILeaf12_2124707f_Double
            ?? throw new global::System.InvalidOperationException(
                $"'{self.GetType()}' is not the 'global::TestNamespace.ILeaf12' test double generated for this assembly. " +
                "If another assembly in this process also generated a double for 'global::TestNamespace.ILeaf12', only one " +
                "registration wins process-wide (Compono.GeneratedTestDoubleRegistry, first-registration-wins) " +
                "- this is a known v1 limitation, not a bug in your test.");
}

file static class TestNamespace_ILeaf12_2124707f_DoubleRegistration
{
    [global::System.Runtime.CompilerServices.ModuleInitializer]
    internal static void Register() =>
        global::Compono.GeneratedTestDoubleRegistry.RegisterFactory<global::TestNamespace.ILeaf12>(
            () => new global::TestNamespace_ILeaf12_2124707f_Double());
}
