//HintName: TestNamespace.IFactory_993557a2.TestDouble.g.cs
// <auto-generated/>
#nullable enable

[global::System.CodeDom.Compiler.GeneratedCode("Compono.Generators", "REPLACED")]
internal sealed class TestNamespace_IFactory_993557a2_Double : global::TestNamespace.IFactory
{
    internal delegate T __Create_Callback<T>();

    internal readonly ref struct __Create_Builder<T>
    {
        private readonly ref global::Compono.ReturnConfig<T> _config;
        private readonly ref __Create_Callback<T>? _callback;

        internal __Create_Builder(ref global::Compono.ReturnConfig<T> config, ref __Create_Callback<T>? callback)
        {
            _config = ref config;
            _callback = ref callback;
        }

        public void Returns(T value)
        {
            _callback = null;
            new global::Compono.ReturnConfigBuilder<T>(ref _config).Returns(value);
        }

        public void Throws(global::System.Exception exception)
        {
            _callback = null;
            new global::Compono.ReturnConfigBuilder<T>(ref _config).Throws(exception);
        }

        public void ReturnsSequence(params global::Compono.SequenceOutcome<T>[] outcomes)
        {
            _callback = null;
            new global::Compono.ReturnConfigBuilder<T>(ref _config).ReturnsSequence(outcomes);
        }

        public void ReturnsCallback(__Create_Callback<T> callback)
        {
            global::System.ArgumentNullException.ThrowIfNull(callback);
            _config.ClearConfiguredResponse();
            _callback = callback;
        }
    }
    internal sealed class __Create_State<T>
    {
        internal global::Compono.ReturnConfig<T> Config;
        internal __Create_Callback<T>? Callback;
    }

    internal readonly global::System.Collections.Generic.Dictionary<global::System.Type, object> __Create_buckets = new();

    internal __Create_State<T> __Create_Bucket<T>()
    {
        lock (__Create_buckets)
        {
            if (!__Create_buckets.TryGetValue(typeof(T), out var __boxed))
            {
                __boxed = new __Create_State<T>();
                __Create_buckets[typeof(T)] = __boxed;
            }

            return (__Create_State<T>)__boxed;
        }
    }

    T global::TestNamespace.IFactory.Create<T>()
    {
        var __bucket = __Create_Bucket<T>();
        __bucket.Config.RecordCall();
        return __bucket.Callback is { } callback ? callback()
            : __bucket.Config.HasConfiguredSequence ? __bucket.Config.NextSequenceOutcome()
            : __bucket.Config.HasConfiguredException ? throw __bucket.Config.ConfiguredException
            : __bucket.Config.HasConfiguredValue ? __bucket.Config.ConfiguredValue
            : throw new global::Compono.TestDoubleNotConfiguredException(
                "'global::TestNamespace.IFactory.Create' was invoked without being configured (or without a matching argument configuration) for this closed type argument - call Configure().Create<T>(...).Returns(...) or .Throws(...) before invoking it.");
    }
}

internal static class TestNamespace_IFactory_993557a2_DoubleConfiguration
{
    public static global::TestNamespace_IFactory_993557a2_Double.__Create_Builder<T> Create<T>(this global::TestNamespace_IFactory_993557a2_Double __self)
    {
        var __bucket = __self.__Create_Bucket<T>();
        return new global::TestNamespace_IFactory_993557a2_Double.__Create_Builder<T>(ref __bucket.Config, ref __bucket.Callback);
    }

}

internal readonly struct TestNamespace_IFactory_993557a2_DoubleVerifier
{
    internal global::TestNamespace_IFactory_993557a2_Double Instance { get; }

    internal TestNamespace_IFactory_993557a2_DoubleVerifier(global::TestNamespace_IFactory_993557a2_Double instance) => Instance = instance;
}

internal static class TestNamespace_IFactory_993557a2_VerifyExtension
{
    public static global::TestNamespace_IFactory_993557a2_DoubleVerifier Verify(this global::TestNamespace.IFactory self) =>
        new(self as global::TestNamespace_IFactory_993557a2_Double
            ?? throw new global::System.InvalidOperationException(
                $"'{self.GetType()}' is not the 'global::TestNamespace.IFactory' test double generated for this assembly. " +
                "If another assembly in this process also generated a double for 'global::TestNamespace.IFactory', only one " +
                "registration wins process-wide (Compono.GeneratedTestDoubleRegistry, first-registration-wins) " +
                "- this is a known v1 limitation, not a bug in your test."));
}

internal static class TestNamespace_IFactory_993557a2_DoubleVerification
{
    public static global::Compono.CallVerifier Create<T>(this global::TestNamespace_IFactory_993557a2_DoubleVerifier __self) =>
        new(__self.Instance.__Create_Bucket<T>().Config.ConfiguredCallCount, "global::TestNamespace.IFactory.Create");

}

internal static class TestNamespace_IFactory_993557a2_ConfigureExtension
{
    public static global::TestNamespace_IFactory_993557a2_Double Configure(this global::TestNamespace.IFactory self) =>
        self as global::TestNamespace_IFactory_993557a2_Double
            ?? throw new global::System.InvalidOperationException(
                $"'{self.GetType()}' is not the 'global::TestNamespace.IFactory' test double generated for this assembly. " +
                "If another assembly in this process also generated a double for 'global::TestNamespace.IFactory', only one " +
                "registration wins process-wide (Compono.GeneratedTestDoubleRegistry, first-registration-wins) " +
                "- this is a known v1 limitation, not a bug in your test.");
}

file static class TestNamespace_IFactory_993557a2_DoubleRegistration
{
    [global::System.Runtime.CompilerServices.ModuleInitializer]
    internal static void Register() =>
        global::Compono.GeneratedTestDoubleRegistry.RegisterFactory<global::TestNamespace.IFactory>(
            () => new global::TestNamespace_IFactory_993557a2_Double());
}
