//HintName: TestNamespace.IWidget_34aa79b8.TestDouble.g.cs
// <auto-generated/>
#nullable enable

[global::System.CodeDom.Compiler.GeneratedCode("Compono.Generators", "REPLACED")]
internal sealed class TestNamespace_IWidget_34aa79b8_Double : global::TestNamespace.IWidget
{
    internal global::Compono.ReturnConfig<global::Compono.Unit> __Process_9f03e88f;
    internal global::Compono.ReturnConfig<global::Compono.Unit> __Process_5792c437;

    void global::TestNamespace.IWidget.Process<T>(T value)
    {
        __Process_9f03e88f.RecordCall();
        if (__Process_9f03e88f.HasConfiguredSequence)
            __Process_9f03e88f.NextSequenceOutcome();
        else if (__Process_9f03e88f.HasConfiguredException)
            throw __Process_9f03e88f.ConfiguredException;
    }

    void global::TestNamespace.IWidget.Process<T>(string label, T value)
    {
        __Process_5792c437.RecordCall();
        if (__Process_5792c437.HasConfiguredSequence)
            __Process_5792c437.NextSequenceOutcome();
        else if (__Process_5792c437.HasConfiguredException)
            throw __Process_5792c437.ConfiguredException;
    }
}

internal static class TestNamespace_IWidget_34aa79b8_DoubleConfiguration
{
    public static global::Compono.ReturnConfigBuilder<global::Compono.Unit> Process<T>(this global::TestNamespace_IWidget_34aa79b8_Double __self, T value) where T : allows ref struct =>
        new global::Compono.ReturnConfigBuilder<global::Compono.Unit>(ref __self.__Process_9f03e88f);

    public static global::Compono.ReturnConfigBuilder<global::Compono.Unit> Process<T>(this global::TestNamespace_IWidget_34aa79b8_Double __self, string label, T value) where T : allows ref struct =>
        new global::Compono.ReturnConfigBuilder<global::Compono.Unit>(ref __self.__Process_5792c437);

}

internal readonly struct TestNamespace_IWidget_34aa79b8_DoubleVerifier
{
    internal global::TestNamespace_IWidget_34aa79b8_Double Instance { get; }

    internal TestNamespace_IWidget_34aa79b8_DoubleVerifier(global::TestNamespace_IWidget_34aa79b8_Double instance) => Instance = instance;
}

internal static class TestNamespace_IWidget_34aa79b8_VerifyExtension
{
    public static global::TestNamespace_IWidget_34aa79b8_DoubleVerifier Verify(this global::TestNamespace.IWidget self) =>
        new(self as global::TestNamespace_IWidget_34aa79b8_Double
            ?? throw new global::System.InvalidOperationException(
                $"'{self.GetType()}' is not the 'global::TestNamespace.IWidget' test double generated for this assembly. " +
                "If another assembly in this process also generated a double for 'global::TestNamespace.IWidget', only one " +
                "registration wins process-wide (Compono.GeneratedTestDoubleRegistry, first-registration-wins) " +
                "- this is a known v1 limitation, not a bug in your test."));
}

internal static class TestNamespace_IWidget_34aa79b8_DoubleVerification
{
    public static global::Compono.CallVerifier Process<T>(this global::TestNamespace_IWidget_34aa79b8_DoubleVerifier __self, T value) where T : allows ref struct =>
        new(__self.Instance.__Process_9f03e88f.ConfiguredCallCount, "global::TestNamespace.IWidget.Process");

    public static global::Compono.CallVerifier Process<T>(this global::TestNamespace_IWidget_34aa79b8_DoubleVerifier __self, string label, T value) where T : allows ref struct =>
        new(__self.Instance.__Process_5792c437.ConfiguredCallCount, "global::TestNamespace.IWidget.Process");

}

internal static class TestNamespace_IWidget_34aa79b8_ConfigureExtension
{
    public static global::TestNamespace_IWidget_34aa79b8_Double Configure(this global::TestNamespace.IWidget self) =>
        self as global::TestNamespace_IWidget_34aa79b8_Double
            ?? throw new global::System.InvalidOperationException(
                $"'{self.GetType()}' is not the 'global::TestNamespace.IWidget' test double generated for this assembly. " +
                "If another assembly in this process also generated a double for 'global::TestNamespace.IWidget', only one " +
                "registration wins process-wide (Compono.GeneratedTestDoubleRegistry, first-registration-wins) " +
                "- this is a known v1 limitation, not a bug in your test.");
}

file static class TestNamespace_IWidget_34aa79b8_DoubleRegistration
{
    [global::System.Runtime.CompilerServices.ModuleInitializer]
    internal static void Register() =>
        global::Compono.GeneratedTestDoubleRegistry.RegisterFactory<global::TestNamespace.IWidget>(
            () => new global::TestNamespace_IWidget_34aa79b8_Double());
}
