//HintName: TestNamespace.IRepository_e3198068.TestDouble.g.cs
// <auto-generated/>
#nullable enable

[global::System.CodeDom.Compiler.GeneratedCode("Compono.Generators", "REPLACED")]
internal sealed class TestNamespace_IRepository_e3198068_Double : global::TestNamespace.IRepository
{
    internal global::Compono.ReturnConfig<global::Compono.Unit> __M_0e236ea3;
    internal global::Compono.ReturnConfig<global::Compono.Unit> __M_1a56931a;

    void global::TestNamespace.IRepository.M(global::TestNamespace.Mode? mode)
    {
        __M_0e236ea3.RecordCall();
        if (__M_0e236ea3.HasConfiguredException)
            throw __M_0e236ea3.ConfiguredException;
    }

    void global::TestNamespace.IRepository.M(string value)
    {
        __M_1a56931a.RecordCall();
        if (__M_1a56931a.HasConfiguredException)
            throw __M_1a56931a.ConfiguredException;
    }
}

internal static class TestNamespace_IRepository_e3198068_DoubleConfiguration
{
    public static global::Compono.ReturnConfigBuilder<global::Compono.Unit> M(this global::TestNamespace_IRepository_e3198068_Double __self, global::TestNamespace.Mode? mode = (global::TestNamespace.Mode)1) =>
        new global::Compono.ReturnConfigBuilder<global::Compono.Unit>(ref __self.__M_0e236ea3);

    public static global::Compono.ReturnConfigBuilder<global::Compono.Unit> M(this global::TestNamespace_IRepository_e3198068_Double __self, string value) =>
        new global::Compono.ReturnConfigBuilder<global::Compono.Unit>(ref __self.__M_1a56931a);

}

internal readonly struct TestNamespace_IRepository_e3198068_DoubleVerifier
{
    internal global::TestNamespace_IRepository_e3198068_Double Instance { get; }

    internal TestNamespace_IRepository_e3198068_DoubleVerifier(global::TestNamespace_IRepository_e3198068_Double instance) => Instance = instance;
}

internal static class TestNamespace_IRepository_e3198068_VerifyExtension
{
    public static global::TestNamespace_IRepository_e3198068_DoubleVerifier Verify(this global::TestNamespace.IRepository self) =>
        new(self as global::TestNamespace_IRepository_e3198068_Double
            ?? throw new global::System.InvalidOperationException(
                $"'{self.GetType()}' is not the 'global::TestNamespace.IRepository' test double generated for this assembly. " +
                "If another assembly in this process also generated a double for 'global::TestNamespace.IRepository', only one " +
                "registration wins process-wide (Compono.GeneratedTestDoubleRegistry, first-registration-wins) " +
                "- this is a known v1 limitation, not a bug in your test."));
}

internal static class TestNamespace_IRepository_e3198068_DoubleVerification
{
    public static global::Compono.CallVerifier M(this global::TestNamespace_IRepository_e3198068_DoubleVerifier __self, global::TestNamespace.Mode? mode = (global::TestNamespace.Mode)1) =>
        new(__self.Instance.__M_0e236ea3.ConfiguredCallCount, "global::TestNamespace.IRepository.M");

    public static global::Compono.CallVerifier M(this global::TestNamespace_IRepository_e3198068_DoubleVerifier __self, string value) =>
        new(__self.Instance.__M_1a56931a.ConfiguredCallCount, "global::TestNamespace.IRepository.M");

}

internal static class TestNamespace_IRepository_e3198068_ConfigureExtension
{
    public static global::TestNamespace_IRepository_e3198068_Double Configure(this global::TestNamespace.IRepository self) =>
        self as global::TestNamespace_IRepository_e3198068_Double
            ?? throw new global::System.InvalidOperationException(
                $"'{self.GetType()}' is not the 'global::TestNamespace.IRepository' test double generated for this assembly. " +
                "If another assembly in this process also generated a double for 'global::TestNamespace.IRepository', only one " +
                "registration wins process-wide (Compono.GeneratedTestDoubleRegistry, first-registration-wins) " +
                "- this is a known v1 limitation, not a bug in your test.");
}

file static class TestNamespace_IRepository_e3198068_DoubleRegistration
{
    [global::System.Runtime.CompilerServices.ModuleInitializer]
    internal static void Register() =>
        global::Compono.GeneratedTestDoubleRegistry.RegisterFactory<global::TestNamespace.IRepository>(
            () => new global::TestNamespace_IRepository_e3198068_Double());
}
