//HintName: TestNamespace.IFactory_993557a2.TestDouble.g.cs
// <auto-generated/>
#nullable enable

// PLAN-0063/ADR-0060: ClearCalls() reaches every ADR-0049 closed-instantiation-eligible member's
// per-closed-T bucket entries generically, with no static knowledge of which closed T's exist at
// runtime - this non-generic interface (implemented by every generated
// TestNamespace_IFactory_993557a2_*State<T> class below) is what makes that possible without reflection.
internal interface TestNamespace_IFactory_993557a2_IClearableCallState
{
    void ClearObservedCalls();
}

[global::System.CodeDom.Compiler.GeneratedCode("Compono.Generators", "REPLACED")]
internal sealed class TestNamespace_IFactory_993557a2_Double : global::TestNamespace.IFactory
{
    internal delegate U __M_m_x_Callback<U>();

    internal readonly ref struct __M_m_x_Builder<U>
    {
        private readonly ref global::Compono.ReturnConfig<U> _config;
        private readonly ref __M_m_x_Callback<U>? _callback;

        internal __M_m_x_Builder(ref global::Compono.ReturnConfig<U> config, ref __M_m_x_Callback<U>? callback)
        {
            _config = ref config;
            _callback = ref callback;
        }

        public void Returns(U value)
        {
            _callback = null;
            new global::Compono.ReturnConfigBuilder<U>(ref _config).Returns(value);
        }

        public void Throws(global::System.Exception exception)
        {
            _callback = null;
            new global::Compono.ReturnConfigBuilder<U>(ref _config).Throws(exception);
        }

        public void ReturnsSequence(params global::Compono.SequenceOutcome<U>[] outcomes)
        {
            _callback = null;
            new global::Compono.ReturnConfigBuilder<U>(ref _config).ReturnsSequence(outcomes);
        }

        public void ReturnsCallback(__M_m_x_Callback<U> callback)
        {
            global::System.ArgumentNullException.ThrowIfNull(callback);
            _config.ClearConfiguredResponse();
            _callback = callback;
        }
    }
    internal sealed class __M_m_x_State<U> : TestNamespace_IFactory_993557a2_IClearableCallState
    {
        internal global::Compono.ReturnConfig<U> Config;
        internal __M_m_x_Callback<U>? Callback;

        // PLAN-0063/ADR-0060: see the matched-parameters branch above for the full rationale - this
        // shape has no argument history to clear, only the scalar call count.
        public void ClearObservedCalls() => this.Config.ClearObservedCalls();
    }

    internal readonly global::System.Collections.Generic.Dictionary<global::System.Type, object> __M_m_x_buckets = new();

    internal __M_m_x_State<U> __M_m_x_Bucket<U>()
    {
        lock (__M_m_x_buckets)
        {
            if (!__M_m_x_buckets.TryGetValue(typeof(U), out var __boxed))
            {
                __boxed = new __M_m_x_State<U>();
                __M_m_x_buckets[typeof(U)] = __boxed;
            }

            return (__M_m_x_State<U>)__boxed;
        }
    }
    internal global::Compono.ReturnConfig<global::Compono.Unit> __M;

    U global::TestNamespace.IFactory.M_m_x<U>()
    {
        var __bucket = __M_m_x_Bucket<U>();
        __bucket.Config.RecordCall();
        return __bucket.Callback is { } callback ? callback()
            : __bucket.Config.HasConfiguredSequence ? __bucket.Config.NextSequenceOutcome()
            : __bucket.Config.HasConfiguredException ? throw __bucket.Config.ConfiguredException
            : __bucket.Config.HasConfiguredValue ? __bucket.Config.ConfiguredValue
            : throw new global::Compono.TestDoubleNotConfiguredException(
                "'global::TestNamespace.IFactory.M_m_x' was invoked without being configured (or without a matching argument configuration) for this closed type argument - call Configure().M_m_x<U>(...).Returns(...) or .Throws(...) before invoking it.");
    }

    void global::TestNamespace.IFactory.M<T>(T x_State)
    {
        __M.RecordCall();
        if (__M.HasConfiguredSequence)
            __M.NextSequenceOutcome();
        else if (__M.HasConfiguredException)
            throw __M.ConfiguredException;
    }
}

internal static class TestNamespace_IFactory_993557a2_DoubleConfiguration
{
    public static global::TestNamespace_IFactory_993557a2_Double.__M_m_x_Builder<U> M_m_x<U>(this global::TestNamespace_IFactory_993557a2_Double __self)
    {
        var __bucket = __self.__M_m_x_Bucket<U>();
        return new global::TestNamespace_IFactory_993557a2_Double.__M_m_x_Builder<U>(ref __bucket.Config, ref __bucket.Callback);
    }

    public static global::Compono.ReturnConfigBuilder<global::Compono.Unit> M(this global::TestNamespace_IFactory_993557a2_Double self) =>
        new global::Compono.ReturnConfigBuilder<global::Compono.Unit>(ref self.__M);

}

internal readonly struct TestNamespace_IFactory_993557a2_DoubleVerifier
{
    internal global::TestNamespace_IFactory_993557a2_Double Instance { get; }

    internal TestNamespace_IFactory_993557a2_DoubleVerifier(global::TestNamespace_IFactory_993557a2_Double instance) => Instance = instance;
}

internal static class TestNamespace_IFactory_993557a2_VerifyExtension
{
    public static global::TestNamespace_IFactory_993557a2_DoubleVerifier Verify(this global::TestNamespace.IFactory self) =>
        new(self as global::TestNamespace_IFactory_993557a2_Double
            ?? throw new global::System.InvalidOperationException(
                $"'{self.GetType()}' is not the 'global::TestNamespace.IFactory' test double generated for this assembly. " +
                "If another assembly in this process also generated a double for 'global::TestNamespace.IFactory', only one " +
                "registration wins process-wide (Compono.GeneratedTestDoubleRegistry, first-registration-wins) " +
                "- this is a known v1 limitation, not a bug in your test."));
}

internal static class TestNamespace_IFactory_993557a2_DoubleVerification
{
    public static global::Compono.CallVerifier M_m_x<U>(this global::TestNamespace_IFactory_993557a2_DoubleVerifier __self) =>
        new(__self.Instance.__M_m_x_Bucket<U>().Config.ConfiguredCallCount, "global::TestNamespace.IFactory.M_m_x");

    public static global::Compono.CallVerifier M(this global::TestNamespace_IFactory_993557a2_DoubleVerifier self) =>
        new(self.Instance.__M.ConfiguredCallCount, "global::TestNamespace.IFactory.M");

}

// PLAN-0063/ADR-0060: ReceivedCalls() - retrospective, snapshot-based call inspection, scoped to
// exactly the ADR-0048 eligible-member set (member.is_eligible_for_matching), unexpanded. A
// distinct third bridge from Configure()/Verify() - never attaches captured data to CallVerifier.
internal readonly struct TestNamespace_IFactory_993557a2_DoubleReceivedCalls
{
    internal global::TestNamespace_IFactory_993557a2_Double Instance { get; }

    internal TestNamespace_IFactory_993557a2_DoubleReceivedCalls(global::TestNamespace_IFactory_993557a2_Double instance) => Instance = instance;
}

internal static class TestNamespace_IFactory_993557a2_ReceivedCallsExtension
{
    public static global::TestNamespace_IFactory_993557a2_DoubleReceivedCalls ReceivedCalls(this global::TestNamespace.IFactory self) =>
        new(self as global::TestNamespace_IFactory_993557a2_Double
            ?? throw new global::System.InvalidOperationException(
                $"'{self.GetType()}' is not the 'global::TestNamespace.IFactory' test double generated for this assembly. " +
                "If another assembly in this process also generated a double for 'global::TestNamespace.IFactory', only one " +
                "registration wins process-wide (Compono.GeneratedTestDoubleRegistry, first-registration-wins) " +
                "- this is a known v1 limitation, not a bug in your test."));
}

internal static class TestNamespace_IFactory_993557a2_DoubleReceivedCallsAccess
{
}

// PLAN-0063/ADR-0060: ClearCalls() - a direct, whole-double operation clearing every member's
// observation state (scalar call counts + ADR-0048 captured argument histories) while preserving
// all configured behavior (Returns/Throws/ReturnsCallback/ReturnsSequence - including in-progress
// SequenceOrdinal, which does not rewind - argument-matcher/multi-entry configuration, and generic
// closed-instantiation configuration). No per-member ClearCalls(), no global whole-double lock -
// each member's own existing synchronization primitive is used independently, per member.
internal static class TestNamespace_IFactory_993557a2_ClearCallsExtension
{
    public static void ClearCalls(this global::TestNamespace.IFactory self)
    {
        var __double = self as global::TestNamespace_IFactory_993557a2_Double
            ?? throw new global::System.InvalidOperationException(
                $"'{self.GetType()}' is not the 'global::TestNamespace.IFactory' test double generated for this assembly. " +
                "If another assembly in this process also generated a double for 'global::TestNamespace.IFactory', only one " +
                "registration wins process-wide (Compono.GeneratedTestDoubleRegistry, first-registration-wins) " +
                "- this is a known v1 limitation, not a bug in your test.");

        lock (__double.__M_m_x_buckets)
        {
            foreach (var __bucketEntry in __double.__M_m_x_buckets.Values)
                ((TestNamespace_IFactory_993557a2_IClearableCallState)__bucketEntry).ClearObservedCalls();
        }
        __double.__M.ClearObservedCalls();
    }
}

internal static class TestNamespace_IFactory_993557a2_ConfigureExtension
{
    public static global::TestNamespace_IFactory_993557a2_Double Configure(this global::TestNamespace.IFactory self) =>
        self as global::TestNamespace_IFactory_993557a2_Double
            ?? throw new global::System.InvalidOperationException(
                $"'{self.GetType()}' is not the 'global::TestNamespace.IFactory' test double generated for this assembly. " +
                "If another assembly in this process also generated a double for 'global::TestNamespace.IFactory', only one " +
                "registration wins process-wide (Compono.GeneratedTestDoubleRegistry, first-registration-wins) " +
                "- this is a known v1 limitation, not a bug in your test.");
}

file static class TestNamespace_IFactory_993557a2_DoubleRegistration
{
    [global::System.Runtime.CompilerServices.ModuleInitializer]
    internal static void Register() =>
        global::Compono.GeneratedTestDoubleRegistry.RegisterFactory<global::TestNamespace.IFactory>(
            () => new global::TestNamespace_IFactory_993557a2_Double());
}
