//HintName: TestNamespace.IRepository_e3198068.TestDouble.g.cs
// <auto-generated/>
#nullable enable

[global::System.CodeDom.Compiler.GeneratedCode("Compono.Generators", "REPLACED")]
internal sealed class TestNamespace_IRepository_e3198068_Double : global::TestNamespace.IRepository
{
    internal global::Compono.ReturnConfig<string?> __ToString_1ccd22c1;
    internal global::Compono.ReturnConfig<string?> __ToString_987ab372;

    string? global::TestNamespace.IRepository.ToString(object[] values) =>
        __ToString_1ccd22c1.HasConfiguredException ? throw __ToString_1ccd22c1.ConfiguredException
        : __ToString_1ccd22c1.HasConfiguredValue ? __ToString_1ccd22c1.ConfiguredValue
        : default;

    string? global::TestNamespace.IRepository.ToString(int format) =>
        __ToString_987ab372.HasConfiguredException ? throw __ToString_987ab372.ConfiguredException
        : __ToString_987ab372.HasConfiguredValue ? __ToString_987ab372.ConfiguredValue
        : default;
}

internal static class TestNamespace_IRepository_e3198068_DoubleConfiguration
{
    public static global::Compono.ReturnConfigBuilder<string?> ToString(this global::TestNamespace_IRepository_e3198068_Double self, params object[] values) =>
        new global::Compono.ReturnConfigBuilder<string?>(ref self.__ToString_1ccd22c1);

    public static global::Compono.ReturnConfigBuilder<string?> ToString(this global::TestNamespace_IRepository_e3198068_Double self, int format) =>
        new global::Compono.ReturnConfigBuilder<string?>(ref self.__ToString_987ab372);

}

internal static class TestNamespace_IRepository_e3198068_ConfigureExtension
{
    public static global::TestNamespace_IRepository_e3198068_Double Configure(this global::TestNamespace.IRepository self) =>
        self as global::TestNamespace_IRepository_e3198068_Double
            ?? throw new global::System.InvalidOperationException(
                $"'{self.GetType()}' is not the 'global::TestNamespace.IRepository' test double generated for this assembly. " +
                "If another assembly in this process also generated a double for 'global::TestNamespace.IRepository', only one " +
                "registration wins process-wide (Compono.GeneratedTestDoubleRegistry, first-registration-wins) " +
                "- this is a known v1 limitation, not a bug in your test.");
}

file static class TestNamespace_IRepository_e3198068_DoubleRegistration
{
    [global::System.Runtime.CompilerServices.ModuleInitializer]
    internal static void Register() =>
        global::Compono.GeneratedTestDoubleRegistry.RegisterFactory<global::TestNamespace.IRepository>(
            () => new global::TestNamespace_IRepository_e3198068_Double());
}
