//HintName: TestNamespace.B_faebd325.CompositionPlan.g.cs
// <auto-generated/>
#nullable enable

namespace TestNamespace
{
    [global::System.CodeDom.Compiler.GeneratedCode("Compono.Generators", "REPLACED")]
    file sealed class BCompositionPlan : global::Compono.ICompositionPlan<global::TestNamespace.B>
    {
        public global::TestNamespace.B Compose(global::Compono.ICompositionContext context) =>
            new global::TestNamespace.B(
                context.Resolve<global::TestNamespace.IProvider<string>>(new global::Compono.CompositionRequestDescriptor(global::Compono.CompositionRequestKind.ConstructorParameter, 0, "provider", typeof(global::TestNamespace.B), global::Compono.Nullability.NotNullable))
            );
    }

    file static class BCompositionPlanRegistration
    {
        [global::System.Runtime.CompilerServices.ModuleInitializer]
        internal static void Register() =>
            global::Compono.PlanCache<global::TestNamespace.B>.Instance = new BCompositionPlan();
    }
}
