//HintName: TestNamespace.IRepository_e3198068.TestDouble.g.cs
// <auto-generated/>
#nullable enable

// PLAN-0063/ADR-0060: ClearCalls() reaches every ADR-0049 closed-instantiation-eligible member's
// per-closed-T bucket entries generically, with no static knowledge of which closed T's exist at
// runtime - this non-generic interface (implemented by every generated
// TestNamespace_IRepository_e3198068_*State<T> class below) is what makes that possible without reflection.
internal interface TestNamespace_IRepository_e3198068_IClearableCallState
{
    void ClearObservedCalls();
}

[global::System.CodeDom.Compiler.GeneratedCode("Compono.Generators", "REPLACED")]
internal sealed class TestNamespace_IRepository_e3198068_Double : global::TestNamespace.IRepository
{
    // ADR-0044 Amendment 20: the owner-forwarding dispatch helper is a pure, stateless forward to
    // `this` (never independently mutated), so one instance is reused for every unconfigured call
    // to this member instead of allocating a fresh one per call (code-review finding). A benign
    // race under concurrent first-use (two threads each constructing one before either publishes)
    // is harmless - both forward identically, and only one is kept.
    private __Value_DimFallback? __Value_dimHelper;
    internal global::Compono.ReturnConfig<int> __Value;
    // ADR-0044 Amendment 20: owner-forwarding dispatch helper - holds the real generated double,
    // implements global::TestNamespace.IRepository but deliberately does NOT
    // override Value, so calling Value through this helper's
    // own global::TestNamespace.IRepository view lets C#'s own default-interface-
    // member dispatch resolve to the interface's real body. Every OTHER member this helper must
    // implement to satisfy that interface's full contract is a pure forward back to the owner's own
    // explicit implementation - never independently recorded, so exactly one place (the owner's own
    // Value implementation, below) ever records a call to this member.
    internal sealed class __Value_DimFallback : global::TestNamespace.IRepository
    {
        private readonly TestNamespace_IRepository_e3198068_Double _owner;

        internal __Value_DimFallback(TestNamespace_IRepository_e3198068_Double owner) => _owner = owner;
    }

    int global::TestNamespace.IRepository.Value
    {
        get
        {
            __Value.RecordCall();
            return __Value.HasConfiguredSequence ? __Value.NextSequenceOutcome()
                : __Value.HasConfiguredException ? throw __Value.ConfiguredException
                : __Value.HasConfiguredValue ? __Value.ConfiguredValue
                : ((global::TestNamespace.IRepository)(this.__Value_dimHelper ??= new __Value_DimFallback(this))).Value;
        }
    }
}

internal static class TestNamespace_IRepository_e3198068_DoubleConfiguration
{
    public static global::Compono.ReturnConfigBuilder<int> Value(this global::TestNamespace_IRepository_e3198068_Double self) =>
        new global::Compono.ReturnConfigBuilder<int>(ref self.__Value);

}

internal readonly struct TestNamespace_IRepository_e3198068_DoubleVerifier
{
    internal global::TestNamespace_IRepository_e3198068_Double Instance { get; }

    internal TestNamespace_IRepository_e3198068_DoubleVerifier(global::TestNamespace_IRepository_e3198068_Double instance) => Instance = instance;
}

internal static class TestNamespace_IRepository_e3198068_VerifyExtension
{
    public static global::TestNamespace_IRepository_e3198068_DoubleVerifier Verify(this global::TestNamespace.IRepository self) =>
        new(self as global::TestNamespace_IRepository_e3198068_Double
            ?? throw new global::System.InvalidOperationException(
                $"'{self.GetType()}' is not the 'global::TestNamespace.IRepository' test double generated for this assembly. " +
                "If another assembly in this process also generated a double for 'global::TestNamespace.IRepository', only one " +
                "registration wins process-wide (Compono.GeneratedTestDoubleRegistry, first-registration-wins) " +
                "- this is a known v1 limitation, not a bug in your test."));
}

internal static class TestNamespace_IRepository_e3198068_DoubleVerification
{
    public static global::Compono.CallVerifier Value(this global::TestNamespace_IRepository_e3198068_DoubleVerifier self) =>
        new(self.Instance.__Value.ConfiguredCallCount, "global::TestNamespace.IRepository.Value");

}

// PLAN-0063/ADR-0060: ReceivedCalls() - retrospective, snapshot-based call inspection, scoped to
// exactly the ADR-0048 eligible-member set (member.is_eligible_for_matching), unexpanded. A
// distinct third bridge from Configure()/Verify() - never attaches captured data to CallVerifier.
internal readonly struct TestNamespace_IRepository_e3198068_DoubleReceivedCalls
{
    internal global::TestNamespace_IRepository_e3198068_Double Instance { get; }

    internal TestNamespace_IRepository_e3198068_DoubleReceivedCalls(global::TestNamespace_IRepository_e3198068_Double instance) => Instance = instance;
}

internal static class TestNamespace_IRepository_e3198068_ReceivedCallsExtension
{
    public static global::TestNamespace_IRepository_e3198068_DoubleReceivedCalls ReceivedCalls(this global::TestNamespace.IRepository self) =>
        new(self as global::TestNamespace_IRepository_e3198068_Double
            ?? throw new global::System.InvalidOperationException(
                $"'{self.GetType()}' is not the 'global::TestNamespace.IRepository' test double generated for this assembly. " +
                "If another assembly in this process also generated a double for 'global::TestNamespace.IRepository', only one " +
                "registration wins process-wide (Compono.GeneratedTestDoubleRegistry, first-registration-wins) " +
                "- this is a known v1 limitation, not a bug in your test."));
}

internal static class TestNamespace_IRepository_e3198068_DoubleReceivedCallsAccess
{
}

// PLAN-0063/ADR-0060: ClearCalls() - a direct, whole-double operation clearing every member's
// observation state (scalar call counts + ADR-0048 captured argument histories) while preserving
// all configured behavior (Returns/Throws/ReturnsCallback/ReturnsSequence - including in-progress
// SequenceOrdinal, which does not rewind - argument-matcher/multi-entry configuration, and generic
// closed-instantiation configuration). No per-member ClearCalls(), no global whole-double lock -
// each member's own existing synchronization primitive is used independently, per member.
internal static class TestNamespace_IRepository_e3198068_ClearCallsExtension
{
    public static void ClearCalls(this global::TestNamespace.IRepository self)
    {
        var __double = self as global::TestNamespace_IRepository_e3198068_Double
            ?? throw new global::System.InvalidOperationException(
                $"'{self.GetType()}' is not the 'global::TestNamespace.IRepository' test double generated for this assembly. " +
                "If another assembly in this process also generated a double for 'global::TestNamespace.IRepository', only one " +
                "registration wins process-wide (Compono.GeneratedTestDoubleRegistry, first-registration-wins) " +
                "- this is a known v1 limitation, not a bug in your test.");

        __double.__Value.ClearObservedCalls();
    }
}

internal static class TestNamespace_IRepository_e3198068_ConfigureExtension
{
    public static global::TestNamespace_IRepository_e3198068_Double Configure(this global::TestNamespace.IRepository self) =>
        self as global::TestNamespace_IRepository_e3198068_Double
            ?? throw new global::System.InvalidOperationException(
                $"'{self.GetType()}' is not the 'global::TestNamespace.IRepository' test double generated for this assembly. " +
                "If another assembly in this process also generated a double for 'global::TestNamespace.IRepository', only one " +
                "registration wins process-wide (Compono.GeneratedTestDoubleRegistry, first-registration-wins) " +
                "- this is a known v1 limitation, not a bug in your test.");
}

file static class TestNamespace_IRepository_e3198068_DoubleRegistration
{
    [global::System.Runtime.CompilerServices.ModuleInitializer]
    internal static void Register() =>
        global::Compono.GeneratedTestDoubleRegistry.RegisterFactory<global::TestNamespace.IRepository>(
            () => new global::TestNamespace_IRepository_e3198068_Double());
}
