//HintName: TestNamespace.OrderService_7c62cf5a.CompositionPlan.g.cs
// <auto-generated/>
#nullable enable

namespace TestNamespace
{
    [global::System.CodeDom.Compiler.GeneratedCode("Compono.Generators", "REPLACED")]
    file sealed class OrderServiceCompositionPlan : global::Compono.ICompositionPlan<global::TestNamespace.OrderService>
    {
        public global::TestNamespace.OrderService Compose(global::Compono.ICompositionContext context) =>
            new global::TestNamespace.OrderService(
                context.Resolve<global::TestNamespace.IHandler>(new global::Compono.CompositionRequestDescriptor(global::Compono.CompositionRequestKind.ConstructorParameter, 0, "handler", typeof(global::TestNamespace.OrderService), global::Compono.Nullability.NotNullable))
            );
    }

    file static class OrderServiceCompositionPlanRegistration
    {
        [global::System.Runtime.CompilerServices.ModuleInitializer]
        internal static void Register() =>
            global::Compono.PlanCache<global::TestNamespace.OrderService>.Instance = new OrderServiceCompositionPlan();
    }
}
