//HintName: TestNamespace.IFactory_993557a2.TestDouble.g.cs
// <auto-generated/>
#nullable enable

[global::System.CodeDom.Compiler.GeneratedCode("Compono.Generators", "REPLACED")]
internal sealed class TestNamespace_IFactory_993557a2_Double : global::TestNamespace.IFactory
{
    internal sealed class __Get_State<T> where T : class
    {
        internal global::Compono.ReturnConfig<global::System.Threading.Tasks.ValueTask<T?>> Config;
    }

    internal readonly global::System.Collections.Generic.Dictionary<global::System.Type, object> __Get_buckets = new();

    internal __Get_State<T> __Get_Bucket<T>() where T : class
    {
        lock (__Get_buckets)
        {
            if (!__Get_buckets.TryGetValue(typeof(T), out var boxed))
            {
                boxed = new __Get_State<T>();
                __Get_buckets[typeof(T)] = boxed;
            }

            return (__Get_State<T>)boxed;
        }
    }

#pragma warning disable CS8616, CS8619
    global::System.Threading.Tasks.ValueTask<T> global::TestNamespace.IFactory.Get<T>()
    {
        var __bucket = __Get_Bucket<T>();
        __bucket.Config.RecordCall();
        return __bucket.Config.HasConfiguredException ? throw __bucket.Config.ConfiguredException
            : __bucket.Config.HasConfiguredValue ? __bucket.Config.ConfiguredValue
            : global::System.Threading.Tasks.ValueTask.FromResult<T?>(default);
    }
#pragma warning restore CS8616, CS8619
}

internal static class TestNamespace_IFactory_993557a2_DoubleConfiguration
{
    public static global::Compono.ReturnConfigBuilder<global::System.Threading.Tasks.ValueTask<T?>> Get<T>(this global::TestNamespace_IFactory_993557a2_Double __self) where T : class
    {
        var __bucket = __self.__Get_Bucket<T>();
        return new global::Compono.ReturnConfigBuilder<global::System.Threading.Tasks.ValueTask<T?>>(ref __bucket.Config);
    }

}

internal readonly struct TestNamespace_IFactory_993557a2_DoubleVerifier
{
    internal global::TestNamespace_IFactory_993557a2_Double Instance { get; }

    internal TestNamespace_IFactory_993557a2_DoubleVerifier(global::TestNamespace_IFactory_993557a2_Double instance) => Instance = instance;
}

internal static class TestNamespace_IFactory_993557a2_VerifyExtension
{
    public static global::TestNamespace_IFactory_993557a2_DoubleVerifier Verify(this global::TestNamespace.IFactory self) =>
        new(self as global::TestNamespace_IFactory_993557a2_Double
            ?? throw new global::System.InvalidOperationException(
                $"'{self.GetType()}' is not the 'global::TestNamespace.IFactory' test double generated for this assembly. " +
                "If another assembly in this process also generated a double for 'global::TestNamespace.IFactory', only one " +
                "registration wins process-wide (Compono.GeneratedTestDoubleRegistry, first-registration-wins) " +
                "- this is a known v1 limitation, not a bug in your test."));
}

internal static class TestNamespace_IFactory_993557a2_DoubleVerification
{
    public static global::Compono.CallVerifier Get<T>(this global::TestNamespace_IFactory_993557a2_DoubleVerifier __self) where T : class =>
        new(__self.Instance.__Get_Bucket<T>().Config.ConfiguredCallCount, "global::TestNamespace.IFactory.Get");

}

internal static class TestNamespace_IFactory_993557a2_ConfigureExtension
{
    public static global::TestNamespace_IFactory_993557a2_Double Configure(this global::TestNamespace.IFactory self) =>
        self as global::TestNamespace_IFactory_993557a2_Double
            ?? throw new global::System.InvalidOperationException(
                $"'{self.GetType()}' is not the 'global::TestNamespace.IFactory' test double generated for this assembly. " +
                "If another assembly in this process also generated a double for 'global::TestNamespace.IFactory', only one " +
                "registration wins process-wide (Compono.GeneratedTestDoubleRegistry, first-registration-wins) " +
                "- this is a known v1 limitation, not a bug in your test.");
}

file static class TestNamespace_IFactory_993557a2_DoubleRegistration
{
    [global::System.Runtime.CompilerServices.ModuleInitializer]
    internal static void Register() =>
        global::Compono.GeneratedTestDoubleRegistry.RegisterFactory<global::TestNamespace.IFactory>(
            () => new global::TestNamespace_IFactory_993557a2_Double());
}
