//HintName: TestNamespace.IFactory_993557a2.TestDouble.g.cs
// <auto-generated/>
#nullable enable

[global::System.CodeDom.Compiler.GeneratedCode("Compono.Generators", "REPLACED")]
internal sealed class TestNamespace_IFactory_993557a2_Double : global::TestNamespace.IFactory
{
    internal sealed class __Create_State<Config>
    {
        // ADR-0050: multi-entry response configuration composed inside ADR-0049's
        // per-closed-T state - same Entry shape as the plain matching-eligible branch below, just
        // nested one level deeper (per closed T instead of per member).
        internal sealed class Entry
        {
            internal global::Compono.Match<int>? Matcher_id;
            internal global::Compono.ReturnConfig<Config> Config;
        }

        internal readonly global::System.Collections.Generic.List<Entry> Entries = [];
        internal readonly global::System.Collections.Generic.List<int> Calls = [];
        internal readonly object Lock = new();
    }

    internal readonly global::System.Collections.Generic.Dictionary<global::System.Type, object> __Create_buckets = new();

    internal __Create_State<Config> __Create_Bucket<Config>()
    {
        lock (__Create_buckets)
        {
            if (!__Create_buckets.TryGetValue(typeof(Config), out var __boxed))
            {
                __boxed = new __Create_State<Config>();
                __Create_buckets[typeof(Config)] = __boxed;
            }

            return (__Create_State<Config>)__boxed;
        }
    }

    Config global::TestNamespace.IFactory.Create<Config>(int id)
    {
        var __bucket = __Create_Bucket<Config>();
        // ADR-0050: reverse-scan the ordered entry list - last matching registration wins. Both
        // the call-log append and the full scan stay under the SAME lock acquisition as
        // Configure()'s Entries.Add() (Codex review, PR #108 round 5) - the prior split-lock shape
        // (a short lock around Calls.Add() only, then an unlocked scan) let a concurrent
        // Configure() call mutate List<T>'s backing array while dispatch was still iterating it.
        // `return`/`throw` inside a C# `lock` block still releases the lock (the compiler emits
        // the equivalent of try/finally), so returning directly from inside the block below is safe.
        lock (__bucket.Lock)
        {
            __bucket.Calls.Add(id);
            for (var __i = __bucket.Entries.Count - 1; __i >= 0; __i--)
            {
                var __entry = __bucket.Entries[__i];
                if ((__entry.Matcher_id is not { } __m_id || __m_id.Matches(id)))
                {
                    // ADR-0050: no `break` here (Codex review, PR #108 round 6) - if this entry
                    // matched but has neither a configured exception nor a configured value (e.g.
                    // its builder is still being set up when this call arrives), it must NOT shadow
                    // an older, fully-configured matching entry; the scan continues to the next
                    // (older) entry instead of falling through to the default/required-config rule.
                    if (__entry.Config.HasConfiguredException) throw __entry.Config.ConfiguredException;
                    if (__entry.Config.HasConfiguredValue) return __entry.Config.ConfiguredValue;
                }
            }
        }
        throw new global::Compono.TestDoubleNotConfiguredException(
            "'global::TestNamespace.IFactory.Create' was invoked without being configured (or without a matching argument configuration) for this closed type argument - call Configure().Create<Config>(...).Returns(...) or .Throws(...) before invoking it.");
    }
}

internal static class TestNamespace_IFactory_993557a2_DoubleConfiguration
{
    public static global::Compono.ReturnConfigBuilder<Config> Create<Config>(this global::TestNamespace_IFactory_993557a2_Double __self, global::Compono.Match<int> id)
    {
        // ADR-0050: appends a new entry rather than overwriting the (removed) single
        // slot - `ref entry.Config` stays valid regardless of later Entries.Add() reallocating the
        // list's backing array, since the ref targets the Entry object itself (heap-stable), not a
        // slot inside the list's array. See spike report for the reallocation-hazard proof. The
        // Add() itself is under the same member lock dispatch scans under (Codex review, PR #108
        // round 5) - concurrent Configure() calls must not race each other or a concurrent
        // in-progress dispatch scan while mutating the shared List<T>.
        var __bucket = __self.__Create_Bucket<Config>();
        var __entry = new global::TestNamespace_IFactory_993557a2_Double.__Create_State<Config>.Entry();
        __entry.Matcher_id = id;
        lock (__bucket.Lock) { __bucket.Entries.Add(__entry); }
        return new global::Compono.ReturnConfigBuilder<Config>(ref __entry.Config);
    }

}

internal readonly struct TestNamespace_IFactory_993557a2_DoubleVerifier
{
    internal global::TestNamespace_IFactory_993557a2_Double Instance { get; }

    internal TestNamespace_IFactory_993557a2_DoubleVerifier(global::TestNamespace_IFactory_993557a2_Double instance) => Instance = instance;
}

internal static class TestNamespace_IFactory_993557a2_VerifyExtension
{
    public static global::TestNamespace_IFactory_993557a2_DoubleVerifier Verify(this global::TestNamespace.IFactory self) =>
        new(self as global::TestNamespace_IFactory_993557a2_Double
            ?? throw new global::System.InvalidOperationException(
                $"'{self.GetType()}' is not the 'global::TestNamespace.IFactory' test double generated for this assembly. " +
                "If another assembly in this process also generated a double for 'global::TestNamespace.IFactory', only one " +
                "registration wins process-wide (Compono.GeneratedTestDoubleRegistry, first-registration-wins) " +
                "- this is a known v1 limitation, not a bug in your test."));
}

internal static class TestNamespace_IFactory_993557a2_DoubleVerification
{
    public static global::Compono.CallVerifier Create<Config>(this global::TestNamespace_IFactory_993557a2_DoubleVerifier __self, global::Compono.Match<int> id)
    {
        var __bucket = __self.Instance.__Create_Bucket<Config>();
        int __count;
        lock (__bucket.Lock)
        {
            __count = 0;
            foreach (var call in __bucket.Calls)
            {
                if (id.Matches(call))
                    __count++;
            }
        }
        return new(__count, "global::TestNamespace.IFactory.Create");
    }

}

internal static class TestNamespace_IFactory_993557a2_ConfigureExtension
{
    public static global::TestNamespace_IFactory_993557a2_Double Configure(this global::TestNamespace.IFactory self) =>
        self as global::TestNamespace_IFactory_993557a2_Double
            ?? throw new global::System.InvalidOperationException(
                $"'{self.GetType()}' is not the 'global::TestNamespace.IFactory' test double generated for this assembly. " +
                "If another assembly in this process also generated a double for 'global::TestNamespace.IFactory', only one " +
                "registration wins process-wide (Compono.GeneratedTestDoubleRegistry, first-registration-wins) " +
                "- this is a known v1 limitation, not a bug in your test.");
}

file static class TestNamespace_IFactory_993557a2_DoubleRegistration
{
    [global::System.Runtime.CompilerServices.ModuleInitializer]
    internal static void Register() =>
        global::Compono.GeneratedTestDoubleRegistry.RegisterFactory<global::TestNamespace.IFactory>(
            () => new global::TestNamespace_IFactory_993557a2_Double());
}
