//HintName: TestNamespace.ILeaf10_232473a5.TestDouble.g.cs
// <auto-generated/>
#nullable enable

[global::System.CodeDom.Compiler.GeneratedCode("Compono.Generators", "REPLACED")]
internal sealed class TestNamespace_ILeaf10_232473a5_Double : global::TestNamespace.ILeaf10
{
    internal delegate bool __Flag_Callback();

    internal readonly ref struct __Flag_Builder
    {
        private readonly ref global::Compono.ReturnConfig<bool> _config;
        private readonly ref __Flag_Callback? _callback;

        internal __Flag_Builder(ref global::Compono.ReturnConfig<bool> config, ref __Flag_Callback? callback)
        {
            _config = ref config;
            _callback = ref callback;
        }

        public void Returns(bool value)
        {
            _callback = null;
            new global::Compono.ReturnConfigBuilder<bool>(ref _config).Returns(value);
        }

        public void Throws(global::System.Exception exception)
        {
            _callback = null;
            new global::Compono.ReturnConfigBuilder<bool>(ref _config).Throws(exception);
        }

        public void ReturnsSequence(params global::Compono.SequenceOutcome<bool>[] outcomes)
        {
            _callback = null;
            new global::Compono.ReturnConfigBuilder<bool>(ref _config).ReturnsSequence(outcomes);
        }

        public void ReturnsCallback(__Flag_Callback callback)
        {
            global::System.ArgumentNullException.ThrowIfNull(callback);
            _config.ClearConfiguredResponse();
            _callback = callback;
        }
    }
    internal global::Compono.ReturnConfig<bool> __Flag;
    internal __Flag_Callback? __Flag_callback;

    bool global::TestNamespace.IBase10.Flag()
    {
        __Flag.RecordCall();
        return __Flag_callback is { } callback ? callback()
            : __Flag.HasConfiguredSequence ? __Flag.NextSequenceOutcome()
            : __Flag.HasConfiguredException ? throw __Flag.ConfiguredException
            : __Flag.HasConfiguredValue ? __Flag.ConfiguredValue
            : default;
    }
}

internal static class TestNamespace_ILeaf10_232473a5_DoubleConfiguration
{
    public static global::TestNamespace_ILeaf10_232473a5_Double.__Flag_Builder Flag(this global::TestNamespace_ILeaf10_232473a5_Double self) =>
        new global::TestNamespace_ILeaf10_232473a5_Double.__Flag_Builder(ref self.__Flag, ref self.__Flag_callback);

}

internal readonly struct TestNamespace_ILeaf10_232473a5_DoubleVerifier
{
    internal global::TestNamespace_ILeaf10_232473a5_Double Instance { get; }

    internal TestNamespace_ILeaf10_232473a5_DoubleVerifier(global::TestNamespace_ILeaf10_232473a5_Double instance) => Instance = instance;
}

internal static class TestNamespace_ILeaf10_232473a5_VerifyExtension
{
    public static global::TestNamespace_ILeaf10_232473a5_DoubleVerifier Verify(this global::TestNamespace.ILeaf10 self) =>
        new(self as global::TestNamespace_ILeaf10_232473a5_Double
            ?? throw new global::System.InvalidOperationException(
                $"'{self.GetType()}' is not the 'global::TestNamespace.ILeaf10' test double generated for this assembly. " +
                "If another assembly in this process also generated a double for 'global::TestNamespace.ILeaf10', only one " +
                "registration wins process-wide (Compono.GeneratedTestDoubleRegistry, first-registration-wins) " +
                "- this is a known v1 limitation, not a bug in your test."));
}

internal static class TestNamespace_ILeaf10_232473a5_DoubleVerification
{
    public static global::Compono.CallVerifier Flag(this global::TestNamespace_ILeaf10_232473a5_DoubleVerifier self) =>
        new(self.Instance.__Flag.ConfiguredCallCount, "global::TestNamespace.IBase10.Flag");

}

internal static class TestNamespace_ILeaf10_232473a5_ConfigureExtension
{
    public static global::TestNamespace_ILeaf10_232473a5_Double Configure(this global::TestNamespace.ILeaf10 self) =>
        self as global::TestNamespace_ILeaf10_232473a5_Double
            ?? throw new global::System.InvalidOperationException(
                $"'{self.GetType()}' is not the 'global::TestNamespace.ILeaf10' test double generated for this assembly. " +
                "If another assembly in this process also generated a double for 'global::TestNamespace.ILeaf10', only one " +
                "registration wins process-wide (Compono.GeneratedTestDoubleRegistry, first-registration-wins) " +
                "- this is a known v1 limitation, not a bug in your test.");
}

file static class TestNamespace_ILeaf10_232473a5_DoubleRegistration
{
    [global::System.Runtime.CompilerServices.ModuleInitializer]
    internal static void Register() =>
        global::Compono.GeneratedTestDoubleRegistry.RegisterFactory<global::TestNamespace.ILeaf10>(
            () => new global::TestNamespace_ILeaf10_232473a5_Double());
}
