//HintName: TestNamespace.IRepository_e3198068.TestDouble.g.cs
// <auto-generated/>
#nullable enable

[global::System.CodeDom.Compiler.GeneratedCode("Compono.Generators", "REPLACED")]
internal sealed class TestNamespace_IRepository_e3198068_Double : global::TestNamespace.IRepository
{
    internal global::Compono.ReturnConfig<bool> __TryGet;
    internal global::Compono.Arg<int>? __TryGet_m_id;
    internal readonly global::System.Collections.Generic.List<int> __TryGet_calls = [];
    internal readonly object __TryGet_lock = new();

    bool global::TestNamespace.IRepository.TryGet(int id, out string? value)
    {
        value = default;
        return default;
    }

    bool global::TestNamespace.IRepository.TryGet(int id)
    {
        __TryGet.RecordCall();
        lock (__TryGet_lock) { __TryGet_calls.Add(id); }
        var __matches = (__TryGet_m_id is not { } __m_id || __m_id.Matches(id));
        return __matches && __TryGet.HasConfiguredException ? throw __TryGet.ConfiguredException
            : __matches && __TryGet.HasConfiguredValue ? __TryGet.ConfiguredValue
            : default;
    }
}

internal static class TestNamespace_IRepository_e3198068_DoubleConfiguration
{
    public static global::Compono.ReturnConfigBuilder<bool> TryGet(this global::TestNamespace_IRepository_e3198068_Double self, global::Compono.Arg<int> id)
    {
        self.__TryGet_m_id = id;
        return new global::Compono.ReturnConfigBuilder<bool>(ref self.__TryGet);
    }

    // Compatibility overload (Codex review, PLAN-0048): v1/v2 gave every non-overloaded member a
    // zero-argument Configure(), regardless of real arity - a real existing call site
    // (Compono.TestDoubles.SampleTests' Save(int) usage) still uses it. Leaving every matcher field
    // null reproduces that exact argument-independent behavior (dispatch's `is not { } m ||
    // m.Matches(...)` treats null as always-matching), so this overload is purely additive, not a
    // second, different meaning.
    public static global::Compono.ReturnConfigBuilder<bool> TryGet(this global::TestNamespace_IRepository_e3198068_Double self) =>
        new global::Compono.ReturnConfigBuilder<bool>(ref self.__TryGet);

}

internal readonly struct TestNamespace_IRepository_e3198068_DoubleVerifier
{
    internal global::TestNamespace_IRepository_e3198068_Double Instance { get; }

    internal TestNamespace_IRepository_e3198068_DoubleVerifier(global::TestNamespace_IRepository_e3198068_Double instance) => Instance = instance;
}

internal static class TestNamespace_IRepository_e3198068_VerifyExtension
{
    public static global::TestNamespace_IRepository_e3198068_DoubleVerifier Verify(this global::TestNamespace.IRepository self) =>
        new(self as global::TestNamespace_IRepository_e3198068_Double
            ?? throw new global::System.InvalidOperationException(
                $"'{self.GetType()}' is not the 'global::TestNamespace.IRepository' test double generated for this assembly. " +
                "If another assembly in this process also generated a double for 'global::TestNamespace.IRepository', only one " +
                "registration wins process-wide (Compono.GeneratedTestDoubleRegistry, first-registration-wins) " +
                "- this is a known v1 limitation, not a bug in your test."));
}

internal static class TestNamespace_IRepository_e3198068_DoubleVerification
{
    public static global::Compono.CallVerifier TryGet(this global::TestNamespace_IRepository_e3198068_DoubleVerifier self, global::Compono.Arg<int> id)
    {
        int __count;
        lock (self.Instance.__TryGet_lock)
        {
            __count = 0;
            foreach (var call in self.Instance.__TryGet_calls)
            {
                if (id.Matches(call))
                    __count++;
            }
        }
        return new(__count, "global::TestNamespace.IRepository.TryGet");
    }

    // Compatibility overload - same reasoning as DoubleConfiguration's zero-argument sibling above:
    // reuses the still-maintained, unfiltered ConfiguredCallCount rather than walking the call log,
    // reproducing v1/v2's exact argument-independent Verify() for this member.
    public static global::Compono.CallVerifier TryGet(this global::TestNamespace_IRepository_e3198068_DoubleVerifier self) =>
        new(self.Instance.__TryGet.ConfiguredCallCount, "global::TestNamespace.IRepository.TryGet");

}

internal static class TestNamespace_IRepository_e3198068_ConfigureExtension
{
    public static global::TestNamespace_IRepository_e3198068_Double Configure(this global::TestNamespace.IRepository self) =>
        self as global::TestNamespace_IRepository_e3198068_Double
            ?? throw new global::System.InvalidOperationException(
                $"'{self.GetType()}' is not the 'global::TestNamespace.IRepository' test double generated for this assembly. " +
                "If another assembly in this process also generated a double for 'global::TestNamespace.IRepository', only one " +
                "registration wins process-wide (Compono.GeneratedTestDoubleRegistry, first-registration-wins) " +
                "- this is a known v1 limitation, not a bug in your test.");
}

file static class TestNamespace_IRepository_e3198068_DoubleRegistration
{
    [global::System.Runtime.CompilerServices.ModuleInitializer]
    internal static void Register() =>
        global::Compono.GeneratedTestDoubleRegistry.RegisterFactory<global::TestNamespace.IRepository>(
            () => new global::TestNamespace_IRepository_e3198068_Double());
}
