//HintName: TestNamespace.IRepository_e3198068.TestDouble.g.cs
// <auto-generated/>
#nullable enable

[global::System.CodeDom.Compiler.GeneratedCode("Compono.Generators", "REPLACED")]
internal sealed class TestNamespace_IRepository_e3198068_Double : global::TestNamespace.IRepository
{
    // ADR-0050: multi-entry response configuration - replaces the single
    // __TryGet/__TryGet_m_{param} shape with an ordered, append-only
    // entry list. Configure() appends; dispatch scans in reverse (last-matching-registration-wins).
    internal sealed class __TryGet_Entry
    {
        internal global::Compono.Match<int>? Matcher_id;
        internal global::Compono.ReturnConfig<bool> Config;
    }

    internal readonly global::System.Collections.Generic.List<__TryGet_Entry> __TryGet_entries = [];
    internal readonly global::System.Collections.Generic.List<int> __TryGet_calls = [];
    internal readonly object __TryGet_lock = new();

    bool global::TestNamespace.IRepository.TryGet(int id, out string? value)
    {
        value = default;
        return default;
    }

    bool global::TestNamespace.IRepository.TryGet(int id)
    {
        // ADR-0050: reverse-scan the ordered entry list - last matching registration wins. Both
        // the call-log append and the full scan stay under the SAME lock acquisition as
        // Configure()'s Add() (Codex review, PR #108 round 5) - the prior split-lock shape (a
        // short lock around _calls.Add() only, then an unlocked scan) let a concurrent Configure()
        // call mutate List<T>'s backing array while dispatch was still iterating it. `return`/
        // `throw` inside a C# `lock` block still releases the lock (try/finally under the hood).
        lock (__TryGet_lock)
        {
            __TryGet_calls.Add(id);
            for (var __i = __TryGet_entries.Count - 1; __i >= 0; __i--)
            {
                var __entry = __TryGet_entries[__i];
                if ((__entry.Matcher_id is not { } __m_id || __m_id.Matches(id)))
                {
                    // ADR-0050: no `break` here (Codex review, PR #108 round 6) - if this entry
                    // matched but has neither a configured exception nor a configured value (e.g.
                    // its builder is still being set up when this call arrives), it must NOT shadow
                    // an older, fully-configured matching entry; the scan continues to the next
                    // (older) entry instead of falling through to the default/required-config rule.
                    // ADR-0054: a configured sequence is checked first - Returns/Throws/ReturnsSequence
                    // are mutually exclusive on one Config, so order between this and the two checks
                    // below doesn't change behavior, but leads with the newest-added capability.
                    if (__entry.Config.HasConfiguredSequence) return __entry.Config.NextSequenceOutcome();
                    if (__entry.Config.HasConfiguredException) throw __entry.Config.ConfiguredException;
                    if (__entry.Config.HasConfiguredValue) return __entry.Config.ConfiguredValue;
                }
            }
        }
        return default;
    }
}

internal static class TestNamespace_IRepository_e3198068_DoubleConfiguration
{
    public static global::Compono.ReturnConfigBuilder<bool> TryGet(this global::TestNamespace_IRepository_e3198068_Double __self, global::Compono.Match<int> id)
    {
        // ADR-0050: appends a new entry - see the closed-instantiation Configure()
        // above for the reallocation-hazard proof, identical reasoning applies here. The Add()
        // itself is under the same member lock dispatch scans under (Codex review, PR #108
        // round 5).
        var __entry = new global::TestNamespace_IRepository_e3198068_Double.__TryGet_Entry();
        __entry.Matcher_id = id;
        lock (__self.__TryGet_lock) { __self.__TryGet_entries.Add(__entry); }
        return new global::Compono.ReturnConfigBuilder<bool>(ref __entry.Config);
    }

    // Compatibility overload (Codex review, PLAN-0048): v1/v2 gave every non-overloaded member a
    // zero-argument Configure(), regardless of real arity. ADR-0050: under multi-entry,
    // this no longer needs to null out prior matchers to reproduce "last wins" - it just appends its
    // own new, all-null-matcher (always-matching) entry; being the most-recently-appended entry, the
    // reverse scan finds it before any earlier, more specific entry, exactly reproducing v1/v2's
    // argument-independent override behavior without mutating any earlier entry's state at all.
    public static global::Compono.ReturnConfigBuilder<bool> TryGet(this global::TestNamespace_IRepository_e3198068_Double self)
    {
        var __entry = new global::TestNamespace_IRepository_e3198068_Double.__TryGet_Entry();
        lock (self.__TryGet_lock) { self.__TryGet_entries.Add(__entry); }
        return new global::Compono.ReturnConfigBuilder<bool>(ref __entry.Config);
    }

}

internal readonly struct TestNamespace_IRepository_e3198068_DoubleVerifier
{
    internal global::TestNamespace_IRepository_e3198068_Double Instance { get; }

    internal TestNamespace_IRepository_e3198068_DoubleVerifier(global::TestNamespace_IRepository_e3198068_Double instance) => Instance = instance;
}

internal static class TestNamespace_IRepository_e3198068_VerifyExtension
{
    public static global::TestNamespace_IRepository_e3198068_DoubleVerifier Verify(this global::TestNamespace.IRepository self) =>
        new(self as global::TestNamespace_IRepository_e3198068_Double
            ?? throw new global::System.InvalidOperationException(
                $"'{self.GetType()}' is not the 'global::TestNamespace.IRepository' test double generated for this assembly. " +
                "If another assembly in this process also generated a double for 'global::TestNamespace.IRepository', only one " +
                "registration wins process-wide (Compono.GeneratedTestDoubleRegistry, first-registration-wins) " +
                "- this is a known v1 limitation, not a bug in your test."));
}

internal static class TestNamespace_IRepository_e3198068_DoubleVerification
{
    public static global::Compono.CallVerifier TryGet(this global::TestNamespace_IRepository_e3198068_DoubleVerifier __self, global::Compono.Match<int> id)
    {
        int __count;
        lock (__self.Instance.__TryGet_lock)
        {
            __count = 0;
            foreach (var call in __self.Instance.__TryGet_calls)
            {
                if (id.Matches(call))
                    __count++;
            }
        }
        return new(__count, "global::TestNamespace.IRepository.TryGet");
    }

    // Compatibility overload - ADR-0050: the removed single-slot field no longer
    // tracks a call count at all (RecordCall() is gone from dispatch for this shape) - the call
    // log's own Count, under its existing lock, is exactly the same number and is already
    // maintained regardless of how many response entries exist.
    public static global::Compono.CallVerifier TryGet(this global::TestNamespace_IRepository_e3198068_DoubleVerifier self)
    {
        int __count;
        lock (self.Instance.__TryGet_lock) { __count = self.Instance.__TryGet_calls.Count; }
        return new(__count, "global::TestNamespace.IRepository.TryGet");
    }

}

internal static class TestNamespace_IRepository_e3198068_ConfigureExtension
{
    public static global::TestNamespace_IRepository_e3198068_Double Configure(this global::TestNamespace.IRepository self) =>
        self as global::TestNamespace_IRepository_e3198068_Double
            ?? throw new global::System.InvalidOperationException(
                $"'{self.GetType()}' is not the 'global::TestNamespace.IRepository' test double generated for this assembly. " +
                "If another assembly in this process also generated a double for 'global::TestNamespace.IRepository', only one " +
                "registration wins process-wide (Compono.GeneratedTestDoubleRegistry, first-registration-wins) " +
                "- this is a known v1 limitation, not a bug in your test.");
}

file static class TestNamespace_IRepository_e3198068_DoubleRegistration
{
    [global::System.Runtime.CompilerServices.ModuleInitializer]
    internal static void Register() =>
        global::Compono.GeneratedTestDoubleRegistry.RegisterFactory<global::TestNamespace.IRepository>(
            () => new global::TestNamespace_IRepository_e3198068_Double());
}
