//HintName: TestNamespace.IFactory_993557a2.TestDouble.g.cs
// <auto-generated/>
#nullable enable

[global::System.CodeDom.Compiler.GeneratedCode("Compono.Generators", "REPLACED")]
internal sealed class TestNamespace_IFactory_993557a2_Double : global::TestNamespace.IFactory
{
    internal sealed class __Get_State<T>
    {
        internal global::Compono.ReturnConfig<T> Config;
    }

    internal readonly global::System.Collections.Generic.Dictionary<global::System.Type, object> __Get_buckets = new();

    internal __Get_State<T> __Get_Bucket<T>()
    {
        lock (__Get_buckets)
        {
            if (!__Get_buckets.TryGetValue(typeof(T), out var boxed))
            {
                boxed = new __Get_State<T>();
                __Get_buckets[typeof(T)] = boxed;
            }

            return (__Get_State<T>)boxed;
        }
    }
    internal sealed class __Other_State<__Get_State>
    {
        internal global::Compono.ReturnConfig<__Get_State> Config;
    }

    internal readonly global::System.Collections.Generic.Dictionary<global::System.Type, object> __Other_buckets = new();

    internal __Other_State<__Get_State> __Other_Bucket<__Get_State>()
    {
        lock (__Other_buckets)
        {
            if (!__Other_buckets.TryGetValue(typeof(__Get_State), out var boxed))
            {
                boxed = new __Other_State<__Get_State>();
                __Other_buckets[typeof(__Get_State)] = boxed;
            }

            return (__Other_State<__Get_State>)boxed;
        }
    }

    T global::TestNamespace.IFactory.Get<T>()
    {
        var __bucket = __Get_Bucket<T>();
        __bucket.Config.RecordCall();
        return __bucket.Config.HasConfiguredException ? throw __bucket.Config.ConfiguredException
            : __bucket.Config.HasConfiguredValue ? __bucket.Config.ConfiguredValue
            : throw new global::Compono.TestDoubleNotConfiguredException(
                "'global::TestNamespace.IFactory.Get' was invoked without being configured (or without a matching argument configuration) for this closed type argument - call Configure().Get<T>(...).Returns(...) or .Throws(...) before invoking it.");
    }

    __Get_State global::TestNamespace.IFactory.Other<__Get_State>()
    {
        var __bucket = __Other_Bucket<__Get_State>();
        __bucket.Config.RecordCall();
        return __bucket.Config.HasConfiguredException ? throw __bucket.Config.ConfiguredException
            : __bucket.Config.HasConfiguredValue ? __bucket.Config.ConfiguredValue
            : throw new global::Compono.TestDoubleNotConfiguredException(
                "'global::TestNamespace.IFactory.Other' was invoked without being configured (or without a matching argument configuration) for this closed type argument - call Configure().Other<__Get_State>(...).Returns(...) or .Throws(...) before invoking it.");
    }
}

internal static class TestNamespace_IFactory_993557a2_DoubleConfiguration
{
    public static global::Compono.ReturnConfigBuilder<T> Get<T>(this global::TestNamespace_IFactory_993557a2_Double __self)
    {
        var __bucket = __self.__Get_Bucket<T>();
        return new global::Compono.ReturnConfigBuilder<T>(ref __bucket.Config);
    }

    public static global::Compono.ReturnConfigBuilder<__Get_State> Other<__Get_State>(this global::TestNamespace_IFactory_993557a2_Double __self)
    {
        var __bucket = __self.__Other_Bucket<__Get_State>();
        return new global::Compono.ReturnConfigBuilder<__Get_State>(ref __bucket.Config);
    }

}

internal readonly struct TestNamespace_IFactory_993557a2_DoubleVerifier
{
    internal global::TestNamespace_IFactory_993557a2_Double Instance { get; }

    internal TestNamespace_IFactory_993557a2_DoubleVerifier(global::TestNamespace_IFactory_993557a2_Double instance) => Instance = instance;
}

internal static class TestNamespace_IFactory_993557a2_VerifyExtension
{
    public static global::TestNamespace_IFactory_993557a2_DoubleVerifier Verify(this global::TestNamespace.IFactory self) =>
        new(self as global::TestNamespace_IFactory_993557a2_Double
            ?? throw new global::System.InvalidOperationException(
                $"'{self.GetType()}' is not the 'global::TestNamespace.IFactory' test double generated for this assembly. " +
                "If another assembly in this process also generated a double for 'global::TestNamespace.IFactory', only one " +
                "registration wins process-wide (Compono.GeneratedTestDoubleRegistry, first-registration-wins) " +
                "- this is a known v1 limitation, not a bug in your test."));
}

internal static class TestNamespace_IFactory_993557a2_DoubleVerification
{
    public static global::Compono.CallVerifier Get<T>(this global::TestNamespace_IFactory_993557a2_DoubleVerifier __self) =>
        new(__self.Instance.__Get_Bucket<T>().Config.ConfiguredCallCount, "global::TestNamespace.IFactory.Get");

    public static global::Compono.CallVerifier Other<__Get_State>(this global::TestNamespace_IFactory_993557a2_DoubleVerifier __self) =>
        new(__self.Instance.__Other_Bucket<__Get_State>().Config.ConfiguredCallCount, "global::TestNamespace.IFactory.Other");

}

internal static class TestNamespace_IFactory_993557a2_ConfigureExtension
{
    public static global::TestNamespace_IFactory_993557a2_Double Configure(this global::TestNamespace.IFactory self) =>
        self as global::TestNamespace_IFactory_993557a2_Double
            ?? throw new global::System.InvalidOperationException(
                $"'{self.GetType()}' is not the 'global::TestNamespace.IFactory' test double generated for this assembly. " +
                "If another assembly in this process also generated a double for 'global::TestNamespace.IFactory', only one " +
                "registration wins process-wide (Compono.GeneratedTestDoubleRegistry, first-registration-wins) " +
                "- this is a known v1 limitation, not a bug in your test.");
}

file static class TestNamespace_IFactory_993557a2_DoubleRegistration
{
    [global::System.Runtime.CompilerServices.ModuleInitializer]
    internal static void Register() =>
        global::Compono.GeneratedTestDoubleRegistry.RegisterFactory<global::TestNamespace.IFactory>(
            () => new global::TestNamespace_IFactory_993557a2_Double());
}
