//HintName: TestNamespace.IMultiMapper_d3a016dc.TestDouble.g.cs
// <auto-generated/>
#nullable enable

[global::System.CodeDom.Compiler.GeneratedCode("Compono.Generators", "REPLACED")]
internal sealed class TestNamespace_IMultiMapper_d3a016dc_Double : global::TestNamespace.IMultiMapper
{
    internal global::Compono.ReturnConfig<global::Compono.Unit> __Map;

    void global::TestNamespace.IMultiMapper.Map<TKey, TValue>(TKey key, TValue value)
    {
        __Map.RecordCall();
        if (__Map.HasConfiguredSequence)
            __Map.NextSequenceOutcome();
        else if (__Map.HasConfiguredException)
            throw __Map.ConfiguredException;
    }
}

internal static class TestNamespace_IMultiMapper_d3a016dc_DoubleConfiguration
{
    public static global::Compono.ReturnConfigBuilder<global::Compono.Unit> Map(this global::TestNamespace_IMultiMapper_d3a016dc_Double self) =>
        new global::Compono.ReturnConfigBuilder<global::Compono.Unit>(ref self.__Map);

}

internal readonly struct TestNamespace_IMultiMapper_d3a016dc_DoubleVerifier
{
    internal global::TestNamespace_IMultiMapper_d3a016dc_Double Instance { get; }

    internal TestNamespace_IMultiMapper_d3a016dc_DoubleVerifier(global::TestNamespace_IMultiMapper_d3a016dc_Double instance) => Instance = instance;
}

internal static class TestNamespace_IMultiMapper_d3a016dc_VerifyExtension
{
    public static global::TestNamespace_IMultiMapper_d3a016dc_DoubleVerifier Verify(this global::TestNamespace.IMultiMapper self) =>
        new(self as global::TestNamespace_IMultiMapper_d3a016dc_Double
            ?? throw new global::System.InvalidOperationException(
                $"'{self.GetType()}' is not the 'global::TestNamespace.IMultiMapper' test double generated for this assembly. " +
                "If another assembly in this process also generated a double for 'global::TestNamespace.IMultiMapper', only one " +
                "registration wins process-wide (Compono.GeneratedTestDoubleRegistry, first-registration-wins) " +
                "- this is a known v1 limitation, not a bug in your test."));
}

internal static class TestNamespace_IMultiMapper_d3a016dc_DoubleVerification
{
    public static global::Compono.CallVerifier Map(this global::TestNamespace_IMultiMapper_d3a016dc_DoubleVerifier self) =>
        new(self.Instance.__Map.ConfiguredCallCount, "global::TestNamespace.IMultiMapper.Map");

}

internal static class TestNamespace_IMultiMapper_d3a016dc_ConfigureExtension
{
    public static global::TestNamespace_IMultiMapper_d3a016dc_Double Configure(this global::TestNamespace.IMultiMapper self) =>
        self as global::TestNamespace_IMultiMapper_d3a016dc_Double
            ?? throw new global::System.InvalidOperationException(
                $"'{self.GetType()}' is not the 'global::TestNamespace.IMultiMapper' test double generated for this assembly. " +
                "If another assembly in this process also generated a double for 'global::TestNamespace.IMultiMapper', only one " +
                "registration wins process-wide (Compono.GeneratedTestDoubleRegistry, first-registration-wins) " +
                "- this is a known v1 limitation, not a bug in your test.");
}

file static class TestNamespace_IMultiMapper_d3a016dc_DoubleRegistration
{
    [global::System.Runtime.CompilerServices.ModuleInitializer]
    internal static void Register() =>
        global::Compono.GeneratedTestDoubleRegistry.RegisterFactory<global::TestNamespace.IMultiMapper>(
            () => new global::TestNamespace_IMultiMapper_d3a016dc_Double());
}
