//HintName: TestNamespace.ICollision_e0157ffc.TestDouble.g.cs
// <auto-generated/>
#nullable enable

// PLAN-0063/ADR-0060: ClearCalls() reaches every ADR-0049 closed-instantiation-eligible member's
// per-closed-T bucket entries generically, with no static knowledge of which closed T's exist at
// runtime - this non-generic interface (implemented by every generated
// TestNamespace_ICollision_e0157ffc_*State<T> class below) is what makes that possible without reflection.
internal interface TestNamespace_ICollision_e0157ffc_IClearableCallState
{
    void ClearObservedCalls();
}

[global::System.CodeDom.Compiler.GeneratedCode("Compono.Generators", "REPLACED")]
internal sealed class TestNamespace_ICollision_e0157ffc_Double : global::TestNamespace.ICollision
{
    internal delegate bool __Foo_Callback();

    internal readonly ref struct __Foo_Builder
    {
        private readonly ref global::Compono.ReturnConfig<bool> _config;
        private readonly ref __Foo_Callback? _callback;

        internal __Foo_Builder(ref global::Compono.ReturnConfig<bool> config, ref __Foo_Callback? callback)
        {
            _config = ref config;
            _callback = ref callback;
        }

        public void Returns(bool value)
        {
            _callback = null;
            new global::Compono.ReturnConfigBuilder<bool>(ref _config).Returns(value);
        }

        public void Throws(global::System.Exception exception)
        {
            _callback = null;
            new global::Compono.ReturnConfigBuilder<bool>(ref _config).Throws(exception);
        }

        public void ReturnsSequence(params global::Compono.SequenceOutcome<bool>[] outcomes)
        {
            _callback = null;
            new global::Compono.ReturnConfigBuilder<bool>(ref _config).ReturnsSequence(outcomes);
        }

        public void ReturnsCallback(__Foo_Callback callback)
        {
            global::System.ArgumentNullException.ThrowIfNull(callback);
            _config.ClearConfiguredResponse();
            _callback = callback;
        }
    }
    internal global::Compono.ReturnConfig<bool> __Foo;
    internal __Foo_Callback? __Foo_callback;
    internal global::Compono.ReturnConfig<global::Compono.Unit> __Foo_dimHelper;

    bool global::TestNamespace.ICollision.Foo()
    {
        __Foo.RecordCall();
        return __Foo_callback is { } callback ? callback()
            : __Foo.HasConfiguredSequence ? __Foo.NextSequenceOutcome()
            : __Foo.HasConfiguredException ? throw __Foo.ConfiguredException
            : __Foo.HasConfiguredValue ? __Foo.ConfiguredValue
            : default;
    }

    void global::TestNamespace.ICollision.Foo_dimHelper()
    {
        __Foo_dimHelper.RecordCall();
        if (__Foo_dimHelper.HasConfiguredSequence)
            __Foo_dimHelper.NextSequenceOutcome();
        else if (__Foo_dimHelper.HasConfiguredException)
            throw __Foo_dimHelper.ConfiguredException;
    }
}

internal static class TestNamespace_ICollision_e0157ffc_DoubleConfiguration
{
    public static global::TestNamespace_ICollision_e0157ffc_Double.__Foo_Builder Foo(this global::TestNamespace_ICollision_e0157ffc_Double self) =>
        new global::TestNamespace_ICollision_e0157ffc_Double.__Foo_Builder(ref self.__Foo, ref self.__Foo_callback);

    public static global::Compono.ReturnConfigBuilder<global::Compono.Unit> Foo_dimHelper(this global::TestNamespace_ICollision_e0157ffc_Double self) =>
        new global::Compono.ReturnConfigBuilder<global::Compono.Unit>(ref self.__Foo_dimHelper);

}

internal readonly struct TestNamespace_ICollision_e0157ffc_DoubleVerifier
{
    internal global::TestNamespace_ICollision_e0157ffc_Double Instance { get; }

    internal TestNamespace_ICollision_e0157ffc_DoubleVerifier(global::TestNamespace_ICollision_e0157ffc_Double instance) => Instance = instance;
}

internal static class TestNamespace_ICollision_e0157ffc_VerifyExtension
{
    public static global::TestNamespace_ICollision_e0157ffc_DoubleVerifier Verify(this global::TestNamespace.ICollision self) =>
        new(self as global::TestNamespace_ICollision_e0157ffc_Double
            ?? throw new global::System.InvalidOperationException(
                $"'{self.GetType()}' is not the 'global::TestNamespace.ICollision' test double generated for this assembly. " +
                "If another assembly in this process also generated a double for 'global::TestNamespace.ICollision', only one " +
                "registration wins process-wide (Compono.GeneratedTestDoubleRegistry, first-registration-wins) " +
                "- this is a known v1 limitation, not a bug in your test."));
}

internal static class TestNamespace_ICollision_e0157ffc_DoubleVerification
{
    public static global::Compono.CallVerifier Foo(this global::TestNamespace_ICollision_e0157ffc_DoubleVerifier self) =>
        new(self.Instance.__Foo.ConfiguredCallCount, "global::TestNamespace.ICollision.Foo");

    public static global::Compono.CallVerifier Foo_dimHelper(this global::TestNamespace_ICollision_e0157ffc_DoubleVerifier self) =>
        new(self.Instance.__Foo_dimHelper.ConfiguredCallCount, "global::TestNamespace.ICollision.Foo_dimHelper");

}

// PLAN-0063/ADR-0060: ReceivedCalls() - retrospective, snapshot-based call inspection, scoped to
// exactly the ADR-0048 eligible-member set (member.is_eligible_for_matching), unexpanded. A
// distinct third bridge from Configure()/Verify() - never attaches captured data to CallVerifier.
internal readonly struct TestNamespace_ICollision_e0157ffc_DoubleReceivedCalls
{
    internal global::TestNamespace_ICollision_e0157ffc_Double Instance { get; }

    internal TestNamespace_ICollision_e0157ffc_DoubleReceivedCalls(global::TestNamespace_ICollision_e0157ffc_Double instance) => Instance = instance;
}

internal static class TestNamespace_ICollision_e0157ffc_ReceivedCallsExtension
{
    public static global::TestNamespace_ICollision_e0157ffc_DoubleReceivedCalls ReceivedCalls(this global::TestNamespace.ICollision self) =>
        new(self as global::TestNamespace_ICollision_e0157ffc_Double
            ?? throw new global::System.InvalidOperationException(
                $"'{self.GetType()}' is not the 'global::TestNamespace.ICollision' test double generated for this assembly. " +
                "If another assembly in this process also generated a double for 'global::TestNamespace.ICollision', only one " +
                "registration wins process-wide (Compono.GeneratedTestDoubleRegistry, first-registration-wins) " +
                "- this is a known v1 limitation, not a bug in your test."));
}

internal static class TestNamespace_ICollision_e0157ffc_DoubleReceivedCallsAccess
{
}

// PLAN-0063/ADR-0060: ClearCalls() - a direct, whole-double operation clearing every member's
// observation state (scalar call counts + ADR-0048 captured argument histories) while preserving
// all configured behavior (Returns/Throws/ReturnsCallback/ReturnsSequence - including in-progress
// SequenceOrdinal, which does not rewind - argument-matcher/multi-entry configuration, and generic
// closed-instantiation configuration). No per-member ClearCalls(), no global whole-double lock -
// each member's own existing synchronization primitive is used independently, per member.
internal static class TestNamespace_ICollision_e0157ffc_ClearCallsExtension
{
    public static void ClearCalls(this global::TestNamespace.ICollision self)
    {
        var __double = self as global::TestNamespace_ICollision_e0157ffc_Double
            ?? throw new global::System.InvalidOperationException(
                $"'{self.GetType()}' is not the 'global::TestNamespace.ICollision' test double generated for this assembly. " +
                "If another assembly in this process also generated a double for 'global::TestNamespace.ICollision', only one " +
                "registration wins process-wide (Compono.GeneratedTestDoubleRegistry, first-registration-wins) " +
                "- this is a known v1 limitation, not a bug in your test.");

        __double.__Foo.ClearObservedCalls();
        __double.__Foo_dimHelper.ClearObservedCalls();
    }
}

internal static class TestNamespace_ICollision_e0157ffc_ConfigureExtension
{
    public static global::TestNamespace_ICollision_e0157ffc_Double Configure(this global::TestNamespace.ICollision self) =>
        self as global::TestNamespace_ICollision_e0157ffc_Double
            ?? throw new global::System.InvalidOperationException(
                $"'{self.GetType()}' is not the 'global::TestNamespace.ICollision' test double generated for this assembly. " +
                "If another assembly in this process also generated a double for 'global::TestNamespace.ICollision', only one " +
                "registration wins process-wide (Compono.GeneratedTestDoubleRegistry, first-registration-wins) " +
                "- this is a known v1 limitation, not a bug in your test.");
}

file static class TestNamespace_ICollision_e0157ffc_DoubleRegistration
{
    [global::System.Runtime.CompilerServices.ModuleInitializer]
    internal static void Register() =>
        global::Compono.GeneratedTestDoubleRegistry.RegisterFactory<global::TestNamespace.ICollision>(
            () => new global::TestNamespace_ICollision_e0157ffc_Double());
}
