//HintName: TestNamespace.IRepository_e3198068.TestDouble.g.cs
// <auto-generated/>
#nullable enable

[global::System.CodeDom.Compiler.GeneratedCode("Compono.Generators", "REPLACED")]
internal sealed class TestNamespace_IRepository_e3198068_Double : global::TestNamespace.IRepository
{
    internal global::Compono.ReturnConfig<global::Compono.Unit> __Get_b9dfaa09;
    internal global::Compono.ReturnConfig<global::Compono.Unit> __Get_1a56931a;

    void global::TestNamespace.IRepository.Get(int id)
    {
        if (__Get_b9dfaa09.HasConfiguredException)
            throw __Get_b9dfaa09.ConfiguredException;
    }

    void global::TestNamespace.IRepository.Get(string id)
    {
        if (__Get_1a56931a.HasConfiguredException)
            throw __Get_1a56931a.ConfiguredException;
    }
}

internal static class TestNamespace_IRepository_e3198068_DoubleConfiguration
{
    public static global::Compono.ReturnConfigBuilder<global::Compono.Unit> Get(this global::TestNamespace_IRepository_e3198068_Double __self, int id) =>
        new global::Compono.ReturnConfigBuilder<global::Compono.Unit>(ref __self.__Get_b9dfaa09);

    public static global::Compono.ReturnConfigBuilder<global::Compono.Unit> Get(this global::TestNamespace_IRepository_e3198068_Double __self, string id) =>
        new global::Compono.ReturnConfigBuilder<global::Compono.Unit>(ref __self.__Get_1a56931a);

}

internal static class TestNamespace_IRepository_e3198068_ConfigureExtension
{
    public static global::TestNamespace_IRepository_e3198068_Double Configure(this global::TestNamespace.IRepository self) =>
        self as global::TestNamespace_IRepository_e3198068_Double
            ?? throw new global::System.InvalidOperationException(
                $"'{self.GetType()}' is not the 'global::TestNamespace.IRepository' test double generated for this assembly. " +
                "If another assembly in this process also generated a double for 'global::TestNamespace.IRepository', only one " +
                "registration wins process-wide (Compono.GeneratedTestDoubleRegistry, first-registration-wins) " +
                "- this is a known v1 limitation, not a bug in your test.");
}

file static class TestNamespace_IRepository_e3198068_DoubleRegistration
{
    [global::System.Runtime.CompilerServices.ModuleInitializer]
    internal static void Register() =>
        global::Compono.GeneratedTestDoubleRegistry.RegisterFactory<global::TestNamespace.IRepository>(
            () => new global::TestNamespace_IRepository_e3198068_Double());
}
