//HintName: TestNamespace.ICollisionM_72d803a3.TestDouble.g.cs
// <auto-generated/>
#nullable enable

[global::System.CodeDom.Compiler.GeneratedCode("Compono.Generators", "REPLACED")]
internal sealed class TestNamespace_ICollisionM_72d803a3_Double : global::TestNamespace.ICollisionM
{
    internal global::Compono.ReturnConfig<bool> __M;

    bool global::TestNamespace.ICollisionM.M()
    {
        __M.RecordCall();
        return __M.HasConfiguredSequence ? __M.NextSequenceOutcome()
            : __M.HasConfiguredException ? throw __M.ConfiguredException
            : __M.HasConfiguredValue ? __M.ConfiguredValue
            : default;
    }

    bool global::TestNamespace.ICollisionM.M(ref int value)
    {
        return default;
    }
}

internal static class TestNamespace_ICollisionM_72d803a3_DoubleConfiguration
{
    public static global::Compono.ReturnConfigBuilder<bool> M(this global::TestNamespace_ICollisionM_72d803a3_Double self) =>
        new global::Compono.ReturnConfigBuilder<bool>(ref self.__M);

}

internal readonly struct TestNamespace_ICollisionM_72d803a3_DoubleVerifier
{
    internal global::TestNamespace_ICollisionM_72d803a3_Double Instance { get; }

    internal TestNamespace_ICollisionM_72d803a3_DoubleVerifier(global::TestNamespace_ICollisionM_72d803a3_Double instance) => Instance = instance;
}

internal static class TestNamespace_ICollisionM_72d803a3_VerifyExtension
{
    public static global::TestNamespace_ICollisionM_72d803a3_DoubleVerifier Verify(this global::TestNamespace.ICollisionM self) =>
        new(self as global::TestNamespace_ICollisionM_72d803a3_Double
            ?? throw new global::System.InvalidOperationException(
                $"'{self.GetType()}' is not the 'global::TestNamespace.ICollisionM' test double generated for this assembly. " +
                "If another assembly in this process also generated a double for 'global::TestNamespace.ICollisionM', only one " +
                "registration wins process-wide (Compono.GeneratedTestDoubleRegistry, first-registration-wins) " +
                "- this is a known v1 limitation, not a bug in your test."));
}

internal static class TestNamespace_ICollisionM_72d803a3_DoubleVerification
{
    public static global::Compono.CallVerifier M(this global::TestNamespace_ICollisionM_72d803a3_DoubleVerifier self) =>
        new(self.Instance.__M.ConfiguredCallCount, "global::TestNamespace.ICollisionM.M");

}

internal static class TestNamespace_ICollisionM_72d803a3_ConfigureExtension
{
    public static global::TestNamespace_ICollisionM_72d803a3_Double Configure(this global::TestNamespace.ICollisionM self) =>
        self as global::TestNamespace_ICollisionM_72d803a3_Double
            ?? throw new global::System.InvalidOperationException(
                $"'{self.GetType()}' is not the 'global::TestNamespace.ICollisionM' test double generated for this assembly. " +
                "If another assembly in this process also generated a double for 'global::TestNamespace.ICollisionM', only one " +
                "registration wins process-wide (Compono.GeneratedTestDoubleRegistry, first-registration-wins) " +
                "- this is a known v1 limitation, not a bug in your test.");
}

file static class TestNamespace_ICollisionM_72d803a3_DoubleRegistration
{
    [global::System.Runtime.CompilerServices.ModuleInitializer]
    internal static void Register() =>
        global::Compono.GeneratedTestDoubleRegistry.RegisterFactory<global::TestNamespace.ICollisionM>(
            () => new global::TestNamespace_ICollisionM_72d803a3_Double());
}
