//HintName: TestNamespace.IRepository_e3198068.TestDouble.g.cs
// <auto-generated/>
#nullable enable

[global::System.CodeDom.Compiler.GeneratedCode("Compono.Generators", "REPLACED")]
internal sealed class TestNamespace_IRepository_e3198068_Double : global::TestNamespace.IRepository
{
    internal delegate global::System.Collections.Generic.List<int>? __GetValues_Callback();

    internal readonly ref struct __GetValues_Builder
    {
        private readonly ref global::Compono.ReturnConfig<global::System.Collections.Generic.List<int>?> _config;
        private readonly ref __GetValues_Callback? _callback;

        internal __GetValues_Builder(ref global::Compono.ReturnConfig<global::System.Collections.Generic.List<int>?> config, ref __GetValues_Callback? callback)
        {
            _config = ref config;
            _callback = ref callback;
        }

        public void Returns(global::System.Collections.Generic.List<int>? value)
        {
            _callback = null;
            new global::Compono.ReturnConfigBuilder<global::System.Collections.Generic.List<int>?>(ref _config).Returns(value);
        }

        public void Throws(global::System.Exception exception)
        {
            _callback = null;
            new global::Compono.ReturnConfigBuilder<global::System.Collections.Generic.List<int>?>(ref _config).Throws(exception);
        }

        public void ReturnsSequence(params global::Compono.SequenceOutcome<global::System.Collections.Generic.List<int>?>[] outcomes)
        {
            _callback = null;
            new global::Compono.ReturnConfigBuilder<global::System.Collections.Generic.List<int>?>(ref _config).ReturnsSequence(outcomes);
        }

        public void ReturnsCallback(__GetValues_Callback callback)
        {
            global::System.ArgumentNullException.ThrowIfNull(callback);
            _config.ClearConfiguredResponse();
            _callback = callback;
        }
    }
    internal global::Compono.ReturnConfig<global::System.Collections.Generic.List<int>?> __GetValues;
    internal __GetValues_Callback? __GetValues_callback;

    global::System.Collections.Generic.List<int>? global::TestNamespace.IRepository.GetValues()
    {
        __GetValues.RecordCall();
        return __GetValues_callback is { } callback ? callback()
            : __GetValues.HasConfiguredSequence ? __GetValues.NextSequenceOutcome()
            : __GetValues.HasConfiguredException ? throw __GetValues.ConfiguredException
            : __GetValues.HasConfiguredValue ? __GetValues.ConfiguredValue
            : [];
    }
}

internal static class TestNamespace_IRepository_e3198068_DoubleConfiguration
{
    public static global::TestNamespace_IRepository_e3198068_Double.__GetValues_Builder GetValues(this global::TestNamespace_IRepository_e3198068_Double self) =>
        new global::TestNamespace_IRepository_e3198068_Double.__GetValues_Builder(ref self.__GetValues, ref self.__GetValues_callback);

}

internal readonly struct TestNamespace_IRepository_e3198068_DoubleVerifier
{
    internal global::TestNamespace_IRepository_e3198068_Double Instance { get; }

    internal TestNamespace_IRepository_e3198068_DoubleVerifier(global::TestNamespace_IRepository_e3198068_Double instance) => Instance = instance;
}

internal static class TestNamespace_IRepository_e3198068_VerifyExtension
{
    public static global::TestNamespace_IRepository_e3198068_DoubleVerifier Verify(this global::TestNamespace.IRepository self) =>
        new(self as global::TestNamespace_IRepository_e3198068_Double
            ?? throw new global::System.InvalidOperationException(
                $"'{self.GetType()}' is not the 'global::TestNamespace.IRepository' test double generated for this assembly. " +
                "If another assembly in this process also generated a double for 'global::TestNamespace.IRepository', only one " +
                "registration wins process-wide (Compono.GeneratedTestDoubleRegistry, first-registration-wins) " +
                "- this is a known v1 limitation, not a bug in your test."));
}

internal static class TestNamespace_IRepository_e3198068_DoubleVerification
{
    public static global::Compono.CallVerifier GetValues(this global::TestNamespace_IRepository_e3198068_DoubleVerifier self) =>
        new(self.Instance.__GetValues.ConfiguredCallCount, "global::TestNamespace.IRepository.GetValues");

}

internal static class TestNamespace_IRepository_e3198068_ConfigureExtension
{
    public static global::TestNamespace_IRepository_e3198068_Double Configure(this global::TestNamespace.IRepository self) =>
        self as global::TestNamespace_IRepository_e3198068_Double
            ?? throw new global::System.InvalidOperationException(
                $"'{self.GetType()}' is not the 'global::TestNamespace.IRepository' test double generated for this assembly. " +
                "If another assembly in this process also generated a double for 'global::TestNamespace.IRepository', only one " +
                "registration wins process-wide (Compono.GeneratedTestDoubleRegistry, first-registration-wins) " +
                "- this is a known v1 limitation, not a bug in your test.");
}

file static class TestNamespace_IRepository_e3198068_DoubleRegistration
{
    [global::System.Runtime.CompilerServices.ModuleInitializer]
    internal static void Register() =>
        global::Compono.GeneratedTestDoubleRegistry.RegisterFactory<global::TestNamespace.IRepository>(
            () => new global::TestNamespace_IRepository_e3198068_Double());
}
